// Code generated by internal/codegen. DO NOT EDIT.

package session

import "fmt"

// SemanticAction identifies a protocol-level semantic action.
// Each constant corresponds to one entry in semantics/mappings.yaml.
type SemanticAction uint16

const (
	ActionUnknown SemanticAction = 0
	ActionAcAcceptLogin SemanticAction = 1
	ActionAcAckHash SemanticAction = 2
	ActionAcRefuseLogin SemanticAction = 3
	ActionAccessibleMaps SemanticAction = 4
	ActionAccountId SemanticAction = 5
	ActionActorAction SemanticAction = 6
	ActionActorConnected SemanticAction = 7
	ActionActorDiedOrDisappeared SemanticAction = 8
	ActionActorExists SemanticAction = 9
	ActionActorMoved SemanticAction = 10
	ActionActorStatusActive SemanticAction = 11
	ActionActorStatusEffectExtended SemanticAction = 12
	ActionAddExchangeItem SemanticAction = 13
	ActionAreaSpell SemanticAction = 14
	ActionAttackRange SemanticAction = 15
	ActionAutoSpell SemanticAction = 16
	ActionBankingCheck SemanticAction = 17
	ActionBankingDeposit SemanticAction = 18
	ActionBankingOpen SemanticAction = 19
	ActionBankingWithdraw SemanticAction = 20
	ActionCaConnectInfoChanged SemanticAction = 21
	ActionCaExeHashcheck SemanticAction = 22
	ActionCaLogin2 SemanticAction = 23
	ActionCaLogin3 SemanticAction = 24
	ActionCaLogin4 SemanticAction = 25
	ActionCaLoginChannel SemanticAction = 26
	ActionCaLoginPcbang SemanticAction = 27
	ActionCaReqHash SemanticAction = 28
	ActionCaSsoLoginReq SemanticAction = 29
	ActionCastCancelled SemanticAction = 30
	ActionCatchPet SemanticAction = 31
	ActionChangeCart SemanticAction = 32
	ActionCharCreate SemanticAction = 33
	ActionCharCreated SemanticAction = 34
	ActionCharDelete SemanticAction = 35
	ActionCharacterBlocked SemanticAction = 36
	ActionCharacterCreationFailed SemanticAction = 37
	ActionCharacterMove SemanticAction = 38
	ActionCharacterMoves SemanticAction = 39
	ActionCharacterPagesNotify SemanticAction = 40
	ActionCharacterServerRefused SemanticAction = 41
	ActionChatMessage SemanticAction = 42
	ActionCloseStorage SemanticAction = 43
	ActionCloseVending SemanticAction = 44
	ActionCtAuth SemanticAction = 45
	ActionCzAckAnswerMacroDetector SemanticAction = 46
	ActionCzAdvancedStatusChange SemanticAction = 47
	ActionCzAdventurerAgencyJoinReq SemanticAction = 48
	ActionCzAdventurerAgencyJoinResult SemanticAction = 49
	ActionCzApproximateActor SemanticAction = 50
	ActionCzCheckname1 SemanticAction = 51
	ActionCzCheckname2 SemanticAction = 52
	ActionCzChooseMenuZero SemanticAction = 53
	ActionCzClientVersion SemanticAction = 54
	ActionCzCloseMsgboxExtendBodyitemSize SemanticAction = 55
	ActionCzCloseRefiningUi SemanticAction = 56
	ActionCzCloseReformUi SemanticAction = 57
	ActionCzCloseUiEnchant SemanticAction = 58
	ActionCzCloseUiStylingshop SemanticAction = 59
	ActionCzCmdResetcooltime SemanticAction = 60
	ActionCzCompleteApplyMacroDetectorCaptcha SemanticAction = 61
	ActionCzDynamicnpcCreateRequest SemanticAction = 62
	ActionCzGetAccountLimtiedSaleList SemanticAction = 63
	ActionCzGradeEnchantCloseUi SemanticAction = 64
	ActionCzGradeEnchantRequest SemanticAction = 65
	ActionCzGradeEnchantSelectEquipment SemanticAction = 66
	ActionCzInventoryTab SemanticAction = 67
	ActionCzItemReform SemanticAction = 68
	ActionCzJoinGuild SemanticAction = 69
	ActionCzMoveItemFromBodyToCart SemanticAction = 70
	ActionCzNpcBarterMarketClose SemanticAction = 71
	ActionCzNpcBarterMarketPurchase SemanticAction = 72
	ActionCzNpcExpandedBarterMarketClose SemanticAction = 73
	ActionCzNpcExpandedBarterMarketPurchase SemanticAction = 74
	ActionCzPartyConfig SemanticAction = 75
	ActionCzPartyJoinReq SemanticAction = 76
	ActionCzPartyJoinReqAck SemanticAction = 77
	ActionCzPcPurchaseItemlistFrommc SemanticAction = 78
	ActionCzPcPurchaseItemlistFrommc2 SemanticAction = 79
	ActionCzPingLive SemanticAction = 80
	ActionCzRandomCombineItemUiClose SemanticAction = 81
	ActionCzRandomUpgradeItemUiClose SemanticAction = 82
	ActionCzRefiningSelectItem SemanticAction = 83
	ActionCzReqAgitInvestment SemanticAction = 84
	ActionCzReqApplyBargainSaleItem SemanticAction = 85
	ActionCzReqApplyMacroDetector SemanticAction = 86
	ActionCzReqBanGuild SemanticAction = 87
	ActionCzReqCashBargainSaleItemInfo SemanticAction = 88
	ActionCzReqChangeMemberpos SemanticAction = 89
	ActionCzReqDisorganizeGuild SemanticAction = 90
	ActionCzReqExtendBodyitemSize SemanticAction = 91
	ActionCzReqGuildEmblemImg1 SemanticAction = 92
	ActionCzReqGuildEmblemImg2 SemanticAction = 93
	ActionCzReqGuildEmblemImg3 SemanticAction = 94
	ActionCzReqItemrepair2 SemanticAction = 95
	ActionCzReqJoinGuild SemanticAction = 96
	ActionCzReqJoinGuild2 SemanticAction = 97
	ActionCzReqLeaveGuild SemanticAction = 98
	ActionCzReqMakingarrow SemanticAction = 99
	ActionCzReqMergeItem SemanticAction = 100
	ActionCzReqMoveGuildAgit SemanticAction = 101
	ActionCzReqOpenMsgboxExtendBodyitemSize SemanticAction = 102
	ActionCzReqPlayerAidInRange SemanticAction = 103
	ActionCzReqPreviewMacroDetector SemanticAction = 104
	ActionCzReqRandomCombineItem SemanticAction = 105
	ActionCzReqRandomUpgradeItem SemanticAction = 106
	ActionCzReqRefining SemanticAction = 107
	ActionCzReqRemaintime SemanticAction = 108
	ActionCzReqRemoveBargainSaleItem SemanticAction = 109
	ActionCzReqSeCashTabCode SemanticAction = 110
	ActionCzReqTakeoffEquipAll SemanticAction = 111
	ActionCzReqUploadMacroDetector SemanticAction = 112
	ActionCzRequestPerfectEnchant SemanticAction = 113
	ActionCzRequestRandomEnchant SemanticAction = 114
	ActionCzRequestResetEnchant SemanticAction = 115
	ActionCzRequestUpgradeEnchant SemanticAction = 116
	ActionCzResetSkill SemanticAction = 117
	ActionCzRodexReturn SemanticAction = 118
	ActionCzSeCashshopOpen1 SemanticAction = 119
	ActionCzSeCashshopOpen2 SemanticAction = 120
	ActionCzSePcBuyCashitemList SemanticAction = 121
	ActionCzShortcutKeyChange1 SemanticAction = 122
	ActionCzShortcutKeyChange2 SemanticAction = 123
	ActionCzShortcutkeybarRotate1 SemanticAction = 124
	ActionCzShortcutkeybarRotate2 SemanticAction = 125
	ActionCzUninstallation SemanticAction = 126
	ActionCzUploadMacroDetectorCaptcha SemanticAction = 127
	ActionCzUsePackageitem SemanticAction = 128
	ActionCzUseSkillEnd SemanticAction = 129
	ActionCzUseSkillStart SemanticAction = 130
	ActionCzViewCamerainfo SemanticAction = 131
	ActionDealAddOther SemanticAction = 132
	ActionDealCancel SemanticAction = 133
	ActionDealFinalize SemanticAction = 134
	ActionDealInitiate SemanticAction = 135
	ActionDealReply SemanticAction = 136
	ActionDealRequest SemanticAction = 137
	ActionDealTrade SemanticAction = 138
	ActionDropItem SemanticAction = 139
	ActionEmote SemanticAction = 140
	ActionEnterWorld SemanticAction = 141
	ActionEntityMove SemanticAction = 142
	ActionEntitySpawn SemanticAction = 143
	ActionEquipItem SemanticAction = 144
	ActionExp SemanticAction = 145
	ActionFriendsAdd SemanticAction = 146
	ActionFriendsRemove SemanticAction = 147
	ActionFriendsReply SemanticAction = 148
	ActionGameLogin SemanticAction = 149
	ActionGetItemFromCart SemanticAction = 150
	ActionGuildChat SemanticAction = 151
	ActionHomunculusAttack SemanticAction = 152
	ActionHomunculusInfo SemanticAction = 153
	ActionHomunculusMenu SemanticAction = 154
	ActionIgnoreListReq SemanticAction = 155
	ActionInsertCard SemanticAction = 156
	ActionInventoryItemsEquip SemanticAction = 157
	ActionInventoryItemsStackable SemanticAction = 158
	ActionItemAppeared SemanticAction = 159
	ActionItemExists SemanticAction = 160
	ActionItemIdentify SemanticAction = 161
	ActionItemPickup SemanticAction = 162
	ActionItemUse SemanticAction = 163
	ActionLoginError SemanticAction = 164
	ActionLook SemanticAction = 165
	ActionMailReceive SemanticAction = 166
	ActionMapChanged SemanticAction = 167
	ActionMapLoaded SemanticAction = 168
	ActionMapLogin SemanticAction = 169
	ActionMarketPurchase SemanticAction = 170
	ActionMasterLogin SemanticAction = 171
	ActionMonsterHpUpdate SemanticAction = 172
	ActionMonsterRangedAttack SemanticAction = 173
	ActionMoveFromStorage SemanticAction = 174
	ActionMoveTo SemanticAction = 175
	ActionMoveToStorage SemanticAction = 176
	ActionNpcContact SemanticAction = 177
	ActionNpcMarketClose SemanticAction = 178
	ActionNpcMenuResponse SemanticAction = 179
	ActionNpcStoreInfo SemanticAction = 180
	ActionNpcTalkClose SemanticAction = 181
	ActionNpcTalkContinue SemanticAction = 182
	ActionNpcTalkNumber SemanticAction = 183
	ActionNpcTalkText SemanticAction = 184
	ActionNpcTradeQuit SemanticAction = 185
	ActionPartyChangeOption SemanticAction = 186
	ActionPartyCreate SemanticAction = 187
	ActionPartyInvite SemanticAction = 188
	ActionPartyKick SemanticAction = 189
	ActionPartyLeave SemanticAction = 190
	ActionPetEggList SemanticAction = 191
	ActionPetInfo SemanticAction = 192
	ActionPetMenu SemanticAction = 193
	ActionPickupItem SemanticAction = 194
	ActionPinCodeRequest SemanticAction = 195
	ActionPinCodeResponse SemanticAction = 196
	ActionPrivateMessage SemanticAction = 197
	ActionPublicChat SemanticAction = 198
	ActionQuestDialog SemanticAction = 199
	ActionQuestDialogList SemanticAction = 200
	ActionQuestUpdateMissionHunt SemanticAction = 201
	ActionQuitGame SemanticAction = 202
	ActionReceivedCharacterIDAndMap SemanticAction = 203
	ActionReceivedCharacterIdAndMap SemanticAction = 204
	ActionReceivedCharacters SemanticAction = 205
	ActionReceivedCharactersInfo SemanticAction = 206
	ActionReceivedCharactersPage SemanticAction = 207
	ActionReceivedMapServerInfo SemanticAction = 208
	ActionRemoveOption SemanticAction = 209
	ActionRepairItem SemanticAction = 210
	ActionReplyPartyInvite SemanticAction = 211
	ActionRequestBuySellList SemanticAction = 212
	ActionRequestCharacterPage SemanticAction = 213
	ActionRequestMemo SemanticAction = 214
	ActionRestart SemanticAction = 215
	ActionScNotifyBan SemanticAction = 216
	ActionSelectAccessibleMap SemanticAction = 217
	ActionSelectCharacter SemanticAction = 218
	ActionSelectEgg SemanticAction = 219
	ActionSelfChat SemanticAction = 220
	ActionSellResult SemanticAction = 221
	ActionSendEmotion SemanticAction = 222
	ActionShopBuy SemanticAction = 223
	ActionShopSell SemanticAction = 224
	ActionSkillAdd SemanticAction = 225
	ActionSkillCast SemanticAction = 226
	ActionSkillDelete SemanticAction = 227
	ActionSkillPostDelay SemanticAction = 228
	ActionSkillUp SemanticAction = 229
	ActionSkillUpdate SemanticAction = 230
	ActionSkillUse SemanticAction = 231
	ActionSkillUseFailed SemanticAction = 232
	ActionSkillUseLocation SemanticAction = 233
	ActionSkillUsedNoDamage SemanticAction = 234
	ActionSkillsList SemanticAction = 235
	ActionStatUpdate SemanticAction = 236
	ActionStatusUp SemanticAction = 237
	ActionSync SemanticAction = 238
	ActionTcResult SemanticAction = 239
	ActionTimeSyncResponse SemanticAction = 240
	ActionUnequipItem SemanticAction = 241
	ActionUseCard SemanticAction = 242
	ActionVenderFound SemanticAction = 243
	ActionVendingListReq SemanticAction = 244
	ActionWeaponRefine SemanticAction = 245
	ActionWhisper SemanticAction = 246
	ActionWhisperSent SemanticAction = 247
	ActionZcAcceptEnter SemanticAction = 248
	ActionZcAckAddExchangeItem SemanticAction = 249
	ActionZcAckAddItemRodex SemanticAction = 250
	ActionZcAckAdditemToCart SemanticAction = 251
	ActionZcAckApplyMacroDetector SemanticAction = 252
	ActionZcAckCashBargainSaleItemInfo SemanticAction = 253
	ActionZcAckCloseBanking SemanticAction = 254
	ActionZcAckCloseRoulette SemanticAction = 255
	ActionZcAckCountBargainSaleItem SemanticAction = 256
	ActionZcAckCreateChatroom SemanticAction = 257
	ActionZcAckDisorganizeGuildResult SemanticAction = 258
	ActionZcAckExtendBodyitemSize SemanticAction = 259
	ActionZcAckGuildstorageLog SemanticAction = 260
	ActionZcAckItemcomposition SemanticAction = 261
	ActionZcAckItemidentify SemanticAction = 262
	ActionZcAckItemrefining SemanticAction = 263
	ActionZcAckItemrepair SemanticAction = 264
	ActionZcAckMakeGroup SemanticAction = 265
	ActionZcAckMergeItem SemanticAction = 266
	ActionZcAckOpenMsgboxExtendBodyitemSize SemanticAction = 267
	ActionZcAckOpenstore2 SemanticAction = 268
	ActionZcAckPlayerAidInRange SemanticAction = 269
	ActionZcAckPreviewMacroDetector SemanticAction = 270
	ActionZcAckRandomCombineItem SemanticAction = 271
	ActionZcAckRandomUpgradeItem SemanticAction = 272
	ActionZcAckRanking SemanticAction = 273
	ActionZcAckReadRodex SemanticAction = 274
	ActionZcAckRememberWarppoint SemanticAction = 275
	ActionZcAckReqJoinGuild SemanticAction = 276
	ActionZcAckReqnameall SemanticAction = 277
	ActionZcAckReqnameallNpc SemanticAction = 278
	ActionZcAckSeCashItemList2 SemanticAction = 279
	ActionZcAckTakeoffEquipAll SemanticAction = 280
	ActionZcAckUploadMacroDetector SemanticAction = 281
	ActionZcActionFailure SemanticAction = 282
	ActionZcAddItemToCart SemanticAction = 283
	ActionZcAddItemToStore SemanticAction = 284
	ActionZcAdventurerAgencyJoinReq SemanticAction = 285
	ActionZcAdventurerAgencyJoinResult SemanticAction = 286
	ActionZcApplyMacroDetector SemanticAction = 287
	ActionZcApplyMacroDetectorCaptcha SemanticAction = 288
	ActionZcAutorunSkill SemanticAction = 289
	ActionZcAutospelllist SemanticAction = 290
	ActionZcBattlefieldNotifyHp SemanticAction = 291
	ActionZcBossInfo SemanticAction = 292
	ActionZcBroadcast SemanticAction = 293
	ActionZcBroadcast2 SemanticAction = 294
	ActionZcBroadcastItemrefiningResult SemanticAction = 295
	ActionZcBroadcastingSpecialItemObtainItem SemanticAction = 296
	ActionZcBuyingStoreEntry SemanticAction = 297
	ActionZcCMarkerinfo SemanticAction = 298
	ActionZcCancelExchangeItem SemanticAction = 299
	ActionZcCartoff SemanticAction = 300
	ActionZcChangeGuild SemanticAction = 301
	ActionZcChangeItemOption SemanticAction = 302
	ActionZcChangestatePet SemanticAction = 303
	ActionZcCheckname SemanticAction = 304
	ActionZcClaninfo SemanticAction = 305
	ActionZcClearDialog SemanticAction = 306
	ActionZcCloseDialog SemanticAction = 307
	ActionZcCloseMacroDetector SemanticAction = 308
	ActionZcCloseStore SemanticAction = 309
	ActionZcCompass SemanticAction = 310
	ActionZcCompleteUploadMacroDetectorCaptcha SemanticAction = 311
	ActionZcCouplename SemanticAction = 312
	ActionZcCouplestatus SemanticAction = 313
	ActionZcDebugmsg SemanticAction = 314
	ActionZcDeleteItemFromBody SemanticAction = 315
	ActionZcDeleteItemFromCart SemanticAction = 316
	ActionZcDeleteItemFromStore SemanticAction = 317
	ActionZcDeleteMemberFromGroup SemanticAction = 318
	ActionZcDeleteitemFromMcstore SemanticAction = 319
	ActionZcDialogTextAlign SemanticAction = 320
	ActionZcDialogWindowPos SemanticAction = 321
	ActionZcDialogWindowPos2 SemanticAction = 322
	ActionZcDialogWindowSize SemanticAction = 323
	ActionZcDisappearBuyingStoreEntry SemanticAction = 324
	ActionZcDynamicnpcCreateResult SemanticAction = 325
	ActionZcElParChange SemanticAction = 326
	ActionZcEntryQueueInit SemanticAction = 327
	ActionZcEquipArrow SemanticAction = 328
	ActionZcEquipitemDamaged SemanticAction = 329
	ActionZcEquipmentEffect SemanticAction = 330
	ActionZcEquipwinMicroscope SemanticAction = 331
	ActionZcExchangeitemUndo SemanticAction = 332
	ActionZcExecExchangeItem SemanticAction = 333
	ActionZcExtendBodyitemSize SemanticAction = 334
	ActionZcFriendsList SemanticAction = 335
	ActionZcGoldpccafePoint SemanticAction = 336
	ActionZcGradeEnchantAck SemanticAction = 337
	ActionZcGradeEnchantBroadcastResult SemanticAction = 338
	ActionZcGradeEnchantMaterialList SemanticAction = 339
	ActionZcGuildAgitInfo SemanticAction = 340
	ActionZcGuildEmblemImg SemanticAction = 341
	ActionZcGuildInfo SemanticAction = 342
	ActionZcGuildNotice SemanticAction = 343
	ActionZcGuildSkillinfo SemanticAction = 344
	ActionZcHoParChange SemanticAction = 345
	ActionZcHoskillinfoList SemanticAction = 346
	ActionZcHoskillinfoUpdate SemanticAction = 347
	ActionZcInventoryEnd SemanticAction = 348
	ActionZcInventoryStart SemanticAction = 349
	ActionZcInventoryTab SemanticAction = 350
	ActionZcItemDisappear SemanticAction = 351
	ActionZcItemPickupParty SemanticAction = 352
	ActionZcItemReformAck SemanticAction = 353
	ActionZcItemThrowAck SemanticAction = 354
	ActionZcLonglongparChange SemanticAction = 355
	ActionZcMakingarrowList SemanticAction = 356
	ActionZcMakingitemList SemanticAction = 357
	ActionZcMembermgrInfo SemanticAction = 358
	ActionZcMenuList SemanticAction = 359
	ActionZcMergeItemOpen SemanticAction = 360
	ActionZcMillenniumshield SemanticAction = 361
	ActionZcMonologDialog SemanticAction = 362
	ActionZcMoveItemFailed SemanticAction = 363
	ActionZcMyguildBasicInfo SemanticAction = 364
	ActionZcNotifyActorinit SemanticAction = 365
	ActionZcNotifyBargainSaleClose SemanticAction = 366
	ActionZcNotifyBargainSaleSelling SemanticAction = 367
	ActionZcNotifyBindOnEquip SemanticAction = 368
	ActionZcNotifyCartitemCountinfo SemanticAction = 369
	ActionZcNotifyChatParty SemanticAction = 370
	ActionZcNotifyEffect SemanticAction = 371
	ActionZcNotifyEffect3 SemanticAction = 372
	ActionZcNotifyGroundskill SemanticAction = 373
	ActionZcNotifyHpToGroupm SemanticAction = 374
	ActionZcNotifyMapinfo SemanticAction = 375
	ActionZcNotifyMapproperty2 SemanticAction = 376
	ActionZcNotifyMemberinfoToGroupm SemanticAction = 377
	ActionZcNotifyPositionToGroupm SemanticAction = 378
	ActionZcNotifyPositionToGuildm SemanticAction = 379
	ActionZcNotifyStoreitemCountinfo SemanticAction = 380
	ActionZcNpcBarterMarketIteminfo SemanticAction = 381
	ActionZcNpcMarketOpen SemanticAction = 382
	ActionZcNpcMarketPurchaseResult SemanticAction = 383
	ActionZcNpcShowefstUpdate SemanticAction = 384
	ActionZcOpenEditdlg SemanticAction = 385
	ActionZcOpenEditdlgstr SemanticAction = 386
	ActionZcOpenRefiningUi SemanticAction = 387
	ActionZcOpenReformUi SemanticAction = 388
	ActionZcOpenSearchStoreInfo SemanticAction = 389
	ActionZcOpenstore SemanticAction = 390
	ActionZcParChangeUser SemanticAction = 391
	ActionZcPartyConfig SemanticAction = 392
	ActionZcPcPurchaseItemlistFrommc SemanticAction = 393
	ActionZcPcPurchaseMyitemlist SemanticAction = 394
	ActionZcPcPurchaseResult SemanticAction = 395
	ActionZcPcPurchaseResultFrommc SemanticAction = 396
	ActionZcPcSellItemlist SemanticAction = 397
	ActionZcPersonalInfomation SemanticAction = 398
	ActionZcPingLive SemanticAction = 399
	ActionZcPlayNpcBgm SemanticAction = 400
	ActionZcPositionIdNameInfo SemanticAction = 401
	ActionZcPositionInfo SemanticAction = 402
	ActionZcPreviewMacroDetectorCaptcha SemanticAction = 403
	ActionZcPropertyHomun SemanticAction = 404
	ActionZcRandomCombineItemUiOpen SemanticAction = 405
	ActionZcRandomUpgradeItemUiOpen SemanticAction = 406
	ActionZcRecovery SemanticAction = 407
	ActionZcRefiningMaterialList SemanticAction = 408
	ActionZcRefuseEnterRoom SemanticAction = 409
	ActionZcRepairitemlist SemanticAction = 410
	ActionZcReputeInfo SemanticAction = 411
	ActionZcReqAckAgitInvestment SemanticAction = 412
	ActionZcReqAckMoveGuildAgit SemanticAction = 413
	ActionZcReqAnswerMacroDetector SemanticAction = 414
	ActionZcReqJoinGuild SemanticAction = 415
	ActionZcReqTakeoffEquipAck SemanticAction = 416
	ActionZcReqWearEquipAck SemanticAction = 417
	ActionZcResponseEnchant SemanticAction = 418
	ActionZcRestartAck SemanticAction = 419
	ActionZcResultMakeGuild SemanticAction = 420
	ActionZcResurrection SemanticAction = 421
	ActionZcRoleChange SemanticAction = 422
	ActionZcSayDialog SemanticAction = 423
	ActionZcSeCashshopOpen SemanticAction = 424
	ActionZcSePcBuyCashitemResult SemanticAction = 425
	ActionZcSearchStoreInfoAck SemanticAction = 426
	ActionZcSearchStoreInfoFailed SemanticAction = 427
	ActionZcSelectDealtype SemanticAction = 428
	ActionZcShortcutKeyList SemanticAction = 429
	ActionZcShowImage SemanticAction = 430
	ActionZcSkillDisappear SemanticAction = 431
	ActionZcSkillSelectRequest SemanticAction = 432
	ActionZcSkillUpdate SemanticAction = 433
	ActionZcSkillinfoUpdate2 SemanticAction = 434
	ActionZcSoulenergy SemanticAction = 435
	ActionZcSound SemanticAction = 436
	ActionZcSpecialpopup SemanticAction = 437
	ActionZcSpirits SemanticAction = 438
	ActionZcSpirits2 SemanticAction = 439
	ActionZcSpiritsAttribute SemanticAction = 440
	ActionZcSsilistItemClickAck SemanticAction = 441
	ActionZcStartCapture SemanticAction = 442
	ActionZcStateChange SemanticAction = 443
	ActionZcStatus SemanticAction = 444
	ActionZcStatusChangeAck SemanticAction = 445
	ActionZcStopmove SemanticAction = 446
	ActionZcSummonHpInit SemanticAction = 447
	ActionZcSummonHpUpdate SemanticAction = 448
	ActionZcTalkboxChatcontents SemanticAction = 449
	ActionZcTargetSpirits SemanticAction = 450
	ActionZcTrycaptureMonster SemanticAction = 451
	ActionZcUiOpen SemanticAction = 452
	ActionZcUiOpen2 SemanticAction = 453
	ActionZcUpdateCardslot SemanticAction = 454
	ActionZcUpdateGdid SemanticAction = 455
	ActionZcUseskillAck SemanticAction = 456
	ActionZcViewCamerainfo SemanticAction = 457
	ActionZcWaitDialog SemanticAction = 458

	// maxSemanticAction is the highest assigned SemanticAction value.
	// Used to size the sendRegistry array in semantic.go.
	maxSemanticAction SemanticAction = ActionZcWaitDialog
)

// String returns the constant name for known SemanticAction values
// and "SemanticAction(N)" for unknown ones.
func (a SemanticAction) String() string {
	switch a {
	case ActionUnknown:
		return "ActionUnknown"
	case ActionAcAcceptLogin:
		return "ActionAcAcceptLogin"
	case ActionAcAckHash:
		return "ActionAcAckHash"
	case ActionAcRefuseLogin:
		return "ActionAcRefuseLogin"
	case ActionAccessibleMaps:
		return "ActionAccessibleMaps"
	case ActionAccountId:
		return "ActionAccountId"
	case ActionActorAction:
		return "ActionActorAction"
	case ActionActorConnected:
		return "ActionActorConnected"
	case ActionActorDiedOrDisappeared:
		return "ActionActorDiedOrDisappeared"
	case ActionActorExists:
		return "ActionActorExists"
	case ActionActorMoved:
		return "ActionActorMoved"
	case ActionActorStatusActive:
		return "ActionActorStatusActive"
	case ActionActorStatusEffectExtended:
		return "ActionActorStatusEffectExtended"
	case ActionAddExchangeItem:
		return "ActionAddExchangeItem"
	case ActionAreaSpell:
		return "ActionAreaSpell"
	case ActionAttackRange:
		return "ActionAttackRange"
	case ActionAutoSpell:
		return "ActionAutoSpell"
	case ActionBankingCheck:
		return "ActionBankingCheck"
	case ActionBankingDeposit:
		return "ActionBankingDeposit"
	case ActionBankingOpen:
		return "ActionBankingOpen"
	case ActionBankingWithdraw:
		return "ActionBankingWithdraw"
	case ActionCaConnectInfoChanged:
		return "ActionCaConnectInfoChanged"
	case ActionCaExeHashcheck:
		return "ActionCaExeHashcheck"
	case ActionCaLogin2:
		return "ActionCaLogin2"
	case ActionCaLogin3:
		return "ActionCaLogin3"
	case ActionCaLogin4:
		return "ActionCaLogin4"
	case ActionCaLoginChannel:
		return "ActionCaLoginChannel"
	case ActionCaLoginPcbang:
		return "ActionCaLoginPcbang"
	case ActionCaReqHash:
		return "ActionCaReqHash"
	case ActionCaSsoLoginReq:
		return "ActionCaSsoLoginReq"
	case ActionCastCancelled:
		return "ActionCastCancelled"
	case ActionCatchPet:
		return "ActionCatchPet"
	case ActionChangeCart:
		return "ActionChangeCart"
	case ActionCharCreate:
		return "ActionCharCreate"
	case ActionCharCreated:
		return "ActionCharCreated"
	case ActionCharDelete:
		return "ActionCharDelete"
	case ActionCharacterBlocked:
		return "ActionCharacterBlocked"
	case ActionCharacterCreationFailed:
		return "ActionCharacterCreationFailed"
	case ActionCharacterMove:
		return "ActionCharacterMove"
	case ActionCharacterMoves:
		return "ActionCharacterMoves"
	case ActionCharacterPagesNotify:
		return "ActionCharacterPagesNotify"
	case ActionCharacterServerRefused:
		return "ActionCharacterServerRefused"
	case ActionChatMessage:
		return "ActionChatMessage"
	case ActionCloseStorage:
		return "ActionCloseStorage"
	case ActionCloseVending:
		return "ActionCloseVending"
	case ActionCtAuth:
		return "ActionCtAuth"
	case ActionCzAckAnswerMacroDetector:
		return "ActionCzAckAnswerMacroDetector"
	case ActionCzAdvancedStatusChange:
		return "ActionCzAdvancedStatusChange"
	case ActionCzAdventurerAgencyJoinReq:
		return "ActionCzAdventurerAgencyJoinReq"
	case ActionCzAdventurerAgencyJoinResult:
		return "ActionCzAdventurerAgencyJoinResult"
	case ActionCzApproximateActor:
		return "ActionCzApproximateActor"
	case ActionCzCheckname1:
		return "ActionCzCheckname1"
	case ActionCzCheckname2:
		return "ActionCzCheckname2"
	case ActionCzChooseMenuZero:
		return "ActionCzChooseMenuZero"
	case ActionCzClientVersion:
		return "ActionCzClientVersion"
	case ActionCzCloseMsgboxExtendBodyitemSize:
		return "ActionCzCloseMsgboxExtendBodyitemSize"
	case ActionCzCloseRefiningUi:
		return "ActionCzCloseRefiningUi"
	case ActionCzCloseReformUi:
		return "ActionCzCloseReformUi"
	case ActionCzCloseUiEnchant:
		return "ActionCzCloseUiEnchant"
	case ActionCzCloseUiStylingshop:
		return "ActionCzCloseUiStylingshop"
	case ActionCzCmdResetcooltime:
		return "ActionCzCmdResetcooltime"
	case ActionCzCompleteApplyMacroDetectorCaptcha:
		return "ActionCzCompleteApplyMacroDetectorCaptcha"
	case ActionCzDynamicnpcCreateRequest:
		return "ActionCzDynamicnpcCreateRequest"
	case ActionCzGetAccountLimtiedSaleList:
		return "ActionCzGetAccountLimtiedSaleList"
	case ActionCzGradeEnchantCloseUi:
		return "ActionCzGradeEnchantCloseUi"
	case ActionCzGradeEnchantRequest:
		return "ActionCzGradeEnchantRequest"
	case ActionCzGradeEnchantSelectEquipment:
		return "ActionCzGradeEnchantSelectEquipment"
	case ActionCzInventoryTab:
		return "ActionCzInventoryTab"
	case ActionCzItemReform:
		return "ActionCzItemReform"
	case ActionCzJoinGuild:
		return "ActionCzJoinGuild"
	case ActionCzMoveItemFromBodyToCart:
		return "ActionCzMoveItemFromBodyToCart"
	case ActionCzNpcBarterMarketClose:
		return "ActionCzNpcBarterMarketClose"
	case ActionCzNpcBarterMarketPurchase:
		return "ActionCzNpcBarterMarketPurchase"
	case ActionCzNpcExpandedBarterMarketClose:
		return "ActionCzNpcExpandedBarterMarketClose"
	case ActionCzNpcExpandedBarterMarketPurchase:
		return "ActionCzNpcExpandedBarterMarketPurchase"
	case ActionCzPartyConfig:
		return "ActionCzPartyConfig"
	case ActionCzPartyJoinReq:
		return "ActionCzPartyJoinReq"
	case ActionCzPartyJoinReqAck:
		return "ActionCzPartyJoinReqAck"
	case ActionCzPcPurchaseItemlistFrommc:
		return "ActionCzPcPurchaseItemlistFrommc"
	case ActionCzPcPurchaseItemlistFrommc2:
		return "ActionCzPcPurchaseItemlistFrommc2"
	case ActionCzPingLive:
		return "ActionCzPingLive"
	case ActionCzRandomCombineItemUiClose:
		return "ActionCzRandomCombineItemUiClose"
	case ActionCzRandomUpgradeItemUiClose:
		return "ActionCzRandomUpgradeItemUiClose"
	case ActionCzRefiningSelectItem:
		return "ActionCzRefiningSelectItem"
	case ActionCzReqAgitInvestment:
		return "ActionCzReqAgitInvestment"
	case ActionCzReqApplyBargainSaleItem:
		return "ActionCzReqApplyBargainSaleItem"
	case ActionCzReqApplyMacroDetector:
		return "ActionCzReqApplyMacroDetector"
	case ActionCzReqBanGuild:
		return "ActionCzReqBanGuild"
	case ActionCzReqCashBargainSaleItemInfo:
		return "ActionCzReqCashBargainSaleItemInfo"
	case ActionCzReqChangeMemberpos:
		return "ActionCzReqChangeMemberpos"
	case ActionCzReqDisorganizeGuild:
		return "ActionCzReqDisorganizeGuild"
	case ActionCzReqExtendBodyitemSize:
		return "ActionCzReqExtendBodyitemSize"
	case ActionCzReqGuildEmblemImg1:
		return "ActionCzReqGuildEmblemImg1"
	case ActionCzReqGuildEmblemImg2:
		return "ActionCzReqGuildEmblemImg2"
	case ActionCzReqGuildEmblemImg3:
		return "ActionCzReqGuildEmblemImg3"
	case ActionCzReqItemrepair2:
		return "ActionCzReqItemrepair2"
	case ActionCzReqJoinGuild:
		return "ActionCzReqJoinGuild"
	case ActionCzReqJoinGuild2:
		return "ActionCzReqJoinGuild2"
	case ActionCzReqLeaveGuild:
		return "ActionCzReqLeaveGuild"
	case ActionCzReqMakingarrow:
		return "ActionCzReqMakingarrow"
	case ActionCzReqMergeItem:
		return "ActionCzReqMergeItem"
	case ActionCzReqMoveGuildAgit:
		return "ActionCzReqMoveGuildAgit"
	case ActionCzReqOpenMsgboxExtendBodyitemSize:
		return "ActionCzReqOpenMsgboxExtendBodyitemSize"
	case ActionCzReqPlayerAidInRange:
		return "ActionCzReqPlayerAidInRange"
	case ActionCzReqPreviewMacroDetector:
		return "ActionCzReqPreviewMacroDetector"
	case ActionCzReqRandomCombineItem:
		return "ActionCzReqRandomCombineItem"
	case ActionCzReqRandomUpgradeItem:
		return "ActionCzReqRandomUpgradeItem"
	case ActionCzReqRefining:
		return "ActionCzReqRefining"
	case ActionCzReqRemaintime:
		return "ActionCzReqRemaintime"
	case ActionCzReqRemoveBargainSaleItem:
		return "ActionCzReqRemoveBargainSaleItem"
	case ActionCzReqSeCashTabCode:
		return "ActionCzReqSeCashTabCode"
	case ActionCzReqTakeoffEquipAll:
		return "ActionCzReqTakeoffEquipAll"
	case ActionCzReqUploadMacroDetector:
		return "ActionCzReqUploadMacroDetector"
	case ActionCzRequestPerfectEnchant:
		return "ActionCzRequestPerfectEnchant"
	case ActionCzRequestRandomEnchant:
		return "ActionCzRequestRandomEnchant"
	case ActionCzRequestResetEnchant:
		return "ActionCzRequestResetEnchant"
	case ActionCzRequestUpgradeEnchant:
		return "ActionCzRequestUpgradeEnchant"
	case ActionCzResetSkill:
		return "ActionCzResetSkill"
	case ActionCzRodexReturn:
		return "ActionCzRodexReturn"
	case ActionCzSeCashshopOpen1:
		return "ActionCzSeCashshopOpen1"
	case ActionCzSeCashshopOpen2:
		return "ActionCzSeCashshopOpen2"
	case ActionCzSePcBuyCashitemList:
		return "ActionCzSePcBuyCashitemList"
	case ActionCzShortcutKeyChange1:
		return "ActionCzShortcutKeyChange1"
	case ActionCzShortcutKeyChange2:
		return "ActionCzShortcutKeyChange2"
	case ActionCzShortcutkeybarRotate1:
		return "ActionCzShortcutkeybarRotate1"
	case ActionCzShortcutkeybarRotate2:
		return "ActionCzShortcutkeybarRotate2"
	case ActionCzUninstallation:
		return "ActionCzUninstallation"
	case ActionCzUploadMacroDetectorCaptcha:
		return "ActionCzUploadMacroDetectorCaptcha"
	case ActionCzUsePackageitem:
		return "ActionCzUsePackageitem"
	case ActionCzUseSkillEnd:
		return "ActionCzUseSkillEnd"
	case ActionCzUseSkillStart:
		return "ActionCzUseSkillStart"
	case ActionCzViewCamerainfo:
		return "ActionCzViewCamerainfo"
	case ActionDealAddOther:
		return "ActionDealAddOther"
	case ActionDealCancel:
		return "ActionDealCancel"
	case ActionDealFinalize:
		return "ActionDealFinalize"
	case ActionDealInitiate:
		return "ActionDealInitiate"
	case ActionDealReply:
		return "ActionDealReply"
	case ActionDealRequest:
		return "ActionDealRequest"
	case ActionDealTrade:
		return "ActionDealTrade"
	case ActionDropItem:
		return "ActionDropItem"
	case ActionEmote:
		return "ActionEmote"
	case ActionEnterWorld:
		return "ActionEnterWorld"
	case ActionEntityMove:
		return "ActionEntityMove"
	case ActionEntitySpawn:
		return "ActionEntitySpawn"
	case ActionEquipItem:
		return "ActionEquipItem"
	case ActionExp:
		return "ActionExp"
	case ActionFriendsAdd:
		return "ActionFriendsAdd"
	case ActionFriendsRemove:
		return "ActionFriendsRemove"
	case ActionFriendsReply:
		return "ActionFriendsReply"
	case ActionGameLogin:
		return "ActionGameLogin"
	case ActionGetItemFromCart:
		return "ActionGetItemFromCart"
	case ActionGuildChat:
		return "ActionGuildChat"
	case ActionHomunculusAttack:
		return "ActionHomunculusAttack"
	case ActionHomunculusInfo:
		return "ActionHomunculusInfo"
	case ActionHomunculusMenu:
		return "ActionHomunculusMenu"
	case ActionIgnoreListReq:
		return "ActionIgnoreListReq"
	case ActionInsertCard:
		return "ActionInsertCard"
	case ActionInventoryItemsEquip:
		return "ActionInventoryItemsEquip"
	case ActionInventoryItemsStackable:
		return "ActionInventoryItemsStackable"
	case ActionItemAppeared:
		return "ActionItemAppeared"
	case ActionItemExists:
		return "ActionItemExists"
	case ActionItemIdentify:
		return "ActionItemIdentify"
	case ActionItemPickup:
		return "ActionItemPickup"
	case ActionItemUse:
		return "ActionItemUse"
	case ActionLoginError:
		return "ActionLoginError"
	case ActionLook:
		return "ActionLook"
	case ActionMailReceive:
		return "ActionMailReceive"
	case ActionMapChanged:
		return "ActionMapChanged"
	case ActionMapLoaded:
		return "ActionMapLoaded"
	case ActionMapLogin:
		return "ActionMapLogin"
	case ActionMarketPurchase:
		return "ActionMarketPurchase"
	case ActionMasterLogin:
		return "ActionMasterLogin"
	case ActionMonsterHpUpdate:
		return "ActionMonsterHpUpdate"
	case ActionMonsterRangedAttack:
		return "ActionMonsterRangedAttack"
	case ActionMoveFromStorage:
		return "ActionMoveFromStorage"
	case ActionMoveTo:
		return "ActionMoveTo"
	case ActionMoveToStorage:
		return "ActionMoveToStorage"
	case ActionNpcContact:
		return "ActionNpcContact"
	case ActionNpcMarketClose:
		return "ActionNpcMarketClose"
	case ActionNpcMenuResponse:
		return "ActionNpcMenuResponse"
	case ActionNpcStoreInfo:
		return "ActionNpcStoreInfo"
	case ActionNpcTalkClose:
		return "ActionNpcTalkClose"
	case ActionNpcTalkContinue:
		return "ActionNpcTalkContinue"
	case ActionNpcTalkNumber:
		return "ActionNpcTalkNumber"
	case ActionNpcTalkText:
		return "ActionNpcTalkText"
	case ActionNpcTradeQuit:
		return "ActionNpcTradeQuit"
	case ActionPartyChangeOption:
		return "ActionPartyChangeOption"
	case ActionPartyCreate:
		return "ActionPartyCreate"
	case ActionPartyInvite:
		return "ActionPartyInvite"
	case ActionPartyKick:
		return "ActionPartyKick"
	case ActionPartyLeave:
		return "ActionPartyLeave"
	case ActionPetEggList:
		return "ActionPetEggList"
	case ActionPetInfo:
		return "ActionPetInfo"
	case ActionPetMenu:
		return "ActionPetMenu"
	case ActionPickupItem:
		return "ActionPickupItem"
	case ActionPinCodeRequest:
		return "ActionPinCodeRequest"
	case ActionPinCodeResponse:
		return "ActionPinCodeResponse"
	case ActionPrivateMessage:
		return "ActionPrivateMessage"
	case ActionPublicChat:
		return "ActionPublicChat"
	case ActionQuestDialog:
		return "ActionQuestDialog"
	case ActionQuestDialogList:
		return "ActionQuestDialogList"
	case ActionQuestUpdateMissionHunt:
		return "ActionQuestUpdateMissionHunt"
	case ActionQuitGame:
		return "ActionQuitGame"
	case ActionReceivedCharacterIDAndMap:
		return "ActionReceivedCharacterIDAndMap"
	case ActionReceivedCharacterIdAndMap:
		return "ActionReceivedCharacterIdAndMap"
	case ActionReceivedCharacters:
		return "ActionReceivedCharacters"
	case ActionReceivedCharactersInfo:
		return "ActionReceivedCharactersInfo"
	case ActionReceivedCharactersPage:
		return "ActionReceivedCharactersPage"
	case ActionReceivedMapServerInfo:
		return "ActionReceivedMapServerInfo"
	case ActionRemoveOption:
		return "ActionRemoveOption"
	case ActionRepairItem:
		return "ActionRepairItem"
	case ActionReplyPartyInvite:
		return "ActionReplyPartyInvite"
	case ActionRequestBuySellList:
		return "ActionRequestBuySellList"
	case ActionRequestCharacterPage:
		return "ActionRequestCharacterPage"
	case ActionRequestMemo:
		return "ActionRequestMemo"
	case ActionRestart:
		return "ActionRestart"
	case ActionScNotifyBan:
		return "ActionScNotifyBan"
	case ActionSelectAccessibleMap:
		return "ActionSelectAccessibleMap"
	case ActionSelectCharacter:
		return "ActionSelectCharacter"
	case ActionSelectEgg:
		return "ActionSelectEgg"
	case ActionSelfChat:
		return "ActionSelfChat"
	case ActionSellResult:
		return "ActionSellResult"
	case ActionSendEmotion:
		return "ActionSendEmotion"
	case ActionShopBuy:
		return "ActionShopBuy"
	case ActionShopSell:
		return "ActionShopSell"
	case ActionSkillAdd:
		return "ActionSkillAdd"
	case ActionSkillCast:
		return "ActionSkillCast"
	case ActionSkillDelete:
		return "ActionSkillDelete"
	case ActionSkillPostDelay:
		return "ActionSkillPostDelay"
	case ActionSkillUp:
		return "ActionSkillUp"
	case ActionSkillUpdate:
		return "ActionSkillUpdate"
	case ActionSkillUse:
		return "ActionSkillUse"
	case ActionSkillUseFailed:
		return "ActionSkillUseFailed"
	case ActionSkillUseLocation:
		return "ActionSkillUseLocation"
	case ActionSkillUsedNoDamage:
		return "ActionSkillUsedNoDamage"
	case ActionSkillsList:
		return "ActionSkillsList"
	case ActionStatUpdate:
		return "ActionStatUpdate"
	case ActionStatusUp:
		return "ActionStatusUp"
	case ActionSync:
		return "ActionSync"
	case ActionTcResult:
		return "ActionTcResult"
	case ActionTimeSyncResponse:
		return "ActionTimeSyncResponse"
	case ActionUnequipItem:
		return "ActionUnequipItem"
	case ActionUseCard:
		return "ActionUseCard"
	case ActionVenderFound:
		return "ActionVenderFound"
	case ActionVendingListReq:
		return "ActionVendingListReq"
	case ActionWeaponRefine:
		return "ActionWeaponRefine"
	case ActionWhisper:
		return "ActionWhisper"
	case ActionWhisperSent:
		return "ActionWhisperSent"
	case ActionZcAcceptEnter:
		return "ActionZcAcceptEnter"
	case ActionZcAckAddExchangeItem:
		return "ActionZcAckAddExchangeItem"
	case ActionZcAckAddItemRodex:
		return "ActionZcAckAddItemRodex"
	case ActionZcAckAdditemToCart:
		return "ActionZcAckAdditemToCart"
	case ActionZcAckApplyMacroDetector:
		return "ActionZcAckApplyMacroDetector"
	case ActionZcAckCashBargainSaleItemInfo:
		return "ActionZcAckCashBargainSaleItemInfo"
	case ActionZcAckCloseBanking:
		return "ActionZcAckCloseBanking"
	case ActionZcAckCloseRoulette:
		return "ActionZcAckCloseRoulette"
	case ActionZcAckCountBargainSaleItem:
		return "ActionZcAckCountBargainSaleItem"
	case ActionZcAckCreateChatroom:
		return "ActionZcAckCreateChatroom"
	case ActionZcAckDisorganizeGuildResult:
		return "ActionZcAckDisorganizeGuildResult"
	case ActionZcAckExtendBodyitemSize:
		return "ActionZcAckExtendBodyitemSize"
	case ActionZcAckGuildstorageLog:
		return "ActionZcAckGuildstorageLog"
	case ActionZcAckItemcomposition:
		return "ActionZcAckItemcomposition"
	case ActionZcAckItemidentify:
		return "ActionZcAckItemidentify"
	case ActionZcAckItemrefining:
		return "ActionZcAckItemrefining"
	case ActionZcAckItemrepair:
		return "ActionZcAckItemrepair"
	case ActionZcAckMakeGroup:
		return "ActionZcAckMakeGroup"
	case ActionZcAckMergeItem:
		return "ActionZcAckMergeItem"
	case ActionZcAckOpenMsgboxExtendBodyitemSize:
		return "ActionZcAckOpenMsgboxExtendBodyitemSize"
	case ActionZcAckOpenstore2:
		return "ActionZcAckOpenstore2"
	case ActionZcAckPlayerAidInRange:
		return "ActionZcAckPlayerAidInRange"
	case ActionZcAckPreviewMacroDetector:
		return "ActionZcAckPreviewMacroDetector"
	case ActionZcAckRandomCombineItem:
		return "ActionZcAckRandomCombineItem"
	case ActionZcAckRandomUpgradeItem:
		return "ActionZcAckRandomUpgradeItem"
	case ActionZcAckRanking:
		return "ActionZcAckRanking"
	case ActionZcAckReadRodex:
		return "ActionZcAckReadRodex"
	case ActionZcAckRememberWarppoint:
		return "ActionZcAckRememberWarppoint"
	case ActionZcAckReqJoinGuild:
		return "ActionZcAckReqJoinGuild"
	case ActionZcAckReqnameall:
		return "ActionZcAckReqnameall"
	case ActionZcAckReqnameallNpc:
		return "ActionZcAckReqnameallNpc"
	case ActionZcAckSeCashItemList2:
		return "ActionZcAckSeCashItemList2"
	case ActionZcAckTakeoffEquipAll:
		return "ActionZcAckTakeoffEquipAll"
	case ActionZcAckUploadMacroDetector:
		return "ActionZcAckUploadMacroDetector"
	case ActionZcActionFailure:
		return "ActionZcActionFailure"
	case ActionZcAddItemToCart:
		return "ActionZcAddItemToCart"
	case ActionZcAddItemToStore:
		return "ActionZcAddItemToStore"
	case ActionZcAdventurerAgencyJoinReq:
		return "ActionZcAdventurerAgencyJoinReq"
	case ActionZcAdventurerAgencyJoinResult:
		return "ActionZcAdventurerAgencyJoinResult"
	case ActionZcApplyMacroDetector:
		return "ActionZcApplyMacroDetector"
	case ActionZcApplyMacroDetectorCaptcha:
		return "ActionZcApplyMacroDetectorCaptcha"
	case ActionZcAutorunSkill:
		return "ActionZcAutorunSkill"
	case ActionZcAutospelllist:
		return "ActionZcAutospelllist"
	case ActionZcBattlefieldNotifyHp:
		return "ActionZcBattlefieldNotifyHp"
	case ActionZcBossInfo:
		return "ActionZcBossInfo"
	case ActionZcBroadcast:
		return "ActionZcBroadcast"
	case ActionZcBroadcast2:
		return "ActionZcBroadcast2"
	case ActionZcBroadcastItemrefiningResult:
		return "ActionZcBroadcastItemrefiningResult"
	case ActionZcBroadcastingSpecialItemObtainItem:
		return "ActionZcBroadcastingSpecialItemObtainItem"
	case ActionZcBuyingStoreEntry:
		return "ActionZcBuyingStoreEntry"
	case ActionZcCMarkerinfo:
		return "ActionZcCMarkerinfo"
	case ActionZcCancelExchangeItem:
		return "ActionZcCancelExchangeItem"
	case ActionZcCartoff:
		return "ActionZcCartoff"
	case ActionZcChangeGuild:
		return "ActionZcChangeGuild"
	case ActionZcChangeItemOption:
		return "ActionZcChangeItemOption"
	case ActionZcChangestatePet:
		return "ActionZcChangestatePet"
	case ActionZcCheckname:
		return "ActionZcCheckname"
	case ActionZcClaninfo:
		return "ActionZcClaninfo"
	case ActionZcClearDialog:
		return "ActionZcClearDialog"
	case ActionZcCloseDialog:
		return "ActionZcCloseDialog"
	case ActionZcCloseMacroDetector:
		return "ActionZcCloseMacroDetector"
	case ActionZcCloseStore:
		return "ActionZcCloseStore"
	case ActionZcCompass:
		return "ActionZcCompass"
	case ActionZcCompleteUploadMacroDetectorCaptcha:
		return "ActionZcCompleteUploadMacroDetectorCaptcha"
	case ActionZcCouplename:
		return "ActionZcCouplename"
	case ActionZcCouplestatus:
		return "ActionZcCouplestatus"
	case ActionZcDebugmsg:
		return "ActionZcDebugmsg"
	case ActionZcDeleteItemFromBody:
		return "ActionZcDeleteItemFromBody"
	case ActionZcDeleteItemFromCart:
		return "ActionZcDeleteItemFromCart"
	case ActionZcDeleteItemFromStore:
		return "ActionZcDeleteItemFromStore"
	case ActionZcDeleteMemberFromGroup:
		return "ActionZcDeleteMemberFromGroup"
	case ActionZcDeleteitemFromMcstore:
		return "ActionZcDeleteitemFromMcstore"
	case ActionZcDialogTextAlign:
		return "ActionZcDialogTextAlign"
	case ActionZcDialogWindowPos:
		return "ActionZcDialogWindowPos"
	case ActionZcDialogWindowPos2:
		return "ActionZcDialogWindowPos2"
	case ActionZcDialogWindowSize:
		return "ActionZcDialogWindowSize"
	case ActionZcDisappearBuyingStoreEntry:
		return "ActionZcDisappearBuyingStoreEntry"
	case ActionZcDynamicnpcCreateResult:
		return "ActionZcDynamicnpcCreateResult"
	case ActionZcElParChange:
		return "ActionZcElParChange"
	case ActionZcEntryQueueInit:
		return "ActionZcEntryQueueInit"
	case ActionZcEquipArrow:
		return "ActionZcEquipArrow"
	case ActionZcEquipitemDamaged:
		return "ActionZcEquipitemDamaged"
	case ActionZcEquipmentEffect:
		return "ActionZcEquipmentEffect"
	case ActionZcEquipwinMicroscope:
		return "ActionZcEquipwinMicroscope"
	case ActionZcExchangeitemUndo:
		return "ActionZcExchangeitemUndo"
	case ActionZcExecExchangeItem:
		return "ActionZcExecExchangeItem"
	case ActionZcExtendBodyitemSize:
		return "ActionZcExtendBodyitemSize"
	case ActionZcFriendsList:
		return "ActionZcFriendsList"
	case ActionZcGoldpccafePoint:
		return "ActionZcGoldpccafePoint"
	case ActionZcGradeEnchantAck:
		return "ActionZcGradeEnchantAck"
	case ActionZcGradeEnchantBroadcastResult:
		return "ActionZcGradeEnchantBroadcastResult"
	case ActionZcGradeEnchantMaterialList:
		return "ActionZcGradeEnchantMaterialList"
	case ActionZcGuildAgitInfo:
		return "ActionZcGuildAgitInfo"
	case ActionZcGuildEmblemImg:
		return "ActionZcGuildEmblemImg"
	case ActionZcGuildInfo:
		return "ActionZcGuildInfo"
	case ActionZcGuildNotice:
		return "ActionZcGuildNotice"
	case ActionZcGuildSkillinfo:
		return "ActionZcGuildSkillinfo"
	case ActionZcHoParChange:
		return "ActionZcHoParChange"
	case ActionZcHoskillinfoList:
		return "ActionZcHoskillinfoList"
	case ActionZcHoskillinfoUpdate:
		return "ActionZcHoskillinfoUpdate"
	case ActionZcInventoryEnd:
		return "ActionZcInventoryEnd"
	case ActionZcInventoryStart:
		return "ActionZcInventoryStart"
	case ActionZcInventoryTab:
		return "ActionZcInventoryTab"
	case ActionZcItemDisappear:
		return "ActionZcItemDisappear"
	case ActionZcItemPickupParty:
		return "ActionZcItemPickupParty"
	case ActionZcItemReformAck:
		return "ActionZcItemReformAck"
	case ActionZcItemThrowAck:
		return "ActionZcItemThrowAck"
	case ActionZcLonglongparChange:
		return "ActionZcLonglongparChange"
	case ActionZcMakingarrowList:
		return "ActionZcMakingarrowList"
	case ActionZcMakingitemList:
		return "ActionZcMakingitemList"
	case ActionZcMembermgrInfo:
		return "ActionZcMembermgrInfo"
	case ActionZcMenuList:
		return "ActionZcMenuList"
	case ActionZcMergeItemOpen:
		return "ActionZcMergeItemOpen"
	case ActionZcMillenniumshield:
		return "ActionZcMillenniumshield"
	case ActionZcMonologDialog:
		return "ActionZcMonologDialog"
	case ActionZcMoveItemFailed:
		return "ActionZcMoveItemFailed"
	case ActionZcMyguildBasicInfo:
		return "ActionZcMyguildBasicInfo"
	case ActionZcNotifyActorinit:
		return "ActionZcNotifyActorinit"
	case ActionZcNotifyBargainSaleClose:
		return "ActionZcNotifyBargainSaleClose"
	case ActionZcNotifyBargainSaleSelling:
		return "ActionZcNotifyBargainSaleSelling"
	case ActionZcNotifyBindOnEquip:
		return "ActionZcNotifyBindOnEquip"
	case ActionZcNotifyCartitemCountinfo:
		return "ActionZcNotifyCartitemCountinfo"
	case ActionZcNotifyChatParty:
		return "ActionZcNotifyChatParty"
	case ActionZcNotifyEffect:
		return "ActionZcNotifyEffect"
	case ActionZcNotifyEffect3:
		return "ActionZcNotifyEffect3"
	case ActionZcNotifyGroundskill:
		return "ActionZcNotifyGroundskill"
	case ActionZcNotifyHpToGroupm:
		return "ActionZcNotifyHpToGroupm"
	case ActionZcNotifyMapinfo:
		return "ActionZcNotifyMapinfo"
	case ActionZcNotifyMapproperty2:
		return "ActionZcNotifyMapproperty2"
	case ActionZcNotifyMemberinfoToGroupm:
		return "ActionZcNotifyMemberinfoToGroupm"
	case ActionZcNotifyPositionToGroupm:
		return "ActionZcNotifyPositionToGroupm"
	case ActionZcNotifyPositionToGuildm:
		return "ActionZcNotifyPositionToGuildm"
	case ActionZcNotifyStoreitemCountinfo:
		return "ActionZcNotifyStoreitemCountinfo"
	case ActionZcNpcBarterMarketIteminfo:
		return "ActionZcNpcBarterMarketIteminfo"
	case ActionZcNpcMarketOpen:
		return "ActionZcNpcMarketOpen"
	case ActionZcNpcMarketPurchaseResult:
		return "ActionZcNpcMarketPurchaseResult"
	case ActionZcNpcShowefstUpdate:
		return "ActionZcNpcShowefstUpdate"
	case ActionZcOpenEditdlg:
		return "ActionZcOpenEditdlg"
	case ActionZcOpenEditdlgstr:
		return "ActionZcOpenEditdlgstr"
	case ActionZcOpenRefiningUi:
		return "ActionZcOpenRefiningUi"
	case ActionZcOpenReformUi:
		return "ActionZcOpenReformUi"
	case ActionZcOpenSearchStoreInfo:
		return "ActionZcOpenSearchStoreInfo"
	case ActionZcOpenstore:
		return "ActionZcOpenstore"
	case ActionZcParChangeUser:
		return "ActionZcParChangeUser"
	case ActionZcPartyConfig:
		return "ActionZcPartyConfig"
	case ActionZcPcPurchaseItemlistFrommc:
		return "ActionZcPcPurchaseItemlistFrommc"
	case ActionZcPcPurchaseMyitemlist:
		return "ActionZcPcPurchaseMyitemlist"
	case ActionZcPcPurchaseResult:
		return "ActionZcPcPurchaseResult"
	case ActionZcPcPurchaseResultFrommc:
		return "ActionZcPcPurchaseResultFrommc"
	case ActionZcPcSellItemlist:
		return "ActionZcPcSellItemlist"
	case ActionZcPersonalInfomation:
		return "ActionZcPersonalInfomation"
	case ActionZcPingLive:
		return "ActionZcPingLive"
	case ActionZcPlayNpcBgm:
		return "ActionZcPlayNpcBgm"
	case ActionZcPositionIdNameInfo:
		return "ActionZcPositionIdNameInfo"
	case ActionZcPositionInfo:
		return "ActionZcPositionInfo"
	case ActionZcPreviewMacroDetectorCaptcha:
		return "ActionZcPreviewMacroDetectorCaptcha"
	case ActionZcPropertyHomun:
		return "ActionZcPropertyHomun"
	case ActionZcRandomCombineItemUiOpen:
		return "ActionZcRandomCombineItemUiOpen"
	case ActionZcRandomUpgradeItemUiOpen:
		return "ActionZcRandomUpgradeItemUiOpen"
	case ActionZcRecovery:
		return "ActionZcRecovery"
	case ActionZcRefiningMaterialList:
		return "ActionZcRefiningMaterialList"
	case ActionZcRefuseEnterRoom:
		return "ActionZcRefuseEnterRoom"
	case ActionZcRepairitemlist:
		return "ActionZcRepairitemlist"
	case ActionZcReputeInfo:
		return "ActionZcReputeInfo"
	case ActionZcReqAckAgitInvestment:
		return "ActionZcReqAckAgitInvestment"
	case ActionZcReqAckMoveGuildAgit:
		return "ActionZcReqAckMoveGuildAgit"
	case ActionZcReqAnswerMacroDetector:
		return "ActionZcReqAnswerMacroDetector"
	case ActionZcReqJoinGuild:
		return "ActionZcReqJoinGuild"
	case ActionZcReqTakeoffEquipAck:
		return "ActionZcReqTakeoffEquipAck"
	case ActionZcReqWearEquipAck:
		return "ActionZcReqWearEquipAck"
	case ActionZcResponseEnchant:
		return "ActionZcResponseEnchant"
	case ActionZcRestartAck:
		return "ActionZcRestartAck"
	case ActionZcResultMakeGuild:
		return "ActionZcResultMakeGuild"
	case ActionZcResurrection:
		return "ActionZcResurrection"
	case ActionZcRoleChange:
		return "ActionZcRoleChange"
	case ActionZcSayDialog:
		return "ActionZcSayDialog"
	case ActionZcSeCashshopOpen:
		return "ActionZcSeCashshopOpen"
	case ActionZcSePcBuyCashitemResult:
		return "ActionZcSePcBuyCashitemResult"
	case ActionZcSearchStoreInfoAck:
		return "ActionZcSearchStoreInfoAck"
	case ActionZcSearchStoreInfoFailed:
		return "ActionZcSearchStoreInfoFailed"
	case ActionZcSelectDealtype:
		return "ActionZcSelectDealtype"
	case ActionZcShortcutKeyList:
		return "ActionZcShortcutKeyList"
	case ActionZcShowImage:
		return "ActionZcShowImage"
	case ActionZcSkillDisappear:
		return "ActionZcSkillDisappear"
	case ActionZcSkillSelectRequest:
		return "ActionZcSkillSelectRequest"
	case ActionZcSkillUpdate:
		return "ActionZcSkillUpdate"
	case ActionZcSkillinfoUpdate2:
		return "ActionZcSkillinfoUpdate2"
	case ActionZcSoulenergy:
		return "ActionZcSoulenergy"
	case ActionZcSound:
		return "ActionZcSound"
	case ActionZcSpecialpopup:
		return "ActionZcSpecialpopup"
	case ActionZcSpirits:
		return "ActionZcSpirits"
	case ActionZcSpirits2:
		return "ActionZcSpirits2"
	case ActionZcSpiritsAttribute:
		return "ActionZcSpiritsAttribute"
	case ActionZcSsilistItemClickAck:
		return "ActionZcSsilistItemClickAck"
	case ActionZcStartCapture:
		return "ActionZcStartCapture"
	case ActionZcStateChange:
		return "ActionZcStateChange"
	case ActionZcStatus:
		return "ActionZcStatus"
	case ActionZcStatusChangeAck:
		return "ActionZcStatusChangeAck"
	case ActionZcStopmove:
		return "ActionZcStopmove"
	case ActionZcSummonHpInit:
		return "ActionZcSummonHpInit"
	case ActionZcSummonHpUpdate:
		return "ActionZcSummonHpUpdate"
	case ActionZcTalkboxChatcontents:
		return "ActionZcTalkboxChatcontents"
	case ActionZcTargetSpirits:
		return "ActionZcTargetSpirits"
	case ActionZcTrycaptureMonster:
		return "ActionZcTrycaptureMonster"
	case ActionZcUiOpen:
		return "ActionZcUiOpen"
	case ActionZcUiOpen2:
		return "ActionZcUiOpen2"
	case ActionZcUpdateCardslot:
		return "ActionZcUpdateCardslot"
	case ActionZcUpdateGdid:
		return "ActionZcUpdateGdid"
	case ActionZcUseskillAck:
		return "ActionZcUseskillAck"
	case ActionZcViewCamerainfo:
		return "ActionZcViewCamerainfo"
	case ActionZcWaitDialog:
		return "ActionZcWaitDialog"
	}
	return fmt.Sprintf("SemanticAction(%d)", uint16(a))
}
