// Code generated by internal/codegen. DO NOT EDIT.

package session

import "fmt"

// SemanticAction identifies a protocol-level semantic action.
// Each constant corresponds to one entry in semantics/mappings.yaml.
type SemanticAction uint16

const (
	ActionUnknown SemanticAction = 0
	ActionAcAcceptLogin SemanticAction = 1
	ActionAcAckHash SemanticAction = 2
	ActionAcRefuseLogin SemanticAction = 3
	ActionAccessibleMaps SemanticAction = 4
	ActionAccountId SemanticAction = 5
	ActionAccountServerInfo SemanticAction = 6
	ActionActorAction SemanticAction = 7
	ActionActorConnected SemanticAction = 8
	ActionActorDiedOrDisappeared SemanticAction = 9
	ActionActorExists SemanticAction = 10
	ActionActorMoved SemanticAction = 11
	ActionActorStatusActive SemanticAction = 12
	ActionActorStatusEffectExtended SemanticAction = 13
	ActionAddExchangeItem SemanticAction = 14
	ActionAreaSpell SemanticAction = 15
	ActionAttackRange SemanticAction = 16
	ActionAutoSpell SemanticAction = 17
	ActionBankingCheck SemanticAction = 18
	ActionBankingDeposit SemanticAction = 19
	ActionBankingOpen SemanticAction = 20
	ActionBankingWithdraw SemanticAction = 21
	ActionCaConnectInfoChanged SemanticAction = 22
	ActionCaExeHashcheck SemanticAction = 23
	ActionCaLogin2 SemanticAction = 24
	ActionCaLogin3 SemanticAction = 25
	ActionCaLogin4 SemanticAction = 26
	ActionCaLoginChannel SemanticAction = 27
	ActionCaLoginPcbang SemanticAction = 28
	ActionCaReqHash SemanticAction = 29
	ActionCaSsoLoginReq SemanticAction = 30
	ActionCastCancelled SemanticAction = 31
	ActionCatchPet SemanticAction = 32
	ActionChangeCart SemanticAction = 33
	ActionCharCreate SemanticAction = 34
	ActionCharDelete SemanticAction = 35
	ActionCharLogin SemanticAction = 36
	ActionCharacterBlocked SemanticAction = 37
	ActionCharacterCreationFailed SemanticAction = 38
	ActionCharacterMove SemanticAction = 39
	ActionCharacterMoves SemanticAction = 40
	ActionCharacterPagesNotify SemanticAction = 41
	ActionCharacterServerRefused SemanticAction = 42
	ActionChatMessage SemanticAction = 43
	ActionCloseStorage SemanticAction = 44
	ActionCloseVending SemanticAction = 45
	ActionCtAuth SemanticAction = 46
	ActionCzAckAnswerMacroDetector SemanticAction = 47
	ActionCzAdvancedStatusChange SemanticAction = 48
	ActionCzAdventurerAgencyJoinReq SemanticAction = 49
	ActionCzAdventurerAgencyJoinResult SemanticAction = 50
	ActionCzApproximateActor SemanticAction = 51
	ActionCzCheckname1 SemanticAction = 52
	ActionCzCheckname2 SemanticAction = 53
	ActionCzChooseMenuZero SemanticAction = 54
	ActionCzClientVersion SemanticAction = 55
	ActionCzCloseMsgboxExtendBodyitemSize SemanticAction = 56
	ActionCzCloseRefiningUi SemanticAction = 57
	ActionCzCloseReformUi SemanticAction = 58
	ActionCzCloseUiEnchant SemanticAction = 59
	ActionCzCloseUiStylingshop SemanticAction = 60
	ActionCzCmdResetcooltime SemanticAction = 61
	ActionCzCompleteApplyMacroDetectorCaptcha SemanticAction = 62
	ActionCzContactnpc SemanticAction = 63
	ActionCzDynamicnpcCreateRequest SemanticAction = 64
	ActionCzGetAccountLimtiedSaleList SemanticAction = 65
	ActionCzGradeEnchantCloseUi SemanticAction = 66
	ActionCzGradeEnchantRequest SemanticAction = 67
	ActionCzGradeEnchantSelectEquipment SemanticAction = 68
	ActionCzInventoryTab SemanticAction = 69
	ActionCzItemReform SemanticAction = 70
	ActionCzJoinGroup SemanticAction = 71
	ActionCzJoinGuild SemanticAction = 72
	ActionCzMoveItemFromBodyToCart SemanticAction = 73
	ActionCzNpcBarterMarketClose SemanticAction = 74
	ActionCzNpcBarterMarketPurchase SemanticAction = 75
	ActionCzNpcExpandedBarterMarketClose SemanticAction = 76
	ActionCzNpcExpandedBarterMarketPurchase SemanticAction = 77
	ActionCzNpcMarketPurchase SemanticAction = 78
	ActionCzPartyConfig SemanticAction = 79
	ActionCzPartyJoinReq SemanticAction = 80
	ActionCzPartyJoinReqAck SemanticAction = 81
	ActionCzPcPurchaseItemlistFrommc SemanticAction = 82
	ActionCzPcPurchaseItemlistFrommc2 SemanticAction = 83
	ActionCzPingLive SemanticAction = 84
	ActionCzRandomCombineItemUiClose SemanticAction = 85
	ActionCzRandomUpgradeItemUiClose SemanticAction = 86
	ActionCzRefiningSelectItem SemanticAction = 87
	ActionCzReqAgitInvestment SemanticAction = 88
	ActionCzReqApplyBargainSaleItem SemanticAction = 89
	ActionCzReqApplyMacroDetector SemanticAction = 90
	ActionCzReqBanGuild SemanticAction = 91
	ActionCzReqCashBargainSaleItemInfo SemanticAction = 92
	ActionCzReqChangeMemberpos SemanticAction = 93
	ActionCzReqDisorganizeGuild SemanticAction = 94
	ActionCzReqExtendBodyitemSize SemanticAction = 95
	ActionCzReqGuildEmblemImg1 SemanticAction = 96
	ActionCzReqGuildEmblemImg2 SemanticAction = 97
	ActionCzReqGuildEmblemImg3 SemanticAction = 98
	ActionCzReqItemrepair1 SemanticAction = 99
	ActionCzReqItemrepair2 SemanticAction = 100
	ActionCzReqJoinGuild SemanticAction = 101
	ActionCzReqJoinGuild2 SemanticAction = 102
	ActionCzReqLeaveGuild SemanticAction = 103
	ActionCzReqMakingarrow SemanticAction = 104
	ActionCzReqMergeItem SemanticAction = 105
	ActionCzReqMoveGuildAgit SemanticAction = 106
	ActionCzReqOpenMsgboxExtendBodyitemSize SemanticAction = 107
	ActionCzReqPlayerAidInRange SemanticAction = 108
	ActionCzReqPreviewMacroDetector SemanticAction = 109
	ActionCzReqRandomCombineItem SemanticAction = 110
	ActionCzReqRandomUpgradeItem SemanticAction = 111
	ActionCzReqRefining SemanticAction = 112
	ActionCzReqRemaintime SemanticAction = 113
	ActionCzReqRemoveBargainSaleItem SemanticAction = 114
	ActionCzReqSeCashTabCode SemanticAction = 115
	ActionCzReqTakeoffEquipAll SemanticAction = 116
	ActionCzReqUploadMacroDetector SemanticAction = 117
	ActionCzRequestPerfectEnchant SemanticAction = 118
	ActionCzRequestRandomEnchant SemanticAction = 119
	ActionCzRequestResetEnchant SemanticAction = 120
	ActionCzRequestUpgradeEnchant SemanticAction = 121
	ActionCzResetSkill SemanticAction = 122
	ActionCzRodexReturn SemanticAction = 123
	ActionCzSeCashshopOpen1 SemanticAction = 124
	ActionCzSeCashshopOpen2 SemanticAction = 125
	ActionCzSePcBuyCashitemList SemanticAction = 126
	ActionCzShortcutKeyChange1 SemanticAction = 127
	ActionCzShortcutKeyChange2 SemanticAction = 128
	ActionCzShortcutkeybarRotate1 SemanticAction = 129
	ActionCzShortcutkeybarRotate2 SemanticAction = 130
	ActionCzUninstallation SemanticAction = 131
	ActionCzUploadMacroDetectorCaptcha SemanticAction = 132
	ActionCzUsePackageitem SemanticAction = 133
	ActionCzUseSkillEnd SemanticAction = 134
	ActionCzUseSkillStart SemanticAction = 135
	ActionCzViewCamerainfo SemanticAction = 136
	ActionDealAddOther SemanticAction = 137
	ActionDealCancel SemanticAction = 138
	ActionDealFinalize SemanticAction = 139
	ActionDealInitiate SemanticAction = 140
	ActionDealReply SemanticAction = 141
	ActionDealRequest SemanticAction = 142
	ActionDealTrade SemanticAction = 143
	ActionDropItem SemanticAction = 144
	ActionEmote SemanticAction = 145
	ActionEnterWorld SemanticAction = 146
	ActionEntityMove SemanticAction = 147
	ActionEntitySpawn SemanticAction = 148
	ActionEquipItem SemanticAction = 149
	ActionFriendsAdd SemanticAction = 150
	ActionFriendsRemove SemanticAction = 151
	ActionFriendsReply SemanticAction = 152
	ActionGameLogin SemanticAction = 153
	ActionGetItemFromCart SemanticAction = 154
	ActionHomunculusAttack SemanticAction = 155
	ActionHomunculusInfo SemanticAction = 156
	ActionHomunculusMenu SemanticAction = 157
	ActionIgnoreListReq SemanticAction = 158
	ActionInsertCard SemanticAction = 159
	ActionInventoryItemAdded SemanticAction = 160
	ActionItemAppeared SemanticAction = 161
	ActionItemDisappeared SemanticAction = 162
	ActionItemExists SemanticAction = 163
	ActionItemIdentify SemanticAction = 164
	ActionItemPickup SemanticAction = 165
	ActionItemUse SemanticAction = 166
	ActionLoginError SemanticAction = 167
	ActionLook SemanticAction = 168
	ActionMapChanged SemanticAction = 169
	ActionMapLoaded SemanticAction = 170
	ActionMapLogin SemanticAction = 171
	ActionMarketPurchase SemanticAction = 172
	ActionMasterLogin SemanticAction = 173
	ActionMonsterHpUpdate SemanticAction = 174
	ActionMonsterRangedAttack SemanticAction = 175
	ActionMoveFromStorage SemanticAction = 176
	ActionMoveTo SemanticAction = 177
	ActionMoveToStorage SemanticAction = 178
	ActionNpcContact SemanticAction = 179
	ActionNpcMarketClose SemanticAction = 180
	ActionNpcMenuResponse SemanticAction = 181
	ActionNpcStoreInfo SemanticAction = 182
	ActionNpcTalkClose SemanticAction = 183
	ActionNpcTalkContinue SemanticAction = 184
	ActionNpcTalkNumber SemanticAction = 185
	ActionNpcTalkText SemanticAction = 186
	ActionNpcTradeQuit SemanticAction = 187
	ActionPartyChangeOption SemanticAction = 188
	ActionPartyCreate SemanticAction = 189
	ActionPartyInvite SemanticAction = 190
	ActionPartyKick SemanticAction = 191
	ActionPartyLeave SemanticAction = 192
	ActionPetEggList SemanticAction = 193
	ActionPetInfo SemanticAction = 194
	ActionPetMenu SemanticAction = 195
	ActionPickupItem SemanticAction = 196
	ActionPinCodeRequest SemanticAction = 197
	ActionPinCodeResponse SemanticAction = 198
	ActionPrivateMessage SemanticAction = 199
	ActionPublicChat SemanticAction = 200
	ActionQuestDialog SemanticAction = 201
	ActionQuestDialogList SemanticAction = 202
	ActionQuestUpdateMissionHunt SemanticAction = 203
	ActionQuitGame SemanticAction = 204
	ActionReceivedCharacterIDAndMap SemanticAction = 205
	ActionReceivedCharacterIdAndMap SemanticAction = 206
	ActionReceivedCharacters SemanticAction = 207
	ActionReceivedCharactersInfo SemanticAction = 208
	ActionReceivedCharactersPage SemanticAction = 209
	ActionReceivedMapServerInfo SemanticAction = 210
	ActionRemoveOption SemanticAction = 211
	ActionRemovePartyMember SemanticAction = 212
	ActionRepairItem SemanticAction = 213
	ActionReplyPartyInvite SemanticAction = 214
	ActionRequestAction SemanticAction = 215
	ActionRequestCharacterPage SemanticAction = 216
	ActionRequestCharlist SemanticAction = 217
	ActionRequestMemo SemanticAction = 218
	ActionRestart SemanticAction = 219
	ActionScNotifyBan SemanticAction = 220
	ActionSelectAccessibleMap SemanticAction = 221
	ActionSelectArrow SemanticAction = 222
	ActionSelectCharacter SemanticAction = 223
	ActionSelectEgg SemanticAction = 224
	ActionSelfChat SemanticAction = 225
	ActionSendEmotion SemanticAction = 226
	ActionShopBuy SemanticAction = 227
	ActionShopSell SemanticAction = 228
	ActionSkillAdd SemanticAction = 229
	ActionSkillCast SemanticAction = 230
	ActionSkillDelete SemanticAction = 231
	ActionSkillPostDelay SemanticAction = 232
	ActionSkillUp SemanticAction = 233
	ActionSkillUpdate SemanticAction = 234
	ActionSkillUse SemanticAction = 235
	ActionSkillUseFailed SemanticAction = 236
	ActionSkillUseLocation SemanticAction = 237
	ActionSkillUsedNoDamage SemanticAction = 238
	ActionSkillsList SemanticAction = 239
	ActionStatUpdate SemanticAction = 240
	ActionStatusUp SemanticAction = 241
	ActionSync SemanticAction = 242
	ActionSystemChat SemanticAction = 243
	ActionTcResult SemanticAction = 244
	ActionTimeSyncResponse SemanticAction = 245
	ActionUnequipItem SemanticAction = 246
	ActionUseCard SemanticAction = 247
	ActionVenderFound SemanticAction = 248
	ActionVendingListReq SemanticAction = 249
	ActionWeaponRefine SemanticAction = 250
	ActionWhisperSent SemanticAction = 251
	ActionZcAcceptEnter SemanticAction = 252
	ActionZcAckAddExchangeItem SemanticAction = 253
	ActionZcAckAddItemRodex SemanticAction = 254
	ActionZcAckAdditemToCart SemanticAction = 255
	ActionZcAckApplyMacroDetector SemanticAction = 256
	ActionZcAckCashBargainSaleItemInfo SemanticAction = 257
	ActionZcAckCloseBanking SemanticAction = 258
	ActionZcAckCloseRoulette SemanticAction = 259
	ActionZcAckCountBargainSaleItem SemanticAction = 260
	ActionZcAckCreateChatroom SemanticAction = 261
	ActionZcAckDisorganizeGuildResult SemanticAction = 262
	ActionZcAckExtendBodyitemSize SemanticAction = 263
	ActionZcAckGuildstorageLog SemanticAction = 264
	ActionZcAckItemcomposition SemanticAction = 265
	ActionZcAckItemidentify SemanticAction = 266
	ActionZcAckItemrefining SemanticAction = 267
	ActionZcAckItemrepair SemanticAction = 268
	ActionZcAckMakeGroup SemanticAction = 269
	ActionZcAckMergeItem SemanticAction = 270
	ActionZcAckOpenMsgboxExtendBodyitemSize SemanticAction = 271
	ActionZcAckOpenstore2 SemanticAction = 272
	ActionZcAckPlayerAidInRange SemanticAction = 273
	ActionZcAckPreviewMacroDetector SemanticAction = 274
	ActionZcAckRandomCombineItem SemanticAction = 275
	ActionZcAckRandomUpgradeItem SemanticAction = 276
	ActionZcAckRanking SemanticAction = 277
	ActionZcAckReadRodex SemanticAction = 278
	ActionZcAckRememberWarppoint SemanticAction = 279
	ActionZcAckReqJoinGuild SemanticAction = 280
	ActionZcAckReqnameall SemanticAction = 281
	ActionZcAckReqnameallNpc SemanticAction = 282
	ActionZcAckSeCashItemList2 SemanticAction = 283
	ActionZcAckTakeoffEquipAll SemanticAction = 284
	ActionZcAckUploadMacroDetector SemanticAction = 285
	ActionZcActionFailure SemanticAction = 286
	ActionZcAddItemToCart SemanticAction = 287
	ActionZcAddItemToStore SemanticAction = 288
	ActionZcAdventurerAgencyJoinReq SemanticAction = 289
	ActionZcAdventurerAgencyJoinResult SemanticAction = 290
	ActionZcApplyMacroDetector SemanticAction = 291
	ActionZcApplyMacroDetectorCaptcha SemanticAction = 292
	ActionZcAutorunSkill SemanticAction = 293
	ActionZcAutospelllist SemanticAction = 294
	ActionZcBattlefieldNotifyHp SemanticAction = 295
	ActionZcBossInfo SemanticAction = 296
	ActionZcBroadcast SemanticAction = 297
	ActionZcBroadcast2 SemanticAction = 298
	ActionZcBroadcastItemrefiningResult SemanticAction = 299
	ActionZcBroadcastingSpecialItemObtainItem SemanticAction = 300
	ActionZcBuyingStoreEntry SemanticAction = 301
	ActionZcCMarkerinfo SemanticAction = 302
	ActionZcCancelExchangeItem SemanticAction = 303
	ActionZcCartoff SemanticAction = 304
	ActionZcChangeGuild SemanticAction = 305
	ActionZcChangeItemOption SemanticAction = 306
	ActionZcChangestatePet SemanticAction = 307
	ActionZcCheckname SemanticAction = 308
	ActionZcClaninfo SemanticAction = 309
	ActionZcClearDialog SemanticAction = 310
	ActionZcCloseDialog SemanticAction = 311
	ActionZcCloseMacroDetector SemanticAction = 312
	ActionZcCloseStore SemanticAction = 313
	ActionZcCompass SemanticAction = 314
	ActionZcCompleteUploadMacroDetectorCaptcha SemanticAction = 315
	ActionZcCouplename SemanticAction = 316
	ActionZcCouplestatus SemanticAction = 317
	ActionZcDebugmsg SemanticAction = 318
	ActionZcDeleteItemFromBody SemanticAction = 319
	ActionZcDeleteItemFromCart SemanticAction = 320
	ActionZcDeleteItemFromStore SemanticAction = 321
	ActionZcDeleteMemberFromGroup SemanticAction = 322
	ActionZcDeleteitemFromMcstore SemanticAction = 323
	ActionZcDialogTextAlign SemanticAction = 324
	ActionZcDialogWindowPos SemanticAction = 325
	ActionZcDialogWindowPos2 SemanticAction = 326
	ActionZcDialogWindowSize SemanticAction = 327
	ActionZcDisappearBuyingStoreEntry SemanticAction = 328
	ActionZcDynamicnpcCreateResult SemanticAction = 329
	ActionZcEntryQueueInit SemanticAction = 330
	ActionZcEquipArrow SemanticAction = 331
	ActionZcEquipitemDamaged SemanticAction = 332
	ActionZcEquipmentEffect SemanticAction = 333
	ActionZcEquipwinMicroscope SemanticAction = 334
	ActionZcExchangeitemUndo SemanticAction = 335
	ActionZcExecExchangeItem SemanticAction = 336
	ActionZcExtendBodyitemSize SemanticAction = 337
	ActionZcFriendsList SemanticAction = 338
	ActionZcGoldpccafePoint SemanticAction = 339
	ActionZcGradeEnchantAck SemanticAction = 340
	ActionZcGradeEnchantBroadcastResult SemanticAction = 341
	ActionZcGradeEnchantMaterialList SemanticAction = 342
	ActionZcGuildAgitInfo SemanticAction = 343
	ActionZcGuildEmblemImg SemanticAction = 344
	ActionZcGuildInfo SemanticAction = 345
	ActionZcGuildNotice SemanticAction = 346
	ActionZcGuildSkillinfo SemanticAction = 347
	ActionZcHoskillinfoList SemanticAction = 348
	ActionZcHoskillinfoUpdate SemanticAction = 349
	ActionZcInventoryEnd SemanticAction = 350
	ActionZcInventoryStart SemanticAction = 351
	ActionZcInventoryTab SemanticAction = 352
	ActionZcItemDisappear SemanticAction = 353
	ActionZcItemPickupParty SemanticAction = 354
	ActionZcItemReformAck SemanticAction = 355
	ActionZcItemThrowAck SemanticAction = 356
	ActionZcLonglongparChange SemanticAction = 357
	ActionZcMakingarrowList SemanticAction = 358
	ActionZcMakingitemList SemanticAction = 359
	ActionZcMembermgrInfo SemanticAction = 360
	ActionZcMenuList SemanticAction = 361
	ActionZcMergeItemOpen SemanticAction = 362
	ActionZcMillenniumshield SemanticAction = 363
	ActionZcMonologDialog SemanticAction = 364
	ActionZcMoveItemFailed SemanticAction = 365
	ActionZcMyguildBasicInfo SemanticAction = 366
	ActionZcNotifyActorinit SemanticAction = 367
	ActionZcNotifyBargainSaleClose SemanticAction = 368
	ActionZcNotifyBargainSaleSelling SemanticAction = 369
	ActionZcNotifyBindOnEquip SemanticAction = 370
	ActionZcNotifyCartitemCountinfo SemanticAction = 371
	ActionZcNotifyChatParty SemanticAction = 372
	ActionZcNotifyEffect SemanticAction = 373
	ActionZcNotifyEffect3 SemanticAction = 374
	ActionZcNotifyGroundskill SemanticAction = 375
	ActionZcNotifyHpToGroupm SemanticAction = 376
	ActionZcNotifyMapinfo SemanticAction = 377
	ActionZcNotifyMapproperty2 SemanticAction = 378
	ActionZcNotifyMemberinfoToGroupm SemanticAction = 379
	ActionZcNotifyPositionToGroupm SemanticAction = 380
	ActionZcNotifyPositionToGuildm SemanticAction = 381
	ActionZcNotifyStoreitemCountinfo SemanticAction = 382
	ActionZcNpcBarterMarketIteminfo SemanticAction = 383
	ActionZcNpcMarketOpen SemanticAction = 384
	ActionZcNpcMarketPurchaseResult SemanticAction = 385
	ActionZcNpcShowefstUpdate SemanticAction = 386
	ActionZcNpcackServermove SemanticAction = 387
	ActionZcOpenEditdlg SemanticAction = 388
	ActionZcOpenEditdlgstr SemanticAction = 389
	ActionZcOpenRefiningUi SemanticAction = 390
	ActionZcOpenReformUi SemanticAction = 391
	ActionZcOpenSearchStoreInfo SemanticAction = 392
	ActionZcOpenstore SemanticAction = 393
	ActionZcParChangeUser SemanticAction = 394
	ActionZcPartyConfig SemanticAction = 395
	ActionZcPcPurchaseItemlistFrommc SemanticAction = 396
	ActionZcPcPurchaseMyitemlist SemanticAction = 397
	ActionZcPcPurchaseResult SemanticAction = 398
	ActionZcPcPurchaseResultFrommc SemanticAction = 399
	ActionZcPcSellItemlist SemanticAction = 400
	ActionZcPersonalInfomation SemanticAction = 401
	ActionZcPingLive SemanticAction = 402
	ActionZcPlayNpcBgm SemanticAction = 403
	ActionZcPositionIdNameInfo SemanticAction = 404
	ActionZcPositionInfo SemanticAction = 405
	ActionZcPreviewMacroDetectorCaptcha SemanticAction = 406
	ActionZcPropertyHomun SemanticAction = 407
	ActionZcRandomCombineItemUiOpen SemanticAction = 408
	ActionZcRandomUpgradeItemUiOpen SemanticAction = 409
	ActionZcRecovery SemanticAction = 410
	ActionZcRefiningMaterialList SemanticAction = 411
	ActionZcRefuseEnterRoom SemanticAction = 412
	ActionZcRepairitemlist SemanticAction = 413
	ActionZcReputeInfo SemanticAction = 414
	ActionZcReqAckAgitInvestment SemanticAction = 415
	ActionZcReqAckMoveGuildAgit SemanticAction = 416
	ActionZcReqAnswerMacroDetector SemanticAction = 417
	ActionZcReqJoinGuild SemanticAction = 418
	ActionZcReqWearEquipAck SemanticAction = 419
	ActionZcResponseEnchant SemanticAction = 420
	ActionZcRestartAck SemanticAction = 421
	ActionZcResultMakeGuild SemanticAction = 422
	ActionZcResurrection SemanticAction = 423
	ActionZcRoleChange SemanticAction = 424
	ActionZcSayDialog SemanticAction = 425
	ActionZcSeCashshopOpen SemanticAction = 426
	ActionZcSePcBuyCashitemResult SemanticAction = 427
	ActionZcSearchStoreInfoAck SemanticAction = 428
	ActionZcSearchStoreInfoFailed SemanticAction = 429
	ActionZcSelectDealtype SemanticAction = 430
	ActionZcShortcutKeyList SemanticAction = 431
	ActionZcShowImage SemanticAction = 432
	ActionZcSkillDisappear SemanticAction = 433
	ActionZcSkillSelectRequest SemanticAction = 434
	ActionZcSkillUpdate SemanticAction = 435
	ActionZcSkillinfoUpdate2 SemanticAction = 436
	ActionZcSoulenergy SemanticAction = 437
	ActionZcSound SemanticAction = 438
	ActionZcSpecialpopup SemanticAction = 439
	ActionZcSpirits SemanticAction = 440
	ActionZcSpirits2 SemanticAction = 441
	ActionZcSpiritsAttribute SemanticAction = 442
	ActionZcSsilistItemClickAck SemanticAction = 443
	ActionZcStartCapture SemanticAction = 444
	ActionZcStateChange SemanticAction = 445
	ActionZcStatus SemanticAction = 446
	ActionZcStatusChangeAck SemanticAction = 447
	ActionZcStopmove SemanticAction = 448
	ActionZcSummonHpInit SemanticAction = 449
	ActionZcSummonHpUpdate SemanticAction = 450
	ActionZcTalkboxChatcontents SemanticAction = 451
	ActionZcTargetSpirits SemanticAction = 452
	ActionZcTrycaptureMonster SemanticAction = 453
	ActionZcUiOpen SemanticAction = 454
	ActionZcUiOpen2 SemanticAction = 455
	ActionZcUpdateCardslot SemanticAction = 456
	ActionZcUpdateGdid SemanticAction = 457
	ActionZcUseskillAck SemanticAction = 458
	ActionZcViewCamerainfo SemanticAction = 459
	ActionZcWaitDialog SemanticAction = 460

	// maxSemanticAction is the highest assigned SemanticAction value.
	// Used to size the sendRegistry array in semantic.go.
	maxSemanticAction SemanticAction = ActionZcWaitDialog
)

// String returns the constant name for known SemanticAction values
// and "SemanticAction(N)" for unknown ones.
func (a SemanticAction) String() string {
	switch a {
	case ActionUnknown:
		return "ActionUnknown"
	case ActionAcAcceptLogin:
		return "ActionAcAcceptLogin"
	case ActionAcAckHash:
		return "ActionAcAckHash"
	case ActionAcRefuseLogin:
		return "ActionAcRefuseLogin"
	case ActionAccessibleMaps:
		return "ActionAccessibleMaps"
	case ActionAccountId:
		return "ActionAccountId"
	case ActionAccountServerInfo:
		return "ActionAccountServerInfo"
	case ActionActorAction:
		return "ActionActorAction"
	case ActionActorConnected:
		return "ActionActorConnected"
	case ActionActorDiedOrDisappeared:
		return "ActionActorDiedOrDisappeared"
	case ActionActorExists:
		return "ActionActorExists"
	case ActionActorMoved:
		return "ActionActorMoved"
	case ActionActorStatusActive:
		return "ActionActorStatusActive"
	case ActionActorStatusEffectExtended:
		return "ActionActorStatusEffectExtended"
	case ActionAddExchangeItem:
		return "ActionAddExchangeItem"
	case ActionAreaSpell:
		return "ActionAreaSpell"
	case ActionAttackRange:
		return "ActionAttackRange"
	case ActionAutoSpell:
		return "ActionAutoSpell"
	case ActionBankingCheck:
		return "ActionBankingCheck"
	case ActionBankingDeposit:
		return "ActionBankingDeposit"
	case ActionBankingOpen:
		return "ActionBankingOpen"
	case ActionBankingWithdraw:
		return "ActionBankingWithdraw"
	case ActionCaConnectInfoChanged:
		return "ActionCaConnectInfoChanged"
	case ActionCaExeHashcheck:
		return "ActionCaExeHashcheck"
	case ActionCaLogin2:
		return "ActionCaLogin2"
	case ActionCaLogin3:
		return "ActionCaLogin3"
	case ActionCaLogin4:
		return "ActionCaLogin4"
	case ActionCaLoginChannel:
		return "ActionCaLoginChannel"
	case ActionCaLoginPcbang:
		return "ActionCaLoginPcbang"
	case ActionCaReqHash:
		return "ActionCaReqHash"
	case ActionCaSsoLoginReq:
		return "ActionCaSsoLoginReq"
	case ActionCastCancelled:
		return "ActionCastCancelled"
	case ActionCatchPet:
		return "ActionCatchPet"
	case ActionChangeCart:
		return "ActionChangeCart"
	case ActionCharCreate:
		return "ActionCharCreate"
	case ActionCharDelete:
		return "ActionCharDelete"
	case ActionCharLogin:
		return "ActionCharLogin"
	case ActionCharacterBlocked:
		return "ActionCharacterBlocked"
	case ActionCharacterCreationFailed:
		return "ActionCharacterCreationFailed"
	case ActionCharacterMove:
		return "ActionCharacterMove"
	case ActionCharacterMoves:
		return "ActionCharacterMoves"
	case ActionCharacterPagesNotify:
		return "ActionCharacterPagesNotify"
	case ActionCharacterServerRefused:
		return "ActionCharacterServerRefused"
	case ActionChatMessage:
		return "ActionChatMessage"
	case ActionCloseStorage:
		return "ActionCloseStorage"
	case ActionCloseVending:
		return "ActionCloseVending"
	case ActionCtAuth:
		return "ActionCtAuth"
	case ActionCzAckAnswerMacroDetector:
		return "ActionCzAckAnswerMacroDetector"
	case ActionCzAdvancedStatusChange:
		return "ActionCzAdvancedStatusChange"
	case ActionCzAdventurerAgencyJoinReq:
		return "ActionCzAdventurerAgencyJoinReq"
	case ActionCzAdventurerAgencyJoinResult:
		return "ActionCzAdventurerAgencyJoinResult"
	case ActionCzApproximateActor:
		return "ActionCzApproximateActor"
	case ActionCzCheckname1:
		return "ActionCzCheckname1"
	case ActionCzCheckname2:
		return "ActionCzCheckname2"
	case ActionCzChooseMenuZero:
		return "ActionCzChooseMenuZero"
	case ActionCzClientVersion:
		return "ActionCzClientVersion"
	case ActionCzCloseMsgboxExtendBodyitemSize:
		return "ActionCzCloseMsgboxExtendBodyitemSize"
	case ActionCzCloseRefiningUi:
		return "ActionCzCloseRefiningUi"
	case ActionCzCloseReformUi:
		return "ActionCzCloseReformUi"
	case ActionCzCloseUiEnchant:
		return "ActionCzCloseUiEnchant"
	case ActionCzCloseUiStylingshop:
		return "ActionCzCloseUiStylingshop"
	case ActionCzCmdResetcooltime:
		return "ActionCzCmdResetcooltime"
	case ActionCzCompleteApplyMacroDetectorCaptcha:
		return "ActionCzCompleteApplyMacroDetectorCaptcha"
	case ActionCzContactnpc:
		return "ActionCzContactnpc"
	case ActionCzDynamicnpcCreateRequest:
		return "ActionCzDynamicnpcCreateRequest"
	case ActionCzGetAccountLimtiedSaleList:
		return "ActionCzGetAccountLimtiedSaleList"
	case ActionCzGradeEnchantCloseUi:
		return "ActionCzGradeEnchantCloseUi"
	case ActionCzGradeEnchantRequest:
		return "ActionCzGradeEnchantRequest"
	case ActionCzGradeEnchantSelectEquipment:
		return "ActionCzGradeEnchantSelectEquipment"
	case ActionCzInventoryTab:
		return "ActionCzInventoryTab"
	case ActionCzItemReform:
		return "ActionCzItemReform"
	case ActionCzJoinGroup:
		return "ActionCzJoinGroup"
	case ActionCzJoinGuild:
		return "ActionCzJoinGuild"
	case ActionCzMoveItemFromBodyToCart:
		return "ActionCzMoveItemFromBodyToCart"
	case ActionCzNpcBarterMarketClose:
		return "ActionCzNpcBarterMarketClose"
	case ActionCzNpcBarterMarketPurchase:
		return "ActionCzNpcBarterMarketPurchase"
	case ActionCzNpcExpandedBarterMarketClose:
		return "ActionCzNpcExpandedBarterMarketClose"
	case ActionCzNpcExpandedBarterMarketPurchase:
		return "ActionCzNpcExpandedBarterMarketPurchase"
	case ActionCzNpcMarketPurchase:
		return "ActionCzNpcMarketPurchase"
	case ActionCzPartyConfig:
		return "ActionCzPartyConfig"
	case ActionCzPartyJoinReq:
		return "ActionCzPartyJoinReq"
	case ActionCzPartyJoinReqAck:
		return "ActionCzPartyJoinReqAck"
	case ActionCzPcPurchaseItemlistFrommc:
		return "ActionCzPcPurchaseItemlistFrommc"
	case ActionCzPcPurchaseItemlistFrommc2:
		return "ActionCzPcPurchaseItemlistFrommc2"
	case ActionCzPingLive:
		return "ActionCzPingLive"
	case ActionCzRandomCombineItemUiClose:
		return "ActionCzRandomCombineItemUiClose"
	case ActionCzRandomUpgradeItemUiClose:
		return "ActionCzRandomUpgradeItemUiClose"
	case ActionCzRefiningSelectItem:
		return "ActionCzRefiningSelectItem"
	case ActionCzReqAgitInvestment:
		return "ActionCzReqAgitInvestment"
	case ActionCzReqApplyBargainSaleItem:
		return "ActionCzReqApplyBargainSaleItem"
	case ActionCzReqApplyMacroDetector:
		return "ActionCzReqApplyMacroDetector"
	case ActionCzReqBanGuild:
		return "ActionCzReqBanGuild"
	case ActionCzReqCashBargainSaleItemInfo:
		return "ActionCzReqCashBargainSaleItemInfo"
	case ActionCzReqChangeMemberpos:
		return "ActionCzReqChangeMemberpos"
	case ActionCzReqDisorganizeGuild:
		return "ActionCzReqDisorganizeGuild"
	case ActionCzReqExtendBodyitemSize:
		return "ActionCzReqExtendBodyitemSize"
	case ActionCzReqGuildEmblemImg1:
		return "ActionCzReqGuildEmblemImg1"
	case ActionCzReqGuildEmblemImg2:
		return "ActionCzReqGuildEmblemImg2"
	case ActionCzReqGuildEmblemImg3:
		return "ActionCzReqGuildEmblemImg3"
	case ActionCzReqItemrepair1:
		return "ActionCzReqItemrepair1"
	case ActionCzReqItemrepair2:
		return "ActionCzReqItemrepair2"
	case ActionCzReqJoinGuild:
		return "ActionCzReqJoinGuild"
	case ActionCzReqJoinGuild2:
		return "ActionCzReqJoinGuild2"
	case ActionCzReqLeaveGuild:
		return "ActionCzReqLeaveGuild"
	case ActionCzReqMakingarrow:
		return "ActionCzReqMakingarrow"
	case ActionCzReqMergeItem:
		return "ActionCzReqMergeItem"
	case ActionCzReqMoveGuildAgit:
		return "ActionCzReqMoveGuildAgit"
	case ActionCzReqOpenMsgboxExtendBodyitemSize:
		return "ActionCzReqOpenMsgboxExtendBodyitemSize"
	case ActionCzReqPlayerAidInRange:
		return "ActionCzReqPlayerAidInRange"
	case ActionCzReqPreviewMacroDetector:
		return "ActionCzReqPreviewMacroDetector"
	case ActionCzReqRandomCombineItem:
		return "ActionCzReqRandomCombineItem"
	case ActionCzReqRandomUpgradeItem:
		return "ActionCzReqRandomUpgradeItem"
	case ActionCzReqRefining:
		return "ActionCzReqRefining"
	case ActionCzReqRemaintime:
		return "ActionCzReqRemaintime"
	case ActionCzReqRemoveBargainSaleItem:
		return "ActionCzReqRemoveBargainSaleItem"
	case ActionCzReqSeCashTabCode:
		return "ActionCzReqSeCashTabCode"
	case ActionCzReqTakeoffEquipAll:
		return "ActionCzReqTakeoffEquipAll"
	case ActionCzReqUploadMacroDetector:
		return "ActionCzReqUploadMacroDetector"
	case ActionCzRequestPerfectEnchant:
		return "ActionCzRequestPerfectEnchant"
	case ActionCzRequestRandomEnchant:
		return "ActionCzRequestRandomEnchant"
	case ActionCzRequestResetEnchant:
		return "ActionCzRequestResetEnchant"
	case ActionCzRequestUpgradeEnchant:
		return "ActionCzRequestUpgradeEnchant"
	case ActionCzResetSkill:
		return "ActionCzResetSkill"
	case ActionCzRodexReturn:
		return "ActionCzRodexReturn"
	case ActionCzSeCashshopOpen1:
		return "ActionCzSeCashshopOpen1"
	case ActionCzSeCashshopOpen2:
		return "ActionCzSeCashshopOpen2"
	case ActionCzSePcBuyCashitemList:
		return "ActionCzSePcBuyCashitemList"
	case ActionCzShortcutKeyChange1:
		return "ActionCzShortcutKeyChange1"
	case ActionCzShortcutKeyChange2:
		return "ActionCzShortcutKeyChange2"
	case ActionCzShortcutkeybarRotate1:
		return "ActionCzShortcutkeybarRotate1"
	case ActionCzShortcutkeybarRotate2:
		return "ActionCzShortcutkeybarRotate2"
	case ActionCzUninstallation:
		return "ActionCzUninstallation"
	case ActionCzUploadMacroDetectorCaptcha:
		return "ActionCzUploadMacroDetectorCaptcha"
	case ActionCzUsePackageitem:
		return "ActionCzUsePackageitem"
	case ActionCzUseSkillEnd:
		return "ActionCzUseSkillEnd"
	case ActionCzUseSkillStart:
		return "ActionCzUseSkillStart"
	case ActionCzViewCamerainfo:
		return "ActionCzViewCamerainfo"
	case ActionDealAddOther:
		return "ActionDealAddOther"
	case ActionDealCancel:
		return "ActionDealCancel"
	case ActionDealFinalize:
		return "ActionDealFinalize"
	case ActionDealInitiate:
		return "ActionDealInitiate"
	case ActionDealReply:
		return "ActionDealReply"
	case ActionDealRequest:
		return "ActionDealRequest"
	case ActionDealTrade:
		return "ActionDealTrade"
	case ActionDropItem:
		return "ActionDropItem"
	case ActionEmote:
		return "ActionEmote"
	case ActionEnterWorld:
		return "ActionEnterWorld"
	case ActionEntityMove:
		return "ActionEntityMove"
	case ActionEntitySpawn:
		return "ActionEntitySpawn"
	case ActionEquipItem:
		return "ActionEquipItem"
	case ActionFriendsAdd:
		return "ActionFriendsAdd"
	case ActionFriendsRemove:
		return "ActionFriendsRemove"
	case ActionFriendsReply:
		return "ActionFriendsReply"
	case ActionGameLogin:
		return "ActionGameLogin"
	case ActionGetItemFromCart:
		return "ActionGetItemFromCart"
	case ActionHomunculusAttack:
		return "ActionHomunculusAttack"
	case ActionHomunculusInfo:
		return "ActionHomunculusInfo"
	case ActionHomunculusMenu:
		return "ActionHomunculusMenu"
	case ActionIgnoreListReq:
		return "ActionIgnoreListReq"
	case ActionInsertCard:
		return "ActionInsertCard"
	case ActionInventoryItemAdded:
		return "ActionInventoryItemAdded"
	case ActionItemAppeared:
		return "ActionItemAppeared"
	case ActionItemDisappeared:
		return "ActionItemDisappeared"
	case ActionItemExists:
		return "ActionItemExists"
	case ActionItemIdentify:
		return "ActionItemIdentify"
	case ActionItemPickup:
		return "ActionItemPickup"
	case ActionItemUse:
		return "ActionItemUse"
	case ActionLoginError:
		return "ActionLoginError"
	case ActionLook:
		return "ActionLook"
	case ActionMapChanged:
		return "ActionMapChanged"
	case ActionMapLoaded:
		return "ActionMapLoaded"
	case ActionMapLogin:
		return "ActionMapLogin"
	case ActionMarketPurchase:
		return "ActionMarketPurchase"
	case ActionMasterLogin:
		return "ActionMasterLogin"
	case ActionMonsterHpUpdate:
		return "ActionMonsterHpUpdate"
	case ActionMonsterRangedAttack:
		return "ActionMonsterRangedAttack"
	case ActionMoveFromStorage:
		return "ActionMoveFromStorage"
	case ActionMoveTo:
		return "ActionMoveTo"
	case ActionMoveToStorage:
		return "ActionMoveToStorage"
	case ActionNpcContact:
		return "ActionNpcContact"
	case ActionNpcMarketClose:
		return "ActionNpcMarketClose"
	case ActionNpcMenuResponse:
		return "ActionNpcMenuResponse"
	case ActionNpcStoreInfo:
		return "ActionNpcStoreInfo"
	case ActionNpcTalkClose:
		return "ActionNpcTalkClose"
	case ActionNpcTalkContinue:
		return "ActionNpcTalkContinue"
	case ActionNpcTalkNumber:
		return "ActionNpcTalkNumber"
	case ActionNpcTalkText:
		return "ActionNpcTalkText"
	case ActionNpcTradeQuit:
		return "ActionNpcTradeQuit"
	case ActionPartyChangeOption:
		return "ActionPartyChangeOption"
	case ActionPartyCreate:
		return "ActionPartyCreate"
	case ActionPartyInvite:
		return "ActionPartyInvite"
	case ActionPartyKick:
		return "ActionPartyKick"
	case ActionPartyLeave:
		return "ActionPartyLeave"
	case ActionPetEggList:
		return "ActionPetEggList"
	case ActionPetInfo:
		return "ActionPetInfo"
	case ActionPetMenu:
		return "ActionPetMenu"
	case ActionPickupItem:
		return "ActionPickupItem"
	case ActionPinCodeRequest:
		return "ActionPinCodeRequest"
	case ActionPinCodeResponse:
		return "ActionPinCodeResponse"
	case ActionPrivateMessage:
		return "ActionPrivateMessage"
	case ActionPublicChat:
		return "ActionPublicChat"
	case ActionQuestDialog:
		return "ActionQuestDialog"
	case ActionQuestDialogList:
		return "ActionQuestDialogList"
	case ActionQuestUpdateMissionHunt:
		return "ActionQuestUpdateMissionHunt"
	case ActionQuitGame:
		return "ActionQuitGame"
	case ActionReceivedCharacterIDAndMap:
		return "ActionReceivedCharacterIDAndMap"
	case ActionReceivedCharacterIdAndMap:
		return "ActionReceivedCharacterIdAndMap"
	case ActionReceivedCharacters:
		return "ActionReceivedCharacters"
	case ActionReceivedCharactersInfo:
		return "ActionReceivedCharactersInfo"
	case ActionReceivedCharactersPage:
		return "ActionReceivedCharactersPage"
	case ActionReceivedMapServerInfo:
		return "ActionReceivedMapServerInfo"
	case ActionRemoveOption:
		return "ActionRemoveOption"
	case ActionRemovePartyMember:
		return "ActionRemovePartyMember"
	case ActionRepairItem:
		return "ActionRepairItem"
	case ActionReplyPartyInvite:
		return "ActionReplyPartyInvite"
	case ActionRequestAction:
		return "ActionRequestAction"
	case ActionRequestCharacterPage:
		return "ActionRequestCharacterPage"
	case ActionRequestCharlist:
		return "ActionRequestCharlist"
	case ActionRequestMemo:
		return "ActionRequestMemo"
	case ActionRestart:
		return "ActionRestart"
	case ActionScNotifyBan:
		return "ActionScNotifyBan"
	case ActionSelectAccessibleMap:
		return "ActionSelectAccessibleMap"
	case ActionSelectArrow:
		return "ActionSelectArrow"
	case ActionSelectCharacter:
		return "ActionSelectCharacter"
	case ActionSelectEgg:
		return "ActionSelectEgg"
	case ActionSelfChat:
		return "ActionSelfChat"
	case ActionSendEmotion:
		return "ActionSendEmotion"
	case ActionShopBuy:
		return "ActionShopBuy"
	case ActionShopSell:
		return "ActionShopSell"
	case ActionSkillAdd:
		return "ActionSkillAdd"
	case ActionSkillCast:
		return "ActionSkillCast"
	case ActionSkillDelete:
		return "ActionSkillDelete"
	case ActionSkillPostDelay:
		return "ActionSkillPostDelay"
	case ActionSkillUp:
		return "ActionSkillUp"
	case ActionSkillUpdate:
		return "ActionSkillUpdate"
	case ActionSkillUse:
		return "ActionSkillUse"
	case ActionSkillUseFailed:
		return "ActionSkillUseFailed"
	case ActionSkillUseLocation:
		return "ActionSkillUseLocation"
	case ActionSkillUsedNoDamage:
		return "ActionSkillUsedNoDamage"
	case ActionSkillsList:
		return "ActionSkillsList"
	case ActionStatUpdate:
		return "ActionStatUpdate"
	case ActionStatusUp:
		return "ActionStatusUp"
	case ActionSync:
		return "ActionSync"
	case ActionSystemChat:
		return "ActionSystemChat"
	case ActionTcResult:
		return "ActionTcResult"
	case ActionTimeSyncResponse:
		return "ActionTimeSyncResponse"
	case ActionUnequipItem:
		return "ActionUnequipItem"
	case ActionUseCard:
		return "ActionUseCard"
	case ActionVenderFound:
		return "ActionVenderFound"
	case ActionVendingListReq:
		return "ActionVendingListReq"
	case ActionWeaponRefine:
		return "ActionWeaponRefine"
	case ActionWhisperSent:
		return "ActionWhisperSent"
	case ActionZcAcceptEnter:
		return "ActionZcAcceptEnter"
	case ActionZcAckAddExchangeItem:
		return "ActionZcAckAddExchangeItem"
	case ActionZcAckAddItemRodex:
		return "ActionZcAckAddItemRodex"
	case ActionZcAckAdditemToCart:
		return "ActionZcAckAdditemToCart"
	case ActionZcAckApplyMacroDetector:
		return "ActionZcAckApplyMacroDetector"
	case ActionZcAckCashBargainSaleItemInfo:
		return "ActionZcAckCashBargainSaleItemInfo"
	case ActionZcAckCloseBanking:
		return "ActionZcAckCloseBanking"
	case ActionZcAckCloseRoulette:
		return "ActionZcAckCloseRoulette"
	case ActionZcAckCountBargainSaleItem:
		return "ActionZcAckCountBargainSaleItem"
	case ActionZcAckCreateChatroom:
		return "ActionZcAckCreateChatroom"
	case ActionZcAckDisorganizeGuildResult:
		return "ActionZcAckDisorganizeGuildResult"
	case ActionZcAckExtendBodyitemSize:
		return "ActionZcAckExtendBodyitemSize"
	case ActionZcAckGuildstorageLog:
		return "ActionZcAckGuildstorageLog"
	case ActionZcAckItemcomposition:
		return "ActionZcAckItemcomposition"
	case ActionZcAckItemidentify:
		return "ActionZcAckItemidentify"
	case ActionZcAckItemrefining:
		return "ActionZcAckItemrefining"
	case ActionZcAckItemrepair:
		return "ActionZcAckItemrepair"
	case ActionZcAckMakeGroup:
		return "ActionZcAckMakeGroup"
	case ActionZcAckMergeItem:
		return "ActionZcAckMergeItem"
	case ActionZcAckOpenMsgboxExtendBodyitemSize:
		return "ActionZcAckOpenMsgboxExtendBodyitemSize"
	case ActionZcAckOpenstore2:
		return "ActionZcAckOpenstore2"
	case ActionZcAckPlayerAidInRange:
		return "ActionZcAckPlayerAidInRange"
	case ActionZcAckPreviewMacroDetector:
		return "ActionZcAckPreviewMacroDetector"
	case ActionZcAckRandomCombineItem:
		return "ActionZcAckRandomCombineItem"
	case ActionZcAckRandomUpgradeItem:
		return "ActionZcAckRandomUpgradeItem"
	case ActionZcAckRanking:
		return "ActionZcAckRanking"
	case ActionZcAckReadRodex:
		return "ActionZcAckReadRodex"
	case ActionZcAckRememberWarppoint:
		return "ActionZcAckRememberWarppoint"
	case ActionZcAckReqJoinGuild:
		return "ActionZcAckReqJoinGuild"
	case ActionZcAckReqnameall:
		return "ActionZcAckReqnameall"
	case ActionZcAckReqnameallNpc:
		return "ActionZcAckReqnameallNpc"
	case ActionZcAckSeCashItemList2:
		return "ActionZcAckSeCashItemList2"
	case ActionZcAckTakeoffEquipAll:
		return "ActionZcAckTakeoffEquipAll"
	case ActionZcAckUploadMacroDetector:
		return "ActionZcAckUploadMacroDetector"
	case ActionZcActionFailure:
		return "ActionZcActionFailure"
	case ActionZcAddItemToCart:
		return "ActionZcAddItemToCart"
	case ActionZcAddItemToStore:
		return "ActionZcAddItemToStore"
	case ActionZcAdventurerAgencyJoinReq:
		return "ActionZcAdventurerAgencyJoinReq"
	case ActionZcAdventurerAgencyJoinResult:
		return "ActionZcAdventurerAgencyJoinResult"
	case ActionZcApplyMacroDetector:
		return "ActionZcApplyMacroDetector"
	case ActionZcApplyMacroDetectorCaptcha:
		return "ActionZcApplyMacroDetectorCaptcha"
	case ActionZcAutorunSkill:
		return "ActionZcAutorunSkill"
	case ActionZcAutospelllist:
		return "ActionZcAutospelllist"
	case ActionZcBattlefieldNotifyHp:
		return "ActionZcBattlefieldNotifyHp"
	case ActionZcBossInfo:
		return "ActionZcBossInfo"
	case ActionZcBroadcast:
		return "ActionZcBroadcast"
	case ActionZcBroadcast2:
		return "ActionZcBroadcast2"
	case ActionZcBroadcastItemrefiningResult:
		return "ActionZcBroadcastItemrefiningResult"
	case ActionZcBroadcastingSpecialItemObtainItem:
		return "ActionZcBroadcastingSpecialItemObtainItem"
	case ActionZcBuyingStoreEntry:
		return "ActionZcBuyingStoreEntry"
	case ActionZcCMarkerinfo:
		return "ActionZcCMarkerinfo"
	case ActionZcCancelExchangeItem:
		return "ActionZcCancelExchangeItem"
	case ActionZcCartoff:
		return "ActionZcCartoff"
	case ActionZcChangeGuild:
		return "ActionZcChangeGuild"
	case ActionZcChangeItemOption:
		return "ActionZcChangeItemOption"
	case ActionZcChangestatePet:
		return "ActionZcChangestatePet"
	case ActionZcCheckname:
		return "ActionZcCheckname"
	case ActionZcClaninfo:
		return "ActionZcClaninfo"
	case ActionZcClearDialog:
		return "ActionZcClearDialog"
	case ActionZcCloseDialog:
		return "ActionZcCloseDialog"
	case ActionZcCloseMacroDetector:
		return "ActionZcCloseMacroDetector"
	case ActionZcCloseStore:
		return "ActionZcCloseStore"
	case ActionZcCompass:
		return "ActionZcCompass"
	case ActionZcCompleteUploadMacroDetectorCaptcha:
		return "ActionZcCompleteUploadMacroDetectorCaptcha"
	case ActionZcCouplename:
		return "ActionZcCouplename"
	case ActionZcCouplestatus:
		return "ActionZcCouplestatus"
	case ActionZcDebugmsg:
		return "ActionZcDebugmsg"
	case ActionZcDeleteItemFromBody:
		return "ActionZcDeleteItemFromBody"
	case ActionZcDeleteItemFromCart:
		return "ActionZcDeleteItemFromCart"
	case ActionZcDeleteItemFromStore:
		return "ActionZcDeleteItemFromStore"
	case ActionZcDeleteMemberFromGroup:
		return "ActionZcDeleteMemberFromGroup"
	case ActionZcDeleteitemFromMcstore:
		return "ActionZcDeleteitemFromMcstore"
	case ActionZcDialogTextAlign:
		return "ActionZcDialogTextAlign"
	case ActionZcDialogWindowPos:
		return "ActionZcDialogWindowPos"
	case ActionZcDialogWindowPos2:
		return "ActionZcDialogWindowPos2"
	case ActionZcDialogWindowSize:
		return "ActionZcDialogWindowSize"
	case ActionZcDisappearBuyingStoreEntry:
		return "ActionZcDisappearBuyingStoreEntry"
	case ActionZcDynamicnpcCreateResult:
		return "ActionZcDynamicnpcCreateResult"
	case ActionZcEntryQueueInit:
		return "ActionZcEntryQueueInit"
	case ActionZcEquipArrow:
		return "ActionZcEquipArrow"
	case ActionZcEquipitemDamaged:
		return "ActionZcEquipitemDamaged"
	case ActionZcEquipmentEffect:
		return "ActionZcEquipmentEffect"
	case ActionZcEquipwinMicroscope:
		return "ActionZcEquipwinMicroscope"
	case ActionZcExchangeitemUndo:
		return "ActionZcExchangeitemUndo"
	case ActionZcExecExchangeItem:
		return "ActionZcExecExchangeItem"
	case ActionZcExtendBodyitemSize:
		return "ActionZcExtendBodyitemSize"
	case ActionZcFriendsList:
		return "ActionZcFriendsList"
	case ActionZcGoldpccafePoint:
		return "ActionZcGoldpccafePoint"
	case ActionZcGradeEnchantAck:
		return "ActionZcGradeEnchantAck"
	case ActionZcGradeEnchantBroadcastResult:
		return "ActionZcGradeEnchantBroadcastResult"
	case ActionZcGradeEnchantMaterialList:
		return "ActionZcGradeEnchantMaterialList"
	case ActionZcGuildAgitInfo:
		return "ActionZcGuildAgitInfo"
	case ActionZcGuildEmblemImg:
		return "ActionZcGuildEmblemImg"
	case ActionZcGuildInfo:
		return "ActionZcGuildInfo"
	case ActionZcGuildNotice:
		return "ActionZcGuildNotice"
	case ActionZcGuildSkillinfo:
		return "ActionZcGuildSkillinfo"
	case ActionZcHoskillinfoList:
		return "ActionZcHoskillinfoList"
	case ActionZcHoskillinfoUpdate:
		return "ActionZcHoskillinfoUpdate"
	case ActionZcInventoryEnd:
		return "ActionZcInventoryEnd"
	case ActionZcInventoryStart:
		return "ActionZcInventoryStart"
	case ActionZcInventoryTab:
		return "ActionZcInventoryTab"
	case ActionZcItemDisappear:
		return "ActionZcItemDisappear"
	case ActionZcItemPickupParty:
		return "ActionZcItemPickupParty"
	case ActionZcItemReformAck:
		return "ActionZcItemReformAck"
	case ActionZcItemThrowAck:
		return "ActionZcItemThrowAck"
	case ActionZcLonglongparChange:
		return "ActionZcLonglongparChange"
	case ActionZcMakingarrowList:
		return "ActionZcMakingarrowList"
	case ActionZcMakingitemList:
		return "ActionZcMakingitemList"
	case ActionZcMembermgrInfo:
		return "ActionZcMembermgrInfo"
	case ActionZcMenuList:
		return "ActionZcMenuList"
	case ActionZcMergeItemOpen:
		return "ActionZcMergeItemOpen"
	case ActionZcMillenniumshield:
		return "ActionZcMillenniumshield"
	case ActionZcMonologDialog:
		return "ActionZcMonologDialog"
	case ActionZcMoveItemFailed:
		return "ActionZcMoveItemFailed"
	case ActionZcMyguildBasicInfo:
		return "ActionZcMyguildBasicInfo"
	case ActionZcNotifyActorinit:
		return "ActionZcNotifyActorinit"
	case ActionZcNotifyBargainSaleClose:
		return "ActionZcNotifyBargainSaleClose"
	case ActionZcNotifyBargainSaleSelling:
		return "ActionZcNotifyBargainSaleSelling"
	case ActionZcNotifyBindOnEquip:
		return "ActionZcNotifyBindOnEquip"
	case ActionZcNotifyCartitemCountinfo:
		return "ActionZcNotifyCartitemCountinfo"
	case ActionZcNotifyChatParty:
		return "ActionZcNotifyChatParty"
	case ActionZcNotifyEffect:
		return "ActionZcNotifyEffect"
	case ActionZcNotifyEffect3:
		return "ActionZcNotifyEffect3"
	case ActionZcNotifyGroundskill:
		return "ActionZcNotifyGroundskill"
	case ActionZcNotifyHpToGroupm:
		return "ActionZcNotifyHpToGroupm"
	case ActionZcNotifyMapinfo:
		return "ActionZcNotifyMapinfo"
	case ActionZcNotifyMapproperty2:
		return "ActionZcNotifyMapproperty2"
	case ActionZcNotifyMemberinfoToGroupm:
		return "ActionZcNotifyMemberinfoToGroupm"
	case ActionZcNotifyPositionToGroupm:
		return "ActionZcNotifyPositionToGroupm"
	case ActionZcNotifyPositionToGuildm:
		return "ActionZcNotifyPositionToGuildm"
	case ActionZcNotifyStoreitemCountinfo:
		return "ActionZcNotifyStoreitemCountinfo"
	case ActionZcNpcBarterMarketIteminfo:
		return "ActionZcNpcBarterMarketIteminfo"
	case ActionZcNpcMarketOpen:
		return "ActionZcNpcMarketOpen"
	case ActionZcNpcMarketPurchaseResult:
		return "ActionZcNpcMarketPurchaseResult"
	case ActionZcNpcShowefstUpdate:
		return "ActionZcNpcShowefstUpdate"
	case ActionZcNpcackServermove:
		return "ActionZcNpcackServermove"
	case ActionZcOpenEditdlg:
		return "ActionZcOpenEditdlg"
	case ActionZcOpenEditdlgstr:
		return "ActionZcOpenEditdlgstr"
	case ActionZcOpenRefiningUi:
		return "ActionZcOpenRefiningUi"
	case ActionZcOpenReformUi:
		return "ActionZcOpenReformUi"
	case ActionZcOpenSearchStoreInfo:
		return "ActionZcOpenSearchStoreInfo"
	case ActionZcOpenstore:
		return "ActionZcOpenstore"
	case ActionZcParChangeUser:
		return "ActionZcParChangeUser"
	case ActionZcPartyConfig:
		return "ActionZcPartyConfig"
	case ActionZcPcPurchaseItemlistFrommc:
		return "ActionZcPcPurchaseItemlistFrommc"
	case ActionZcPcPurchaseMyitemlist:
		return "ActionZcPcPurchaseMyitemlist"
	case ActionZcPcPurchaseResult:
		return "ActionZcPcPurchaseResult"
	case ActionZcPcPurchaseResultFrommc:
		return "ActionZcPcPurchaseResultFrommc"
	case ActionZcPcSellItemlist:
		return "ActionZcPcSellItemlist"
	case ActionZcPersonalInfomation:
		return "ActionZcPersonalInfomation"
	case ActionZcPingLive:
		return "ActionZcPingLive"
	case ActionZcPlayNpcBgm:
		return "ActionZcPlayNpcBgm"
	case ActionZcPositionIdNameInfo:
		return "ActionZcPositionIdNameInfo"
	case ActionZcPositionInfo:
		return "ActionZcPositionInfo"
	case ActionZcPreviewMacroDetectorCaptcha:
		return "ActionZcPreviewMacroDetectorCaptcha"
	case ActionZcPropertyHomun:
		return "ActionZcPropertyHomun"
	case ActionZcRandomCombineItemUiOpen:
		return "ActionZcRandomCombineItemUiOpen"
	case ActionZcRandomUpgradeItemUiOpen:
		return "ActionZcRandomUpgradeItemUiOpen"
	case ActionZcRecovery:
		return "ActionZcRecovery"
	case ActionZcRefiningMaterialList:
		return "ActionZcRefiningMaterialList"
	case ActionZcRefuseEnterRoom:
		return "ActionZcRefuseEnterRoom"
	case ActionZcRepairitemlist:
		return "ActionZcRepairitemlist"
	case ActionZcReputeInfo:
		return "ActionZcReputeInfo"
	case ActionZcReqAckAgitInvestment:
		return "ActionZcReqAckAgitInvestment"
	case ActionZcReqAckMoveGuildAgit:
		return "ActionZcReqAckMoveGuildAgit"
	case ActionZcReqAnswerMacroDetector:
		return "ActionZcReqAnswerMacroDetector"
	case ActionZcReqJoinGuild:
		return "ActionZcReqJoinGuild"
	case ActionZcReqWearEquipAck:
		return "ActionZcReqWearEquipAck"
	case ActionZcResponseEnchant:
		return "ActionZcResponseEnchant"
	case ActionZcRestartAck:
		return "ActionZcRestartAck"
	case ActionZcResultMakeGuild:
		return "ActionZcResultMakeGuild"
	case ActionZcResurrection:
		return "ActionZcResurrection"
	case ActionZcRoleChange:
		return "ActionZcRoleChange"
	case ActionZcSayDialog:
		return "ActionZcSayDialog"
	case ActionZcSeCashshopOpen:
		return "ActionZcSeCashshopOpen"
	case ActionZcSePcBuyCashitemResult:
		return "ActionZcSePcBuyCashitemResult"
	case ActionZcSearchStoreInfoAck:
		return "ActionZcSearchStoreInfoAck"
	case ActionZcSearchStoreInfoFailed:
		return "ActionZcSearchStoreInfoFailed"
	case ActionZcSelectDealtype:
		return "ActionZcSelectDealtype"
	case ActionZcShortcutKeyList:
		return "ActionZcShortcutKeyList"
	case ActionZcShowImage:
		return "ActionZcShowImage"
	case ActionZcSkillDisappear:
		return "ActionZcSkillDisappear"
	case ActionZcSkillSelectRequest:
		return "ActionZcSkillSelectRequest"
	case ActionZcSkillUpdate:
		return "ActionZcSkillUpdate"
	case ActionZcSkillinfoUpdate2:
		return "ActionZcSkillinfoUpdate2"
	case ActionZcSoulenergy:
		return "ActionZcSoulenergy"
	case ActionZcSound:
		return "ActionZcSound"
	case ActionZcSpecialpopup:
		return "ActionZcSpecialpopup"
	case ActionZcSpirits:
		return "ActionZcSpirits"
	case ActionZcSpirits2:
		return "ActionZcSpirits2"
	case ActionZcSpiritsAttribute:
		return "ActionZcSpiritsAttribute"
	case ActionZcSsilistItemClickAck:
		return "ActionZcSsilistItemClickAck"
	case ActionZcStartCapture:
		return "ActionZcStartCapture"
	case ActionZcStateChange:
		return "ActionZcStateChange"
	case ActionZcStatus:
		return "ActionZcStatus"
	case ActionZcStatusChangeAck:
		return "ActionZcStatusChangeAck"
	case ActionZcStopmove:
		return "ActionZcStopmove"
	case ActionZcSummonHpInit:
		return "ActionZcSummonHpInit"
	case ActionZcSummonHpUpdate:
		return "ActionZcSummonHpUpdate"
	case ActionZcTalkboxChatcontents:
		return "ActionZcTalkboxChatcontents"
	case ActionZcTargetSpirits:
		return "ActionZcTargetSpirits"
	case ActionZcTrycaptureMonster:
		return "ActionZcTrycaptureMonster"
	case ActionZcUiOpen:
		return "ActionZcUiOpen"
	case ActionZcUiOpen2:
		return "ActionZcUiOpen2"
	case ActionZcUpdateCardslot:
		return "ActionZcUpdateCardslot"
	case ActionZcUpdateGdid:
		return "ActionZcUpdateGdid"
	case ActionZcUseskillAck:
		return "ActionZcUseskillAck"
	case ActionZcViewCamerainfo:
		return "ActionZcViewCamerainfo"
	case ActionZcWaitDialog:
		return "ActionZcWaitDialog"
	}
	return fmt.Sprintf("SemanticAction(%d)", uint16(a))
}
