// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// AccountServerInfo_0x0AC4 decodes a 0x0AC4 packet (struct PACKET_AC_ACCEPT_LOGIN).
func AccountServerInfo_0x0AC4(data []byte, packetver uint32) events.AccountServerInfo {
	var e events.AccountServerInfo
	if packetver >= 20170315 {
		e.PacketLength = leI16(data, 2)  // rAthena: packetLength (offset 2, size 2)
		e.Login_id1 = leU32(data, 4)  // rAthena: login_id1 (offset 4, size 4)
		e.AID = leU32(data, 8)  // rAthena: AID (offset 8, size 4)
		e.Login_id2 = leU32(data, 12)  // rAthena: login_id2 (offset 12, size 4)
		e.Last_ip = leU32(data, 16)  // rAthena: last_ip (offset 16, size 4)
		e.Last_login = nullTermString(data[20:46])  // rAthena: last_login (offset 20, size 26)
		e.Sex = data[46]  // rAthena: sex (offset 46, size 1)
		e.Token = nullTermString(data[47:64])  // rAthena: token (offset 47, size 17)
		e.Char_servers = data[64:]  // rAthena: char_servers (offset 64, size 0)
	} else {
		e.PacketLength = leI16(data, 2)  // rAthena: packetLength (offset 2, size 2)
		e.Login_id1 = leU32(data, 4)  // rAthena: login_id1 (offset 4, size 4)
		e.AID = leU32(data, 8)  // rAthena: AID (offset 8, size 4)
		e.Login_id2 = leU32(data, 12)  // rAthena: login_id2 (offset 12, size 4)
		e.Last_ip = leU32(data, 16)  // rAthena: last_ip (offset 16, size 4)
		e.Last_login = nullTermString(data[20:46])  // rAthena: last_login (offset 20, size 26)
		e.Sex = data[46]  // rAthena: sex (offset 46, size 1)
		e.Char_servers = data[47:]  // rAthena: char_servers (offset 47, size 0)
	}
	return e
}

