// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// AccountServerInfo_0x0AC4 decodes a 0x0AC4 packet (struct PACKET_AC_ACCEPT_LOGIN).
func AccountServerInfo_0x0AC4(data []byte, packetver uint32) events.AccountServerInfo {
	var e events.AccountServerInfo
	if packetver >= 20170315 {
		e.AccountID = leU32(data, 8)  // rAthena: AID (offset 8, size 4)
		e.ServerInfo = data[64:]  // rAthena: char_servers (offset 64, size 0)
		e.LastLoginIP = leU32(data, 16)  // rAthena: last_ip (offset 16, size 4)
		// e.LastLoginTime = nullTermString(packet.last_login[:])  (complex expression — implement manually)
		e.SessionID = leU32(data, 4)  // rAthena: login_id1 (offset 4, size 4)
		e.SessionID2 = leU32(data, 12)  // rAthena: login_id2 (offset 12, size 4)
		e.AccountSex = data[46]  // rAthena: sex (offset 46, size 1)
		// e.WebAuthToken = zero (field absent/defaulted in this version)
	} else {
		e.AccountID = leU32(data, 8)  // rAthena: AID (offset 8, size 4)
		e.ServerInfo = data[47:]  // rAthena: char_servers (offset 47, size 0)
		e.LastLoginIP = leU32(data, 16)  // rAthena: last_ip (offset 16, size 4)
		// e.LastLoginTime = nullTermString(packet.last_login[:])  (complex expression — implement manually)
		e.SessionID = leU32(data, 4)  // rAthena: login_id1 (offset 4, size 4)
		e.SessionID2 = leU32(data, 12)  // rAthena: login_id2 (offset 12, size 4)
		e.AccountSex = data[46]  // rAthena: sex (offset 46, size 1)
		// e.WebAuthToken = zero (field absent/defaulted in this version)
	}
	return e
}

