// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// AccountId_0x0283 decodes a 0x0283 packet (struct SYNTH_ZC_AID).
func AccountId_0x0283(data []byte, packetver uint32) events.AccountId {
	var e events.AccountId
	_ = packetver
	e.AID = leU32(data, 2)  // rAthena: AID (offset 2, size 4)
	return e
}

