// Code generated by internal/codegen. DO NOT EDIT.

package decode

// SKIP ActorAction_0x008A: struct PACKET_ZC_NOTIFY_ACT not found in VersionTable

// SKIP ActorAction_0x08C8: struct PACKET_ZC_NOTIFY_ACT not found in VersionTable

