// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// AreaSpell_0x011F decodes a 0x011F packet (struct packet_skill_entry).
func AreaSpell_0x011F(data []byte, packetver uint32) events.AreaSpell {
	var e events.AreaSpell
	if packetver >= 20130731 {
		e.ID = leU32(data, 4)  // rAthena: AID (offset 4, size 4)
		e.SourceID = leU32(data, 8)  // rAthena: creatorAID (offset 8, size 4)
		e.IsVisible = data[21]  // rAthena: isVisible (offset 21, size 1)
		e.Type = data[16]  // rAthena: job (offset 16, size 4)
		e.X = leI16(data, 12)  // rAthena: xPos (offset 12, size 2)
		e.Y = leI16(data, 14)  // rAthena: yPos (offset 14, size 2)
	} else if packetver >= 20121212 {
		e.ID = leU32(data, 4)  // rAthena: AID (offset 4, size 4)
		e.SourceID = leU32(data, 8)  // rAthena: creatorAID (offset 8, size 4)
		e.IsVisible = data[21]  // rAthena: isVisible (offset 21, size 1)
		e.Type = data[16]  // rAthena: job (offset 16, size 4)
		e.X = leI16(data, 12)  // rAthena: xPos (offset 12, size 2)
		e.Y = leI16(data, 14)  // rAthena: yPos (offset 14, size 2)
	} else if packetver >= 20110718 {
		e.ID = leU32(data, 4)  // rAthena: AID (offset 4, size 4)
		e.SourceID = leU32(data, 8)  // rAthena: creatorAID (offset 8, size 4)
		e.IsVisible = data[18]  // rAthena: isVisible (offset 18, size 1)
		e.Type = data[16]  // rAthena: job (offset 16, size 1)
		e.X = leI16(data, 12)  // rAthena: xPos (offset 12, size 2)
		e.Y = leI16(data, 14)  // rAthena: yPos (offset 14, size 2)
	} else {
		e.ID = leU32(data, 2)  // rAthena: AID (offset 2, size 4)
		e.SourceID = leU32(data, 6)  // rAthena: creatorAID (offset 6, size 4)
		e.IsVisible = data[15]  // rAthena: isVisible (offset 15, size 1)
		e.Type = data[14]  // rAthena: job (offset 14, size 1)
		e.X = leI16(data, 10)  // rAthena: xPos (offset 10, size 2)
		e.Y = leI16(data, 12)  // rAthena: yPos (offset 12, size 2)
	}
	return e
}

