// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// CharCreated_0x006D decodes a 0x006D packet (struct PACKET_HC_ACCEPT_MAKECHAR).
func CharCreated_0x006D(data []byte, packetver uint32) events.CharCreated {
	var e events.CharCreated
	_ = packetver
	return e
}

// CharCreated_0x0B6F decodes a 0x0B6F packet (struct PACKET_HC_ACCEPT_MAKECHAR).
func CharCreated_0x0B6F(data []byte, packetver uint32) events.CharCreated {
	var e events.CharCreated
	_ = packetver
	return e
}
