// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// CzAckAnswerMacroDetector_0x0A5C decodes a 0x0A5C packet (struct PACKET_CZ_ACK_ANSWER_MACRO_DETECTOR).
func CzAckAnswerMacroDetector_0x0A5C(data []byte, packetver uint32) events.CzAckAnswerMacroDetector {
	var e events.CzAckAnswerMacroDetector
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
	// e.Answer = func() [16]byte { var arr [16]byte; copy(arr[:], []byte(packet.answer)); return arr }()  (complex expression — implement manually)
	return e
}

