// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// CzCloseReformUi_0x0B90 decodes a 0x0B90 packet (struct PACKET_CZ_CLOSE_REFORM_UI).
func CzCloseReformUi_0x0B90(data []byte, packetver uint32) events.CzCloseReformUi {
	var e events.CzCloseReformUi
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
	return e
}

