// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// CzClientVersion_0x044A decodes a 0x044A packet (struct PACKET_CZ_CLIENT_VERSION).
func CzClientVersion_0x044A(data []byte, packetver uint32) events.CzClientVersion {
	var e events.CzClientVersion
	_ = packetver
	e.ClientVersion = leU32(data, 2)  // rAthena: clientVersion (offset 2, size 4)
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	return e
}

