// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// CzCloseRefiningUi_0x0AA4 decodes a 0x0AA4 packet (struct PACKET_CZ_CLOSE_REFINING_UI).
func CzCloseRefiningUi_0x0AA4(data []byte, packetver uint32) events.CzCloseRefiningUi {
	var e events.CzCloseRefiningUi
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	return e
}

