// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// CzCompleteApplyMacroDetectorCaptcha_0x0A5A decodes a 0x0A5A packet (struct PACKET_CZ_COMPLETE_APPLY_MACRO_DETECTOR_CAPTCHA).
func CzCompleteApplyMacroDetectorCaptcha_0x0A5A(data []byte, packetver uint32) events.CzCompleteApplyMacroDetectorCaptcha {
	var e events.CzCompleteApplyMacroDetectorCaptcha
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
	return e
}

