// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// CzGradeEnchantCloseUi_0x0B5C decodes a 0x0B5C packet (struct PACKET_CZ_GRADE_ENCHANT_CLOSE_UI).
func CzGradeEnchantCloseUi_0x0B5C(data []byte, packetver uint32) events.CzGradeEnchantCloseUi {
	var e events.CzGradeEnchantCloseUi
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
	return e
}

