// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// CzGradeEnchantSelectEquipment_0x0B59 decodes a 0x0B59 packet (struct PACKET_CZ_GRADE_ENCHANT_SELECT_EQUIPMENT).
func CzGradeEnchantSelectEquipment_0x0B59(data []byte, packetver uint32) events.CzGradeEnchantSelectEquipment {
	var e events.CzGradeEnchantSelectEquipment
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
	e.Index = leI16(data, 2)  // rAthena: index (offset 2, size 2)
	return e
}

