// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// CzItemReform_0x0B91 decodes a 0x0B91 packet (struct PACKET_CZ_ITEM_REFORM).
func CzItemReform_0x0B91(data []byte, packetver uint32) events.CzItemReform {
	var e events.CzItemReform
	_ = packetver
	e.ITID = leI32(data, 2)  // rAthena: ITID (offset 2, size 4)
	e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
	e.Index = leI16(data, 6)  // rAthena: index (offset 6, size 2)
	return e
}

