// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// CzNpcExpandedBarterMarketClose_0x0B58 decodes a 0x0B58 packet (struct PACKET_CZ_NPC_EXPANDED_BARTER_MARKET_CLOSE).
func CzNpcExpandedBarterMarketClose_0x0B58(data []byte, packetver uint32) events.CzNpcExpandedBarterMarketClose {
	var e events.CzNpcExpandedBarterMarketClose
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	return e
}

