// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// CzPcPurchaseItemlistFrommc_0x0134 decodes a 0x0134 packet (struct PACKET_CZ_PC_PURCHASE_ITEMLIST_FROMMC).
func CzPcPurchaseItemlistFrommc_0x0134(data []byte, packetver uint32) events.CzPcPurchaseItemlistFrommc {
	var e events.CzPcPurchaseItemlistFrommc
	_ = packetver
	e.AID = leU32(data, 4)  // rAthena: AID (offset 4, size 4)
	e.List = data[8:]  // rAthena: list (offset 8, size 0)
	e.PacketLength = leI16(data, 2)  // rAthena: packetLength (offset 2, size 2)
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	return e
}

