// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// CzPcPurchaseItemlistFrommc2_0x0801 decodes a 0x0801 packet (struct PACKET_CZ_PC_PURCHASE_ITEMLIST_FROMMC2).
func CzPcPurchaseItemlistFrommc2_0x0801(data []byte, packetver uint32) events.CzPcPurchaseItemlistFrommc2 {
	var e events.CzPcPurchaseItemlistFrommc2
	_ = packetver
	e.AID = leU32(data, 4)  // rAthena: AID (offset 4, size 4)
	e.UniqueID = leU32(data, 8)  // rAthena: UniqueID (offset 8, size 4)
	e.List = data[12:]  // rAthena: list (offset 12, size 0)
	e.PacketLength = leI16(data, 2)  // rAthena: packetLength (offset 2, size 2)
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	return e
}

