// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// CzPingLive_0x0B1C decodes a 0x0B1C packet (struct PACKET_CZ_PING_LIVE).
func CzPingLive_0x0B1C(data []byte, packetver uint32) events.CzPingLive {
	var e events.CzPingLive
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	return e
}

