// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// CzReqOpenMsgboxExtendBodyitemSize_0x0B14 decodes a 0x0B14 packet (struct PACKET_CZ_REQ_OPEN_MSGBOX_EXTEND_BODYITEM_SIZE).
func CzReqOpenMsgboxExtendBodyitemSize_0x0B14(data []byte, packetver uint32) events.CzReqOpenMsgboxExtendBodyitemSize {
	var e events.CzReqOpenMsgboxExtendBodyitemSize
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	return e
}

