// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// CzReqPlayerAidInRange_0x0A6C decodes a 0x0A6C packet (struct PACKET_CZ_REQ_PLAYER_AID_IN_RANGE).
func CzReqPlayerAidInRange_0x0A6C(data []byte, packetver uint32) events.CzReqPlayerAidInRange {
	var e events.CzReqPlayerAidInRange
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
	e.RadiusRange = int8(data[6])  // rAthena: RadiusRange (offset 6, size 1)
	e.XPos = leI16(data, 2)  // rAthena: xPos (offset 2, size 2)
	e.YPos = leI16(data, 4)  // rAthena: yPos (offset 4, size 2)
	return e
}

