// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// CzRequestResetEnchant_0x0B9E decodes a 0x0B9E packet (struct PACKET_CZ_REQUEST_RESET_ENCHANT).
func CzRequestResetEnchant_0x0B9E(data []byte, packetver uint32) events.CzRequestResetEnchant {
	var e events.CzRequestResetEnchant
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
	e.EnchantGroup = leI64(data, 2)  // rAthena: enchant_group (offset 2, size 8)
	e.Index = leI16(data, 10)  // rAthena: index (offset 10, size 2)
	return e
}

