// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// CzRandomUpgradeItemUiClose_0x0AB5 decodes a 0x0AB5 packet (struct PACKET_CZ_RANDOM_UPGRADE_ITEM_UI_CLOSE).
func CzRandomUpgradeItemUiClose_0x0AB5(data []byte, packetver uint32) events.CzRandomUpgradeItemUiClose {
	var e events.CzRandomUpgradeItemUiClose
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	return e
}

