// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// CzReqItemrepair2_0x0B66 decodes a 0x0B66 packet (struct PACKET_CZ_REQ_ITEMREPAIR2).
func CzReqItemrepair2_0x0B66(data []byte, packetver uint32) events.CzReqItemrepair2 {
	var e events.CzReqItemrepair2
	_ = packetver
	// e.Item = []byte{}  (complex expression — implement manually)
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	return e
}

