// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// CzReqItemrepair1_0x01FD decodes a 0x01FD packet (struct PACKET_CZ_REQ_ITEMREPAIR1).
func CzReqItemrepair1_0x01FD(data []byte, packetver uint32) events.CzReqItemrepair1 {
	var e events.CzReqItemrepair1
	if packetver >= 20181121 {
		// e.Item = []byte{}  (complex expression — implement manually)
		e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	} else {
		// e.Item = []byte{}  (complex expression — implement manually)
		e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	}
	return e
}

