// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// CzReqRandomUpgradeItem_0x0AB6 decodes a 0x0AB6 packet (struct PACKET_CZ_REQ_RANDOM_UPGRADE_ITEM).
func CzReqRandomUpgradeItem_0x0AB6(data []byte, packetver uint32) events.CzReqRandomUpgradeItem {
	var e events.CzReqRandomUpgradeItem
	if packetver >= 20181121 {
		e.Index = leU16(data, 6)  // rAthena: index (offset 6, size 2)
		e.ItemId = leU32(data, 2)  // rAthena: itemId (offset 2, size 4)
		e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	} else {
		e.Index = leU16(data, 4)  // rAthena: index (offset 4, size 2)
		e.ItemId = uint32(leU16(data, 2))  // rAthena: itemId (offset 2, size 2)
		e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	}
	return e
}

