// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// CzReqRemaintime_0x01C0 decodes a 0x01C0 packet (struct PACKET_CZ_REQ_REMAINTIME).
func CzReqRemaintime_0x01C0(data []byte, packetver uint32) events.CzReqRemaintime {
	var e events.CzReqRemaintime
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	return e
}

