// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// CzSeCashshopOpen1_0x0844 decodes a 0x0844 packet (struct PACKET_CZ_SE_CASHSHOP_OPEN1).
func CzSeCashshopOpen1_0x0844(data []byte, packetver uint32) events.CzSeCashshopOpen1 {
	var e events.CzSeCashshopOpen1
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	return e
}

