// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// CzShortcutKeyChange1_0x02BA decodes a 0x02BA packet (struct PACKET_CZ_SHORTCUT_KEY_CHANGE1).
func CzShortcutKeyChange1_0x02BA(data []byte, packetver uint32) events.CzShortcutKeyChange1 {
	var e events.CzShortcutKeyChange1
	_ = packetver
	// e.Hotkey = func() []byte { bytes, _ := packet.hotkey.ToPacket(0); if len(bytes) > 2 { return bytes[2:] }; return []byte{} }()  (complex expression — implement manually)
	e.Index = leU16(data, 2)  // rAthena: index (offset 2, size 2)
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	return e
}

