// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// CzShortcutKeyChange2_0x0B21 decodes a 0x0B21 packet (struct PACKET_CZ_SHORTCUT_KEY_CHANGE2).
func CzShortcutKeyChange2_0x0B21(data []byte, packetver uint32) events.CzShortcutKeyChange2 {
	var e events.CzShortcutKeyChange2
	_ = packetver
	// e.Hotkey = func() []byte { bytes, _ := packet.Hotkey.ToPacket(0); if len(bytes) > 2 { return bytes[2:] }; return []byte{} }()  (complex expression — implement manually)
	e.Index = leU16(data, 4)  // rAthena: index (offset 4, size 2)
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	e.Tab = leU16(data, 2)  // rAthena: tab (offset 2, size 2)
	return e
}

