// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// CzViewCamerainfo_0x0A77 decodes a 0x0A77 packet (struct PACKET_CZ_VIEW_CAMERAINFO).
func CzViewCamerainfo_0x0A77(data []byte, packetver uint32) events.CzViewCamerainfo {
	var e events.CzViewCamerainfo
	_ = packetver
	e.Action = int8(data[2])  // rAthena: action (offset 2, size 1)
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	return e
}

