// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// EntitySpawn_0x007C decodes a 0x007C packet (struct packet_spawn_unit2).
func EntitySpawn_0x007C(data []byte, packetver uint32) events.EntitySpawn {
	var e events.EntitySpawn
	if packetver >= 20071106 {
		e.Objecttype = data[2]          // rAthena: objecttype (offset 2, size 1)
		e.GID = leU32(data, 3)          // rAthena: GID (offset 3, size 4)
		e.Speed = leI16(data, 7)        // rAthena: speed (offset 7, size 2)
		e.BodyState = leI16(data, 9)    // rAthena: bodyState (offset 9, size 2)
		e.HealthState = leI16(data, 11) // rAthena: healthState (offset 11, size 2)
		e.EffectState = leI16(data, 13) // rAthena: effectState (offset 13, size 2)
		e.Head = leU16(data, 15)        // rAthena: head (offset 15, size 2)
		e.Weapon = leU16(data, 17)      // rAthena: weapon (offset 17, size 2)
		e.Accessory = leU16(data, 19)   // rAthena: accessory (offset 19, size 2)
		e.Job = leI16(data, 21)         // rAthena: job (offset 21, size 2)
		e.Shield = leU16(data, 23)      // rAthena: shield (offset 23, size 2)
		e.Accessory2 = leU16(data, 25)  // rAthena: accessory2 (offset 25, size 2)
		e.Accessory3 = leU16(data, 27)  // rAthena: accessory3 (offset 27, size 2)
		e.Headpalette = leI16(data, 29) // rAthena: headpalette (offset 29, size 2)
		e.Bodypalette = leI16(data, 31) // rAthena: bodypalette (offset 31, size 2)
		e.HeadDir = leI16(data, 33)     // rAthena: headDir (offset 33, size 2)
		e.IsPKModeON = data[35]         // rAthena: isPKModeON (offset 35, size 1)
		e.Sex = data[36]                // rAthena: sex (offset 36, size 1)
		e.PosDir = [3]byte(data[37:40]) // rAthena: PosDir (offset 37, size 3)
		e.XSize = data[40]              // rAthena: xSize (offset 40, size 1)
		e.YSize = data[41]              // rAthena: ySize (offset 41, size 1)
	} else {
		e.GID = leU32(data, 2)          // rAthena: GID (offset 2, size 4)
		e.Speed = leI16(data, 6)        // rAthena: speed (offset 6, size 2)
		e.BodyState = leI16(data, 8)    // rAthena: bodyState (offset 8, size 2)
		e.HealthState = leI16(data, 10) // rAthena: healthState (offset 10, size 2)
		e.EffectState = leI16(data, 12) // rAthena: effectState (offset 12, size 2)
		e.Head = leU16(data, 14)        // rAthena: head (offset 14, size 2)
		e.Weapon = leU16(data, 16)      // rAthena: weapon (offset 16, size 2)
		e.Accessory = leU16(data, 18)   // rAthena: accessory (offset 18, size 2)
		e.Job = leI16(data, 20)         // rAthena: job (offset 20, size 2)
		e.Shield = leU16(data, 22)      // rAthena: shield (offset 22, size 2)
		e.Accessory2 = leU16(data, 24)  // rAthena: accessory2 (offset 24, size 2)
		e.Accessory3 = leU16(data, 26)  // rAthena: accessory3 (offset 26, size 2)
		e.Headpalette = leI16(data, 28) // rAthena: headpalette (offset 28, size 2)
		e.Bodypalette = leI16(data, 30) // rAthena: bodypalette (offset 30, size 2)
		e.HeadDir = leI16(data, 32)     // rAthena: headDir (offset 32, size 2)
		e.IsPKModeON = data[34]         // rAthena: isPKModeON (offset 34, size 1)
		e.Sex = data[35]                // rAthena: sex (offset 35, size 1)
		e.PosDir = [3]byte(data[36:39]) // rAthena: PosDir (offset 36, size 3)
		e.XSize = data[39]              // rAthena: xSize (offset 39, size 1)
		e.YSize = data[40]              // rAthena: ySize (offset 40, size 1)
	}
	return e
}
