// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// EntitySpawn_0x007C decodes a 0x007C packet (struct packet_spawn_unit2).
func EntitySpawn_0x007C(data []byte, packetver uint32) events.EntitySpawn {
	var e events.EntitySpawn
	if packetver >= 20071106 {
		e.EntityID = leU32(data, 3)  // rAthena: GID (offset 3, size 4)
		e.EntityType = leU16(data, 21)  // rAthena: job (offset 21, size 2)
		e.PosDir = [3]byte(data[37:40])  // rAthena: PosDir (offset 37, size 3)
	} else {
		e.EntityID = leU32(data, 2)  // rAthena: GID (offset 2, size 4)
		e.EntityType = leU16(data, 20)  // rAthena: job (offset 20, size 2)
		e.PosDir = [3]byte(data[36:39])  // rAthena: PosDir (offset 36, size 3)
	}
	return e
}

