// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// Exp_0x07F6 decodes a 0x07F6 packet (struct SYNTH_ZC_LONG_PAR_CHANGE).
func Exp_0x07F6(data []byte, packetver uint32) events.Exp {
	var e events.Exp
	_ = packetver
	e.Aid = leU32(data, 2)  // rAthena: aid (offset 2, size 4)
	e.Exp = uint64(leU32(data, 6))  // rAthena: exp (offset 6, size 4)
	e.Type = leU16(data, 10)  // rAthena: type (offset 10, size 2)
	e.Quest = leU16(data, 12)  // rAthena: quest (offset 12, size 2)
	return e
}

// Exp_0x0ACC decodes a 0x0ACC packet (struct SYNTH_ZC_LONG_PAR_CHANGE2).
func Exp_0x0ACC(data []byte, packetver uint32) events.Exp {
	var e events.Exp
	_ = packetver
	e.Aid = leU32(data, 2)  // rAthena: aid (offset 2, size 4)
	e.Exp = leU64(data, 6)  // rAthena: exp (offset 6, size 8)
	e.Type = leU16(data, 14)  // rAthena: type (offset 14, size 2)
	e.Quest = leU16(data, 16)  // rAthena: quest (offset 16, size 2)
	return e
}

