// Code generated by internal/codegen. DO NOT EDIT.

package decode

// SKIP GameLogin_0x0065: struct PACKET_CH_ENTER_0x0065 not found in VersionTable

// SKIP GameLogin_0x0275: struct PACKET_CH_ENTER not found in VersionTable

