// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// InventoryItemsEquip_0x00A4 decodes a 0x00A4 packet (struct packet_itemlist_equip).
func InventoryItemsEquip_0x00A4(data []byte, packetver uint32) events.InventoryItemsEquip {
	var e events.InventoryItemsEquip
	_ = packetver
	e.PacketLength = leI16(data, 2)  // rAthena: PacketLength (offset 2, size 2)
	e.List = data[4:]  // rAthena: list (offset 4, size 0)
	return e
}

// InventoryItemsEquip_0x0992 decodes a 0x0992 packet (struct packet_itemlist_equip).
func InventoryItemsEquip_0x0992(data []byte, packetver uint32) events.InventoryItemsEquip {
	var e events.InventoryItemsEquip
	_ = packetver
	e.PacketLength = leI16(data, 2)  // rAthena: PacketLength (offset 2, size 2)
	e.List = data[4:]  // rAthena: list (offset 4, size 0)
	return e
}

// InventoryItemsEquip_0x0A0D decodes a 0x0A0D packet (struct packet_itemlist_equip).
func InventoryItemsEquip_0x0A0D(data []byte, packetver uint32) events.InventoryItemsEquip {
	var e events.InventoryItemsEquip
	_ = packetver
	e.PacketLength = leI16(data, 2)  // rAthena: PacketLength (offset 2, size 2)
	e.List = data[4:]  // rAthena: list (offset 4, size 0)
	return e
}

// InventoryItemsEquip_0x0B0A decodes a 0x0B0A packet (struct packet_itemlist_equip).
func InventoryItemsEquip_0x0B0A(data []byte, packetver uint32) events.InventoryItemsEquip {
	var e events.InventoryItemsEquip
	_ = packetver
	e.PacketLength = leI16(data, 2)  // rAthena: PacketLength (offset 2, size 2)
	e.InvType = data[4]  // rAthena: invType (offset 4, size 1)
	e.List = data[5:]  // rAthena: list (offset 5, size 0)
	return e
}

// InventoryItemsEquip_0x0B39 decodes a 0x0B39 packet (struct packet_itemlist_equip).
func InventoryItemsEquip_0x0B39(data []byte, packetver uint32) events.InventoryItemsEquip {
	var e events.InventoryItemsEquip
	_ = packetver
	e.PacketLength = leI16(data, 2)  // rAthena: PacketLength (offset 2, size 2)
	e.InvType = data[4]  // rAthena: invType (offset 4, size 1)
	e.List = data[5:]  // rAthena: list (offset 5, size 0)
	return e
}

