// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ItemAppeared_0x009E decodes a 0x009E packet (struct packet_dropflooritem).
func ItemAppeared_0x009E(data []byte, packetver uint32) events.ItemAppeared {
	var e events.ItemAppeared
	if packetver >= 20181121 {
		e.ID = leU32(data, 2)  // rAthena: ITAID (offset 2, size 4)
		e.ItemID = leU16(data, 6)  // rAthena: ITID (offset 6, size 4)
		e.Identified = data[12]  // rAthena: IsIdentified (offset 12, size 1)
		e.X = leU16(data, 13)  // rAthena: xPos (offset 13, size 2)
		e.Y = leU16(data, 15)  // rAthena: yPos (offset 15, size 2)
		e.Subx = data[17]  // rAthena: subX (offset 17, size 1)
		e.Suby = data[18]  // rAthena: subY (offset 18, size 1)
		e.Amount = leU16(data, 19)  // rAthena: count (offset 19, size 2)
	} else if packetver >= 20180511 {
		e.ID = leU32(data, 2)  // rAthena: ITAID (offset 2, size 4)
		e.ItemID = leU16(data, 6)  // rAthena: ITID (offset 6, size 2)
		e.Identified = data[10]  // rAthena: IsIdentified (offset 10, size 1)
		e.X = leU16(data, 11)  // rAthena: xPos (offset 11, size 2)
		e.Y = leU16(data, 13)  // rAthena: yPos (offset 13, size 2)
		e.Subx = data[15]  // rAthena: subX (offset 15, size 1)
		e.Suby = data[16]  // rAthena: subY (offset 16, size 1)
		e.Amount = leU16(data, 17)  // rAthena: count (offset 17, size 2)
	} else if packetver >= 20130000 {
		e.ID = leU32(data, 2)  // rAthena: ITAID (offset 2, size 4)
		e.ItemID = leU16(data, 6)  // rAthena: ITID (offset 6, size 2)
		e.Identified = data[10]  // rAthena: IsIdentified (offset 10, size 1)
		e.X = leU16(data, 11)  // rAthena: xPos (offset 11, size 2)
		e.Y = leU16(data, 13)  // rAthena: yPos (offset 13, size 2)
		e.Subx = data[15]  // rAthena: subX (offset 15, size 1)
		e.Suby = data[16]  // rAthena: subY (offset 16, size 1)
		e.Amount = leU16(data, 17)  // rAthena: count (offset 17, size 2)
	} else {
		e.ID = leU32(data, 2)  // rAthena: ITAID (offset 2, size 4)
		e.ItemID = leU16(data, 6)  // rAthena: ITID (offset 6, size 2)
		e.Identified = data[8]  // rAthena: IsIdentified (offset 8, size 1)
		e.X = leU16(data, 9)  // rAthena: xPos (offset 9, size 2)
		e.Y = leU16(data, 11)  // rAthena: yPos (offset 11, size 2)
		e.Subx = data[13]  // rAthena: subX (offset 13, size 1)
		e.Suby = data[14]  // rAthena: subY (offset 14, size 1)
		e.Amount = leU16(data, 15)  // rAthena: count (offset 15, size 2)
	}
	return e
}

