// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ItemPickup_0x00A0 decodes a 0x00A0 packet (struct PACKET_ZC_ITEM_PICKUP_ACK).
func ItemPickup_0x00A0(data []byte, packetver uint32) events.ItemPickup {
	var e events.ItemPickup
	if packetver >= 20160921 {
		e.ItemID = uint32(leU16(data, 6))  // rAthena: nameid (offset 6, size 2)
		e.Index = leU16(data, 2)  // rAthena: Index (offset 2, size 2)
		e.Amount = leU16(data, 4)  // rAthena: count (offset 4, size 2)
		// e.IsIdentified = packet.IsIdentified != 0  (complex expression — implement manually)
		e.Result = data[24]  // rAthena: result (offset 24, size 1)
	} else if packetver >= 20150226 {
		e.ItemID = uint32(leU16(data, 6))  // rAthena: nameid (offset 6, size 2)
		e.Index = leU16(data, 2)  // rAthena: Index (offset 2, size 2)
		e.Amount = leU16(data, 4)  // rAthena: count (offset 4, size 2)
		// e.IsIdentified = packet.IsIdentified != 0  (complex expression — implement manually)
		e.Result = data[24]  // rAthena: result (offset 24, size 1)
	} else if packetver >= 20120925 {
		e.ItemID = uint32(leU16(data, 6))  // rAthena: nameid (offset 6, size 2)
		e.Index = leU16(data, 2)  // rAthena: Index (offset 2, size 2)
		e.Amount = leU16(data, 4)  // rAthena: count (offset 4, size 2)
		// e.IsIdentified = packet.IsIdentified != 0  (complex expression — implement manually)
		e.Result = data[24]  // rAthena: result (offset 24, size 1)
	} else if packetver >= 20071002 {
		e.ItemID = uint32(leU16(data, 6))  // rAthena: nameid (offset 6, size 2)
		e.Index = leU16(data, 2)  // rAthena: Index (offset 2, size 2)
		e.Amount = leU16(data, 4)  // rAthena: count (offset 4, size 2)
		// e.IsIdentified = packet.IsIdentified != 0  (complex expression — implement manually)
		e.Result = data[22]  // rAthena: result (offset 22, size 1)
	} else if packetver >= 20061218 {
		e.ItemID = uint32(leU16(data, 6))  // rAthena: nameid (offset 6, size 2)
		e.Index = leU16(data, 2)  // rAthena: Index (offset 2, size 2)
		e.Amount = leU16(data, 4)  // rAthena: count (offset 4, size 2)
		// e.IsIdentified = packet.IsIdentified != 0  (complex expression — implement manually)
		e.Result = data[22]  // rAthena: result (offset 22, size 1)
	} else {
		e.ItemID = uint32(leU16(data, 6))  // rAthena: nameid (offset 6, size 2)
		e.Index = leU16(data, 2)  // rAthena: Index (offset 2, size 2)
		e.Amount = leU16(data, 4)  // rAthena: count (offset 4, size 2)
		// e.IsIdentified = packet.IsIdentified != 0  (complex expression — implement manually)
		e.Result = data[22]  // rAthena: result (offset 22, size 1)
	}
	return e
}

// SKIP ItemPickup_0x0A37: struct PACKET_ZC_ITEM_PICKUP_ACK_V7 not found in VersionTable

