// Code generated by internal/codegen. DO NOT EDIT.

package decode

// SKIP MapLoaded_0x02EB: struct PACKET_ZC_ACCEPT_ENTER not found in VersionTable

// SKIP MapLoaded_0x007D: struct PACKET_CZ_NOTIFY_ACTORINIT not found in VersionTable

