// Code generated by internal/codegen. DO NOT EDIT.

package decode

// SKIP MapChanged_0x0091: struct PACKET_ZC_NPCACK_MAPMOVE not found in VersionTable

// SKIP MapChanged_0x0AC7: struct PACKET_ZC_NPCACK_SERVERMOVE not found in VersionTable

