// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// MarketPurchase_0x0134 decodes a 0x0134 packet (struct PACKET_CZ_NPC_MARKET_PURCHASE).
func MarketPurchase_0x0134(data []byte, packetver uint32) events.MarketPurchase {
	var e events.MarketPurchase
	_ = packetver
	e.ItemList = data[4:]  // rAthena: list (offset 4, size 0)
	return e
}

