// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// MonsterHpUpdate_0x0977 decodes a 0x0977 packet (struct packet_monster_hp).
func MonsterHpUpdate_0x0977(data []byte, packetver uint32) events.MonsterHpUpdate {
	var e events.MonsterHpUpdate
	_ = packetver
	e.GID = leU32(data, 2)    // rAthena: GID (offset 2, size 4)
	e.HP = leI32(data, 6)     // rAthena: HP (offset 6, size 4)
	e.MaxHP = leI32(data, 10) // rAthena: MaxHP (offset 10, size 4)
	return e
}
