// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// MoveTo_0x0085 decodes a 0x0085 packet (struct SYNTH_CZ_REQUEST_MOVE).
func MoveTo_0x0085(data []byte, packetver uint32) events.MoveTo {
	var e events.MoveTo
	_ = packetver
	e.Coords = [3]byte(data[2:5])  // rAthena: PosDir (offset 2, size 3)
	return e
}

// MoveTo_0x0437 decodes a 0x0437 packet (struct SYNTH_CZ_REQUEST_MOVE2).
func MoveTo_0x0437(data []byte, packetver uint32) events.MoveTo {
	var e events.MoveTo
	_ = packetver
	e.Coords = [3]byte(data[2:5])  // rAthena: dest (offset 2, size 3)
	return e
}

