// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// PetEggList_0x01A6 decodes a 0x01A6 packet (struct SYNTH_ZC_PETEGG_LIST).
func PetEggList_0x01A6(data []byte, packetver uint32) events.PetEggList {
	var e events.PetEggList
	_ = packetver
	e.InventoryIndices = func() []int16 { d := data[4:]; r := make([]int16, len(d)/2); for i := range r { r[i] = leI16(d, i*2) }; return r }()  // rAthena: eggs (offset 4, size 0)
	return e
}

