// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// PublicChat_0x008D decodes a 0x008D packet (struct PACKET_ZC_NOTIFY_CHAT).
func PublicChat_0x008D(data []byte, packetver uint32) events.PublicChat {
	var e events.PublicChat
	_ = packetver
	// e.ID = &packet.GID  (complex expression — implement manually)
	// e.Message = &packet.Message  (complex expression — implement manually)
	return e
}

// SKIP PublicChat_0x008C: struct PACKET_CZ_REQUEST_CHAT not found in VersionTable

