// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// SelfChat_0x008E decodes a 0x008E packet (struct PACKET_ZC_NOTIFY_PLAYERCHAT).
func SelfChat_0x008E(data []byte, packetver uint32) events.SelfChat {
	var e events.SelfChat
	_ = packetver
	e.Message = nullTermString(data[4:])  // rAthena: Message (offset 4, size 0)
	return e
}

