// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ShopBuy_0x00C8 decodes a 0x00C8 packet (struct PACKET_CZ_PC_PURCHASE_ITEMLIST).
func ShopBuy_0x00C8(data []byte, packetver uint32) events.ShopBuy {
	var e events.ShopBuy
	_ = packetver
	e.ItemList = data[4:]  // rAthena: items (offset 4, size 0)
	return e
}

