// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// SkillUsedNoDamage_0x011A decodes a 0x011A packet (struct PACKET_ZC_USE_SKILL).
func SkillUsedNoDamage_0x011A(data []byte, packetver uint32) events.SkillUsedNoDamage {
	var e events.SkillUsedNoDamage
	if packetver >= 20130731 {
		e.SkillID = leU16(data, 2)  // rAthena: SKID (offset 2, size 2)
		e.Amount = leU16(data, 4)  // rAthena: level (offset 4, size 4)
		e.Success = data[16]  // rAthena: result (offset 16, size 1)
		e.SourceID = leU32(data, 12)  // rAthena: srcAID (offset 12, size 4)
		e.TargetID = leU32(data, 8)  // rAthena: targetAID (offset 8, size 4)
	} else {
		e.SkillID = leU16(data, 2)  // rAthena: SKID (offset 2, size 2)
		e.Amount = leU16(data, 4)  // rAthena: level (offset 4, size 2)
		e.Success = data[14]  // rAthena: result (offset 14, size 1)
		e.SourceID = leU32(data, 10)  // rAthena: srcAID (offset 10, size 4)
		e.TargetID = leU32(data, 6)  // rAthena: targetAID (offset 6, size 4)
	}
	return e
}

