// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// SkillAdd_0x0111 decodes a 0x0111 packet (struct PACKET_ZC_ADD_SKILL).
func SkillAdd_0x0111(data []byte, packetver uint32) events.SkillAdd {
	var e events.SkillAdd
	if packetver >= 20220216 {
		// e.Skill = serialization.SerializeSKILLDATA(packet.skill)  (complex expression — implement manually)
	} else if packetver >= 20200902 {
		// e.Skill = serialization.SerializeSKILLDATA(packet.skill)  (complex expression — implement manually)
	} else {
		// e.Skill = serialization.SerializeSKILLDATA(packet.skill)  (complex expression — implement manually)
	}
	return e
}

