// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// SkillsList_0x010F decodes a 0x010F packet (struct PACKET_ZC_SKILLINFO_LIST).
func SkillsList_0x010F(data []byte, packetver uint32) events.SkillsList {
	var e events.SkillsList
	_ = packetver
	e.PacketLength = leI16(data, 2)  // rAthena: packetLength (offset 2, size 2)
	e.Skills = data[4:]  // rAthena: skills (offset 4, size 0)
	return e
}

