// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// SkillUseFailed_0x0110 decodes a 0x0110 packet (struct PACKET_ZC_ACK_TOUSESKILL).
func SkillUseFailed_0x0110(data []byte, packetver uint32) events.SkillUseFailed {
	var e events.SkillUseFailed
	if packetver >= 20181121 {
		e.Btype = leU32(data, 4)  // rAthena: btype (offset 4, size 4)
		e.Cause = data[13]  // rAthena: cause (offset 13, size 1)
		e.Flag = data[12]  // rAthena: flag (offset 12, size 1)
		e.ItemId = leU16(data, 8)  // rAthena: itemId (offset 8, size 4)
		e.SkillID = leU16(data, 2)  // rAthena: skillId (offset 2, size 2)
	} else {
		e.Btype = uint32(leU16(data, 4))  // rAthena: btype (offset 4, size 2)
		e.Cause = data[9]  // rAthena: cause (offset 9, size 1)
		e.Flag = data[8]  // rAthena: flag (offset 8, size 1)
		e.ItemId = leU16(data, 6)  // rAthena: itemId (offset 6, size 2)
		e.SkillID = leU16(data, 2)  // rAthena: skillId (offset 2, size 2)
	}
	return e
}

