// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// SkillPostDelay_0x043D decodes a 0x043D packet (struct PACKET_ZC_SKILL_POSTDELAY).
func SkillPostDelay_0x043D(data []byte, packetver uint32) events.SkillPostDelay {
	var e events.SkillPostDelay
	_ = packetver
	e.Time = leU32(data, 4)  // rAthena: DelayTM (offset 4, size 4)
	e.ID = leU16(data, 2)  // rAthena: SKID (offset 2, size 2)
	return e
}

