// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// VenderFound_0x0131 decodes a 0x0131 packet (struct PACKET_ZC_STORE_ENTRY).
func VenderFound_0x0131(data []byte, packetver uint32) events.VenderFound {
	var e events.VenderFound
	_ = packetver
	e.MakerAID = leU32(data, 2)              // rAthena: makerAID (offset 2, size 4)
	e.StoreName = nullTermString(data[6:86]) // rAthena: storeName (offset 6, size 80)
	return e
}
