// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// VenderFound_0x0131 decodes a 0x0131 packet (struct PACKET_ZC_STORE_ENTRY).
func VenderFound_0x0131(data []byte, packetver uint32) events.VenderFound {
	var e events.VenderFound
	_ = packetver
	e.ID = leU32(data, 2)  // rAthena: makerAID (offset 2, size 4)
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	// e.Title = strings.TrimRight(packet.storeName, "\x00")  (complex expression — implement manually)
	return e
}

