// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// ZcAckApplyMacroDetector_0x0A57 decodes a 0x0A57 packet (struct PACKET_ZC_ACK_APPLY_MACRO_DETECTOR).
func ZcAckApplyMacroDetector_0x0A57(data []byte, packetver uint32) events.ZcAckApplyMacroDetector {
	var e events.ZcAckApplyMacroDetector
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
	return e
}

