// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// ZcAddItemToStore_0x00F4 decodes a 0x00F4 packet (struct PACKET_ZC_ADD_ITEM_TO_STORE).
func ZcAddItemToStore_0x00F4(data []byte, packetver uint32) events.ZcAddItemToStore {
	var e events.ZcAddItemToStore
	if packetver >= 20200902 {
		e.Amount = leI32(data, 4)  // rAthena: amount (offset 4, size 4)
		e.Damaged = data[14]  // rAthena: damaged (offset 14, size 1)
		e.Identified = data[13]  // rAthena: identified (offset 13, size 1)
		e.Index = leI16(data, 2)  // rAthena: index (offset 2, size 2)
		e.ItemId = leU32(data, 8)  // rAthena: itemId (offset 8, size 4)
		e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
		e.Refine = data[31]  // rAthena: refine (offset 31, size 1)
		// e.Slot = serialization.SerializeEQUIPSLOTINFO(packet.slot)  (complex expression — implement manually)
	} else if packetver >= 20181121 {
		e.Amount = leI32(data, 4)  // rAthena: amount (offset 4, size 4)
		e.Damaged = data[14]  // rAthena: damaged (offset 14, size 1)
		e.Identified = data[13]  // rAthena: identified (offset 13, size 1)
		e.Index = leI16(data, 2)  // rAthena: index (offset 2, size 2)
		e.ItemId = leU32(data, 8)  // rAthena: itemId (offset 8, size 4)
		e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
		e.Refine = data[15]  // rAthena: refine (offset 15, size 1)
		// e.Slot = serialization.SerializeEQUIPSLOTINFO(packet.slot)  (complex expression — implement manually)
	} else if packetver >= 20140813 {
		e.Amount = leI32(data, 4)  // rAthena: amount (offset 4, size 4)
		e.Damaged = data[12]  // rAthena: damaged (offset 12, size 1)
		e.Identified = data[11]  // rAthena: identified (offset 11, size 1)
		e.Index = leI16(data, 2)  // rAthena: index (offset 2, size 2)
		e.ItemId = uint32(leU16(data, 8))  // rAthena: itemId (offset 8, size 2)
		e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
		e.Refine = data[13]  // rAthena: refine (offset 13, size 1)
		// e.Slot = serialization.SerializeEQUIPSLOTINFO(packet.slot)  (complex expression — implement manually)
	} else {
		e.Amount = leI32(data, 4)  // rAthena: amount (offset 4, size 4)
		e.Damaged = data[12]  // rAthena: damaged (offset 12, size 1)
		e.Identified = data[11]  // rAthena: identified (offset 11, size 1)
		e.Index = leI16(data, 2)  // rAthena: index (offset 2, size 2)
		e.ItemId = uint32(leU16(data, 8))  // rAthena: itemId (offset 8, size 2)
		e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
		e.Refine = data[13]  // rAthena: refine (offset 13, size 1)
		// e.Slot = serialization.SerializeEQUIPSLOTINFO(packet.slot)  (complex expression — implement manually)
	}
	return e
}

