// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcAckCloseRoulette_0x0A1E decodes a 0x0A1E packet (struct PACKET_ZC_ACK_CLOSE_ROULETTE).
func ZcAckCloseRoulette_0x0A1E(data []byte, packetver uint32) events.ZcAckCloseRoulette {
	var e events.ZcAckCloseRoulette
	_ = packetver
	e.Result = data[2]  // rAthena: result (offset 2, size 1)
	return e
}

