// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// ZcAutorunSkill_0x0147 decodes a 0x0147 packet (struct PACKET_ZC_AUTORUN_SKILL).
func ZcAutorunSkill_0x0147(data []byte, packetver uint32) events.ZcAutorunSkill {
	var e events.ZcAutorunSkill
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	e.Skill_id = leU16(data, 2)  // rAthena: skill_id (offset 2, size 2)
	e.Skill_lv = leU16(data, 8)  // rAthena: skill_lv (offset 8, size 2)
	e.Skill_range = leU16(data, 12)  // rAthena: skill_range (offset 12, size 2)
	e.Skill_sp = leU16(data, 10)  // rAthena: skill_sp (offset 10, size 2)
	e.Skill_type = leU32(data, 4)  // rAthena: skill_type (offset 4, size 4)
	e.Up_flag = data[38]  // rAthena: up_flag (offset 38, size 1)
	// e.SkillName = string(packet.skill_name[:])  (complex expression — implement manually)
	return e
}

