// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcAckItemrepair_0x01FE decodes a 0x01FE packet (struct PACKET_ZC_ACK_ITEMREPAIR).
func ZcAckItemrepair_0x01FE(data []byte, packetver uint32) events.ZcAckItemrepair {
	var e events.ZcAckItemrepair
	_ = packetver
	e.Index = leU16(data, 2) // rAthena: index (offset 2, size 2)
	e.Result = data[4]       // rAthena: result (offset 4, size 1)
	return e
}
