// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcAckMergeItem_0x096F decodes a 0x096F packet (struct PACKET_ZC_ACK_MERGE_ITEM).
func ZcAckMergeItem_0x096F(data []byte, packetver uint32) events.ZcAckMergeItem {
	var e events.ZcAckMergeItem
	_ = packetver
	e.Amount = leI16(data, 4)  // rAthena: amount (offset 4, size 2)
	e.Index = leI16(data, 2)  // rAthena: index (offset 2, size 2)
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	e.Reason = data[6]  // rAthena: reason (offset 6, size 1)
	return e
}

