// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcApplyMacroDetectorCaptcha_0x0A59 decodes a 0x0A59 packet (struct PACKET_ZC_APPLY_MACRO_DETECTOR_CAPTCHA).
func ZcApplyMacroDetectorCaptcha_0x0A59(data []byte, packetver uint32) events.ZcApplyMacroDetectorCaptcha {
	var e events.ZcApplyMacroDetectorCaptcha
	_ = packetver
	e.PacketLength = leI16(data, 2)          // rAthena: PacketLength (offset 2, size 2)
	e.CaptchaKey = nullTermString(data[4:8]) // rAthena: captchaKey (offset 4, size 4)
	e.ImageData = nullTermString(data[8:])   // rAthena: imageData (offset 8, size 0)
	return e
}
