// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcAckReqnameallNpc_0x0095 decodes a 0x0095 packet (struct PACKET_ZC_ACK_REQNAMEALL_NPC).
func ZcAckReqnameallNpc_0x0095(data []byte, packetver uint32) events.ZcAckReqnameallNpc {
	var e events.ZcAckReqnameallNpc
	if packetver >= 20171207 {
		// e.Name = strings.TrimRight(string(packet.name[:]), "\x00")  (complex expression — implement manually)
		e.ID = leU32(data, 2)  // rAthena: gid (offset 2, size 4)
	} else {
		// e.Name = strings.TrimRight(string(packet.name[:]), "\x00")  (complex expression — implement manually)
		e.ID = leU32(data, 2)  // rAthena: gid (offset 2, size 4)
	}
	return e
}

