// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcAckUploadMacroDetector_0x0A53 decodes a 0x0A53 packet (struct PACKET_ZC_ACK_UPLOAD_MACRO_DETECTOR).
func ZcAckUploadMacroDetector_0x0A53(data []byte, packetver uint32) events.ZcAckUploadMacroDetector {
	var e events.ZcAckUploadMacroDetector
	_ = packetver
	e.CaptchaKey = nullTermString(data[2:6]) // rAthena: captchaKey (offset 2, size 4)
	e.CaptchaFlag = data[6:]                 // rAthena: captchaFlag (offset 6, size 4)
	return e
}
