// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcAutospelllist_0x01CD decodes a 0x01CD packet (struct PACKET_ZC_AUTOSPELLLIST).
func ZcAutospelllist_0x01CD(data []byte, packetver uint32) events.ZcAutospelllist {
	var e events.ZcAutospelllist
	if packetver >= 20181128 {
		e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	} else {
		e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	}
	return e
}

