// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcAckReadRodex_0x09EB decodes a 0x09EB packet (struct PACKET_ZC_ACK_READ_RODEX).
func ZcAckReadRodex_0x09EB(data []byte, packetver uint32) events.ZcAckReadRodex {
	var e events.ZcAckReadRodex
	_ = packetver
	e.ItemCnt = int8(data[23])  // rAthena: ItemCnt (offset 23, size 1)
	e.MailID = leI64(data, 5)  // rAthena: MailID (offset 5, size 8)
	e.PacketLength = leI16(data, 2)  // rAthena: PacketLength (offset 2, size 2)
	e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
	e.Textcontent = nullTermString(data[24:])  // rAthena: Textcontent (offset 24, size 0)
	e.TextcontentsLength = leI16(data, 13)  // rAthena: TextcontentsLength (offset 13, size 2)
	e.Opentype = int8(data[4])  // rAthena: opentype (offset 4, size 1)
	e.Zeny = leI64(data, 15)  // rAthena: zeny (offset 15, size 8)
	return e
}

