// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// ZcApplyMacroDetectorCaptcha_0x0A59 decodes a 0x0A59 packet (struct PACKET_ZC_APPLY_MACRO_DETECTOR_CAPTCHA).
func ZcApplyMacroDetectorCaptcha_0x0A59(data []byte, packetver uint32) events.ZcApplyMacroDetectorCaptcha {
	var e events.ZcApplyMacroDetectorCaptcha
	_ = packetver
	e.PacketLength = leI16(data, 2)  // rAthena: PacketLength (offset 2, size 2)
	e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
	e.CaptchaKey = func() [4]byte { var a [4]byte; copy(a[:], data[4:]); return a }()  // rAthena: captchaKey (offset 4, size 4)
	e.ImageData = data[8:]  // rAthena: imageData (offset 8, size 0)
	return e
}

