// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcAckTakeoffEquipAll_0x0BAE decodes a 0x0BAE packet (struct PACKET_ZC_ACK_TAKEOFF_EQUIP_ALL).
func ZcAckTakeoffEquipAll_0x0BAE(data []byte, packetver uint32) events.ZcAckTakeoffEquipAll {
	var e events.ZcAckTakeoffEquipAll
	_ = packetver
	e.Result = data[2]  // rAthena: result (offset 2, size 1)
	return e
}

