// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcAckReqnameall_0x0195 decodes a 0x0195 packet (struct PACKET_ZC_ACK_REQNAMEALL).
func ZcAckReqnameall_0x0195(data []byte, packetver uint32) events.ZcAckReqnameall {
	var e events.ZcAckReqnameall
	_ = packetver
	e.Packet_id = leU16(data, 0)                   // rAthena: packet_id (offset 0, size 2)
	e.Gid = leI32(data, 2)                         // rAthena: gid (offset 2, size 4)
	e.Name = nullTermString(data[6:30])            // rAthena: name (offset 6, size 24)
	e.Party_name = nullTermString(data[30:54])     // rAthena: party_name (offset 30, size 24)
	e.Guild_name = nullTermString(data[54:78])     // rAthena: guild_name (offset 54, size 24)
	e.Position_name = nullTermString(data[78:102]) // rAthena: position_name (offset 78, size 24)
	return e
}

// ZcAckReqnameall_0x0A30 decodes a 0x0A30 packet (struct PACKET_ZC_ACK_REQNAMEALL).
func ZcAckReqnameall_0x0A30(data []byte, packetver uint32) events.ZcAckReqnameall {
	var e events.ZcAckReqnameall
	_ = packetver
	e.Packet_id = leU16(data, 0)                   // rAthena: packet_id (offset 0, size 2)
	e.Gid = leI32(data, 2)                         // rAthena: gid (offset 2, size 4)
	e.Name = nullTermString(data[6:30])            // rAthena: name (offset 6, size 24)
	e.Party_name = nullTermString(data[30:54])     // rAthena: party_name (offset 30, size 24)
	e.Guild_name = nullTermString(data[54:78])     // rAthena: guild_name (offset 54, size 24)
	e.Position_name = nullTermString(data[78:102]) // rAthena: position_name (offset 78, size 24)
	e.Title_id = leI32(data, 102)                  // rAthena: title_id (offset 102, size 4)
	return e
}
