// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcAcceptEnter_0x0A18 decodes a 0x0A18 packet (struct PACKET_ZC_ACCEPT_ENTER).
func ZcAcceptEnter_0x0A18(data []byte, packetver uint32) events.ZcAcceptEnter {
	var e events.ZcAcceptEnter
	_ = packetver
	e.StartTime = leU32(data, 2)  // rAthena: startTime (offset 2, size 4)
	e.PosDir = [3]byte(data[6:9])  // rAthena: posDir (offset 6, size 3)
	e.XSize = data[9]  // rAthena: xSize (offset 9, size 1)
	e.YSize = data[10]  // rAthena: ySize (offset 10, size 1)
	e.Font = leU16(data, 11)  // rAthena: font (offset 11, size 2)
	e.Sex = data[13]  // rAthena: sex (offset 13, size 1)
	return e
}

// ZcAcceptEnter_0x0073 decodes a 0x0073 packet (struct PACKET_ZC_ACCEPT_ENTER).
func ZcAcceptEnter_0x0073(data []byte, packetver uint32) events.ZcAcceptEnter {
	var e events.ZcAcceptEnter
	_ = packetver
	e.StartTime = leU32(data, 2)  // rAthena: startTime (offset 2, size 4)
	e.PosDir = [3]byte(data[6:9])  // rAthena: posDir (offset 6, size 3)
	e.XSize = data[9]  // rAthena: xSize (offset 9, size 1)
	e.YSize = data[10]  // rAthena: ySize (offset 10, size 1)
	return e
}

// ZcAcceptEnter_0x02EB decodes a 0x02EB packet (struct PACKET_ZC_ACCEPT_ENTER).
func ZcAcceptEnter_0x02EB(data []byte, packetver uint32) events.ZcAcceptEnter {
	var e events.ZcAcceptEnter
	_ = packetver
	e.StartTime = leU32(data, 2)  // rAthena: startTime (offset 2, size 4)
	e.PosDir = [3]byte(data[6:9])  // rAthena: posDir (offset 6, size 3)
	e.XSize = data[9]  // rAthena: xSize (offset 9, size 1)
	e.YSize = data[10]  // rAthena: ySize (offset 10, size 1)
	e.Font = leU16(data, 11)  // rAthena: font (offset 11, size 2)
	return e
}

