// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcAckRandomCombineItem_0x0A50 decodes a 0x0A50 packet (struct PACKET_ZC_ACK_RANDOM_COMBINE_ITEM).
func ZcAckRandomCombineItem_0x0A50(data []byte, packetver uint32) events.ZcAckRandomCombineItem {
	var e events.ZcAckRandomCombineItem
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	e.Result = leI16(data, 2)  // rAthena: result (offset 2, size 2)
	return e
}

