// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcBattlefieldNotifyHp_0x02E0 decodes a 0x02E0 packet (struct PACKET_ZC_BATTLEFIELD_NOTIFY_HP).
func ZcBattlefieldNotifyHp_0x02E0(data []byte, packetver uint32) events.ZcBattlefieldNotifyHp {
	var e events.ZcBattlefieldNotifyHp
	if packetver >= 20140312 {
		e.AID = leU32(data, 2)  // rAthena: AID (offset 2, size 4)
		e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
		e.Hp = leI32(data, 6)  // rAthena: hp (offset 6, size 4)
		e.Maxhp = leI32(data, 10)  // rAthena: maxhp (offset 10, size 4)
	} else {
		e.AID = leU32(data, 2)  // rAthena: AID (offset 2, size 4)
		e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
		e.Hp = int32(leI16(data, 30))  // rAthena: hp (offset 30, size 2)
		e.Maxhp = int32(leI16(data, 32))  // rAthena: maxhp (offset 32, size 2)
	}
	return e
}

