// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// ZcChangeItemOption_0x0AB9 decodes a 0x0AB9 packet (struct PACKET_ZC_CHANGE_ITEM_OPTION).
func ZcChangeItemOption_0x0AB9(data []byte, packetver uint32) events.ZcChangeItemOption {
	var e events.ZcChangeItemOption
	if packetver >= 20200902 {
		e.Index = leI16(data, 2)  // rAthena: index (offset 2, size 2)
		e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
		e.RefiningLevel = int16(int8(data[21]))  // rAthena: refiningLevel (offset 21, size 1)
		// e.Slot = serialization.SerializeEQUIPSLOTINFO(packet.slot)  (complex expression — implement manually)
	} else if packetver >= 20181121 {
		e.Index = leI16(data, 2)  // rAthena: index (offset 2, size 2)
		e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
		e.RefiningLevel = leI16(data, 5)  // rAthena: refiningLevel (offset 5, size 2)
		// e.Slot = serialization.SerializeEQUIPSLOTINFO(packet.slot)  (complex expression — implement manually)
	} else if packetver >= 20181017 {
		e.Index = leI16(data, 2)  // rAthena: index (offset 2, size 2)
		e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
		e.RefiningLevel = leI16(data, 5)  // rAthena: refiningLevel (offset 5, size 2)
		// e.Slot = serialization.SerializeEQUIPSLOTINFO(packet.slot)  (complex expression — implement manually)
	} else {
		e.Index = leI16(data, 2)  // rAthena: index (offset 2, size 2)
		e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
		e.RefiningLevel = leI16(data, 4)  // rAthena: refiningLevel (offset 4, size 2)
		// e.Slot = serialization.SerializeEQUIPSLOTINFO(packet.slot)  (complex expression — implement manually)
	}
	return e
}

