// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcCloseMacroDetector_0x0A5D decodes a 0x0A5D packet (struct PACKET_ZC_CLOSE_MACRO_DETECTOR).
func ZcCloseMacroDetector_0x0A5D(data []byte, packetver uint32) events.ZcCloseMacroDetector {
	var e events.ZcCloseMacroDetector
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
	return e
}

