// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcCompleteUploadMacroDetectorCaptcha_0x0A55 decodes a 0x0A55 packet (struct PACKET_ZC_COMPLETE_UPLOAD_MACRO_DETECTOR_CAPTCHA).
func ZcCompleteUploadMacroDetectorCaptcha_0x0A55(data []byte, packetver uint32) events.ZcCompleteUploadMacroDetectorCaptcha {
	var e events.ZcCompleteUploadMacroDetectorCaptcha
	_ = packetver
	return e
}
