// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcChangestatePet_0x01A4 decodes a 0x01A4 packet (struct PACKET_ZC_CHANGESTATE_PET).
func ZcChangestatePet_0x01A4(data []byte, packetver uint32) events.ZcChangestatePet {
	var e events.ZcChangestatePet
	_ = packetver
	e.Type = int8(data[2]) // rAthena: type (offset 2, size 1)
	e.GID = data[3:]       // rAthena: GID (offset 3, size 4)
	e.Data = data[7:]      // rAthena: data (offset 7, size 4)
	return e
}
