// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcClearDialog_0x08D6 decodes a 0x08D6 packet (struct PACKET_ZC_CLEAR_DIALOG).
func ZcClearDialog_0x08D6(data []byte, packetver uint32) events.ZcClearDialog {
	var e events.ZcClearDialog
	_ = packetver
	e.GID = leU32(data, 2) // rAthena: GID (offset 2, size 4)
	return e
}
