// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcCheckname_0x0A14 decodes a 0x0A14 packet (struct PACKET_ZC_CHECKNAME).
func ZcCheckname_0x0A14(data []byte, packetver uint32) events.ZcCheckname {
	var e events.ZcCheckname
	if packetver >= 20170315 {
		e.CharId = leI32(data, 2)  // rAthena: CharId (offset 2, size 4)
		e.Class = leI16(data, 6)  // rAthena: Class (offset 6, size 2)
		e.BaseLevel = leI16(data, 8)  // rAthena: BaseLevel (offset 8, size 2)
		e.Name = nullTermString(data[10:34])  // rAthena: Name (offset 10, size 24)
	} else {
		e.CharId = leI32(data, 2)  // rAthena: CharId (offset 2, size 4)
		e.Class = leI16(data, 6)  // rAthena: Class (offset 6, size 2)
		e.BaseLevel = leI16(data, 8)  // rAthena: BaseLevel (offset 8, size 2)
	}
	return e
}

// ZcCheckname_0x0A51 decodes a 0x0A51 packet (struct PACKET_ZC_CHECKNAME).
func ZcCheckname_0x0A51(data []byte, packetver uint32) events.ZcCheckname {
	var e events.ZcCheckname
	if packetver >= 20170315 {
		e.CharId = leI32(data, 2)  // rAthena: CharId (offset 2, size 4)
		e.Class = leI16(data, 6)  // rAthena: Class (offset 6, size 2)
		e.BaseLevel = leI16(data, 8)  // rAthena: BaseLevel (offset 8, size 2)
		e.Name = nullTermString(data[10:34])  // rAthena: Name (offset 10, size 24)
	} else {
		e.CharId = leI32(data, 2)  // rAthena: CharId (offset 2, size 4)
		e.Class = leI16(data, 6)  // rAthena: Class (offset 6, size 2)
		e.BaseLevel = leI16(data, 8)  // rAthena: BaseLevel (offset 8, size 2)
	}
	return e
}

