// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcDebugmsg_0x0ADB decodes a 0x0ADB packet (struct PACKET_ZC_DEBUGMSG).
func ZcDebugmsg_0x0ADB(data []byte, packetver uint32) events.ZcDebugmsg {
	var e events.ZcDebugmsg
	_ = packetver
	e.PacketLength = leI16(data, 2)      // rAthena: packetLength (offset 2, size 2)
	e.Color = leI32(data, 4)             // rAthena: color (offset 4, size 4)
	e.Message = nullTermString(data[8:]) // rAthena: message (offset 8, size 0)
	return e
}
