// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcDialogWindowSize_0x0BA2 decodes a 0x0BA2 packet (struct PACKET_ZC_DIALOG_WINDOW_SIZE).
func ZcDialogWindowSize_0x0BA2(data []byte, packetver uint32) events.ZcDialogWindowSize {
	var e events.ZcDialogWindowSize
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
	return e
}

