// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcDeleteItemFromCart_0x0125 decodes a 0x0125 packet (struct PACKET_ZC_DELETE_ITEM_FROM_CART).
func ZcDeleteItemFromCart_0x0125(data []byte, packetver uint32) events.ZcDeleteItemFromCart {
	var e events.ZcDeleteItemFromCart
	_ = packetver
	e.Index = leU16(data, 2)  // rAthena: index (offset 2, size 2)
	e.Amount = leI32(data, 4) // rAthena: amount (offset 4, size 4)
	return e
}
