// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// ZcDialogWindowPos_0x0BA3 decodes a 0x0BA3 packet (struct PACKET_ZC_DIALOG_WINDOW_POS).
func ZcDialogWindowPos_0x0BA3(data []byte, packetver uint32) events.ZcDialogWindowPos {
	var e events.ZcDialogWindowPos
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
	return e
}

