// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcDialogWindowPos2_0x0BB5 decodes a 0x0BB5 packet (struct PACKET_ZC_DIALOG_WINDOW_POS2).
func ZcDialogWindowPos2_0x0BB5(data []byte, packetver uint32) events.ZcDialogWindowPos2 {
	var e events.ZcDialogWindowPos2
	_ = packetver
	e.X = data[2:] // rAthena: x (offset 2, size 4)
	e.Y = data[6:] // rAthena: y (offset 6, size 4)
	return e
}
