// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcDisappearBuyingStoreEntry_0x0816 decodes a 0x0816 packet (struct PACKET_ZC_DISAPPEAR_BUYING_STORE_ENTRY).
func ZcDisappearBuyingStoreEntry_0x0816(data []byte, packetver uint32) events.ZcDisappearBuyingStoreEntry {
	var e events.ZcDisappearBuyingStoreEntry
	_ = packetver
	e.MakerAID = leU32(data, 2) // rAthena: makerAID (offset 2, size 4)
	return e
}
