// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcExtendBodyitemSize_0x0B18 decodes a 0x0B18 packet (struct PACKET_ZC_EXTEND_BODYITEM_SIZE).
func ZcExtendBodyitemSize_0x0B18(data []byte, packetver uint32) events.ZcExtendBodyitemSize {
	var e events.ZcExtendBodyitemSize
	_ = packetver
	e.ExpansionSize = leI16(data, 2)  // rAthena: expansionSize (offset 2, size 2)
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	return e
}

