// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcElParChange_0x081E decodes a 0x081E packet (struct PACKET_ZC_EL_PAR_CHANGE).
func ZcElParChange_0x081E(data []byte, packetver uint32) events.ZcElParChange {
	var e events.ZcElParChange
	_ = packetver
	e.Type = leU16(data, 2)  // rAthena: type (offset 2, size 2)
	e.Value = leU32(data, 4) // rAthena: value (offset 4, size 4)
	return e
}
