// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcEquipmentEffect_0x0A3B decodes a 0x0A3B packet (struct PACKET_ZC_EQUIPMENT_EFFECT).
func ZcEquipmentEffect_0x0A3B(data []byte, packetver uint32) events.ZcEquipmentEffect {
	var e events.ZcEquipmentEffect
	_ = packetver
	e.Aid = leU32(data, 4)  // rAthena: aid (offset 4, size 4)
	e.Effects = data[9:]  // rAthena: effects (offset 9, size 0)
	e.PacketLength = leI16(data, 2)  // rAthena: packetLength (offset 2, size 2)
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	e.Status = int8(data[8])  // rAthena: status (offset 8, size 1)
	return e
}

