// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcGradeEnchantMaterialList_0x0B5A decodes a 0x0B5A packet (struct PACKET_ZC_GRADE_ENCHANT_MATERIAL_LIST).
func ZcGradeEnchantMaterialList_0x0B5A(data []byte, packetver uint32) events.ZcGradeEnchantMaterialList {
	var e events.ZcGradeEnchantMaterialList
	_ = packetver
	e.PacketLength = leI16(data, 2)    // rAthena: PacketLength (offset 2, size 2)
	e.Index = leI16(data, 4)           // rAthena: index (offset 4, size 2)
	e.Success_chance = leI32(data, 6)  // rAthena: success_chance (offset 6, size 4)
	e.Blessing_info = data[10:26]      // rAthena: blessing_info (offset 10, size 16)
	e.Protect_itemid = leI32(data, 26) // rAthena: protect_itemid (offset 26, size 4)
	e.Protect_amount = leI32(data, 30) // rAthena: protect_amount (offset 30, size 4)
	e.Material_info = data[34:]        // rAthena: material_info (offset 34, size 0)
	return e
}
