// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcGuildEmblemImg_0x0152 decodes a 0x0152 packet (struct PACKET_ZC_GUILD_EMBLEM_IMG).
func ZcGuildEmblemImg_0x0152(data []byte, packetver uint32) events.ZcGuildEmblemImg {
	var e events.ZcGuildEmblemImg
	if packetver >= 20190821 {
		e.EmblemData = nullTermString(data[14:])  // rAthena: emblem_data (offset 14, size 0)
		e.EmblemId = leU32(data, 10)  // rAthena: emblem_id (offset 10, size 4)
		e.GuildId = leI32(data, 6)  // rAthena: guild_id (offset 6, size 4)
		e.PacketLength = leI16(data, 2)  // rAthena: packetLength (offset 2, size 2)
		e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	} else {
		e.EmblemData = nullTermString(data[12:])  // rAthena: emblem_data (offset 12, size 0)
		e.EmblemId = leU32(data, 8)  // rAthena: emblem_id (offset 8, size 4)
		e.GuildId = leI32(data, 4)  // rAthena: guild_id (offset 4, size 4)
		e.PacketLength = leI16(data, 2)  // rAthena: packetLength (offset 2, size 2)
		e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	}
	return e
}

