// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcGoldpccafePoint_0x0A15 decodes a 0x0A15 packet (struct PACKET_ZC_GOLDPCCAFE_POINT).
func ZcGoldpccafePoint_0x0A15(data []byte, packetver uint32) events.ZcGoldpccafePoint {
	var e events.ZcGoldpccafePoint
	_ = packetver
	e.IsActive = int8(data[2])  // rAthena: isActive (offset 2, size 1)
	e.Mode = int8(data[3])  // rAthena: mode (offset 3, size 1)
	e.Point = leI32(data, 4)  // rAthena: point (offset 4, size 4)
	e.PlayedTime = leI32(data, 8)  // rAthena: playedTime (offset 8, size 4)
	return e
}

