// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcGuildSkillinfo_0x0162 decodes a 0x0162 packet (struct PACKET_ZC_GUILD_SKILLINFO).
func ZcGuildSkillinfo_0x0162(data []byte, packetver uint32) events.ZcGuildSkillinfo {
	var e events.ZcGuildSkillinfo
	_ = packetver
	e.PacketLength = leI16(data, 2)  // rAthena: PacketLength (offset 2, size 2)
	e.SkillPoint = leI16(data, 4)  // rAthena: skillPoint (offset 4, size 2)
	e.SkillInfo = data[6:]  // rAthena: skillInfo (offset 6, size 0)
	return e
}

