// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcItemPickupParty_0x02B8 decodes a 0x02B8 packet (struct PACKET_ZC_ITEM_PICKUP_PARTY).
func ZcItemPickupParty_0x02B8(data []byte, packetver uint32) events.ZcItemPickupParty {
	var e events.ZcItemPickupParty
	if packetver >= 20200902 {
		e.AID = leU32(data, 2)  // rAthena: AID (offset 2, size 4)
		e.Damaged = data[11]  // rAthena: damaged (offset 11, size 1)
		e.Identified = data[10]  // rAthena: identified (offset 10, size 1)
		e.ItemId = leU32(data, 6)  // rAthena: itemId (offset 6, size 4)
		e.ItemType = data[30]  // rAthena: itemType (offset 30, size 1)
		e.Location = leU16(data, 28)  // rAthena: location (offset 28, size 2)
		e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
		e.Refine = data[31]  // rAthena: refine (offset 31, size 1)
		// e.Slot = serialization.SerializeEQUIPSLOTINFO(packet.slot)  (complex expression — implement manually)
	} else if packetver >= 20181121 {
		e.AID = leU32(data, 2)  // rAthena: AID (offset 2, size 4)
		e.Damaged = data[11]  // rAthena: damaged (offset 11, size 1)
		e.Identified = data[10]  // rAthena: identified (offset 10, size 1)
		e.ItemId = leU32(data, 6)  // rAthena: itemId (offset 6, size 4)
		e.ItemType = data[31]  // rAthena: itemType (offset 31, size 1)
		e.Location = leU16(data, 29)  // rAthena: location (offset 29, size 2)
		e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
		e.Refine = data[12]  // rAthena: refine (offset 12, size 1)
		// e.Slot = serialization.SerializeEQUIPSLOTINFO(packet.slot)  (complex expression — implement manually)
	} else {
		e.AID = leU32(data, 2)  // rAthena: AID (offset 2, size 4)
		e.Damaged = data[9]  // rAthena: damaged (offset 9, size 1)
		e.Identified = data[8]  // rAthena: identified (offset 8, size 1)
		e.ItemId = uint32(leU16(data, 6))  // rAthena: itemId (offset 6, size 2)
		e.ItemType = data[21]  // rAthena: itemType (offset 21, size 1)
		e.Location = leU16(data, 19)  // rAthena: location (offset 19, size 2)
		e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
		e.Refine = data[10]  // rAthena: refine (offset 10, size 1)
		// e.Slot = serialization.SerializeEQUIPSLOTINFO(packet.slot)  (complex expression — implement manually)
	}
	return e
}

