// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcItemReformAck_0x0B92 decodes a 0x0B92 packet (struct PACKET_ZC_ITEM_REFORM_ACK).
func ZcItemReformAck_0x0B92(data []byte, packetver uint32) events.ZcItemReformAck {
	var e events.ZcItemReformAck
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
	e.Index = leI16(data, 2)  // rAthena: index (offset 2, size 2)
	e.Result = int8(data[4])  // rAthena: result (offset 4, size 1)
	return e
}

