// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcInventoryEnd_0x0B0B decodes a 0x0B0B packet (struct PACKET_ZC_INVENTORY_END).
func ZcInventoryEnd_0x0B0B(data []byte, packetver uint32) events.ZcInventoryEnd {
	var e events.ZcInventoryEnd
	_ = packetver
	e.Flag = data[3]  // rAthena: flag (offset 3, size 1)
	e.InvType = data[2]  // rAthena: invType (offset 2, size 1)
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	return e
}

