// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcLonglongparChange_0x0ACB decodes a 0x0ACB packet (struct PACKET_ZC_LONGLONGPAR_CHANGE).
func ZcLonglongparChange_0x0ACB(data []byte, packetver uint32) events.ZcLonglongparChange {
	var e events.ZcLonglongparChange
	_ = packetver
	e.VarID = leU16(data, 2)  // rAthena: varID (offset 2, size 2)
	e.Amount = leI64(data, 4) // rAthena: amount (offset 4, size 8)
	return e
}
