// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcMakingarrowList_0x01AD decodes a 0x01AD packet (struct PACKET_ZC_MAKINGARROW_LIST).
func ZcMakingarrowList_0x01AD(data []byte, packetver uint32) events.ZcMakingarrowList {
	var e events.ZcMakingarrowList
	_ = packetver
	e.PacketLength = leI16(data, 2)  // rAthena: packetLength (offset 2, size 2)
	e.Items = data[4:]  // rAthena: items (offset 4, size 0)
	return e
}

