// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// ZcMakingitemList_0x025A decodes a 0x025A packet (struct PACKET_ZC_MAKINGITEM_LIST).
func ZcMakingitemList_0x025A(data []byte, packetver uint32) events.ZcMakingitemList {
	var e events.ZcMakingitemList
	_ = packetver
	e.Items = data[6:]  // rAthena: items (offset 6, size 0)
	e.MakeItem = leU16(data, 4)  // rAthena: makeItem (offset 4, size 2)
	e.PacketLength = leI16(data, 2)  // rAthena: packetLength (offset 2, size 2)
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	return e
}

