// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcMembermgrInfo_0x0154 decodes a 0x0154 packet (struct PACKET_ZC_MEMBERMGR_INFO).
func ZcMembermgrInfo_0x0154(data []byte, packetver uint32) events.ZcMembermgrInfo {
	var e events.ZcMembermgrInfo
	_ = packetver
	e.PacketLength = leI16(data, 2) // rAthena: packetLength (offset 2, size 2)
	e.GuildMemberInfo = data[4:]    // rAthena: guildMemberInfo (offset 4, size 0)
	return e
}
