// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcNpcMarketOpen_0x09D5 decodes a 0x09D5 packet (struct PACKET_ZC_NPC_MARKET_OPEN).
func ZcNpcMarketOpen_0x09D5(data []byte, packetver uint32) events.ZcNpcMarketOpen {
	var e events.ZcNpcMarketOpen
	_ = packetver
	e.PacketLength = leI16(data, 2) // rAthena: packetLength (offset 2, size 2)
	e.List = data[4:]               // rAthena: list (offset 4, size 0)
	return e
}
