// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// ZcNotifyHpToGroupm_0x0106 decodes a 0x0106 packet (struct PACKET_ZC_NOTIFY_HP_TO_GROUPM).
func ZcNotifyHpToGroupm_0x0106(data []byte, packetver uint32) events.ZcNotifyHpToGroupm {
	var e events.ZcNotifyHpToGroupm
	if packetver >= 20100119 {
		e.AccountID = leU32(data, 2)  // rAthena: AID (offset 2, size 4)
		e.Hp = leU16(data, 6)  // rAthena: hp (offset 6, size 4)
		e.MaxHP = leU16(data, 10)  // rAthena: maxhp (offset 10, size 4)
	} else {
		e.AccountID = leU32(data, 2)  // rAthena: AID (offset 2, size 4)
		e.Hp = leU16(data, 6)  // rAthena: hp (offset 6, size 2)
		e.MaxHP = leU16(data, 8)  // rAthena: maxhp (offset 8, size 2)
	}
	return e
}

