// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// ZcNotifyCartitemCountinfo_0x0121 decodes a 0x0121 packet (struct PACKET_ZC_NOTIFY_CARTITEM_COUNTINFO).
func ZcNotifyCartitemCountinfo_0x0121(data []byte, packetver uint32) events.ZcNotifyCartitemCountinfo {
	var e events.ZcNotifyCartitemCountinfo
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
	e.CurCount = leI16(data, 2)  // rAthena: curCount (offset 2, size 2)
	e.CurWeight = leI32(data, 6)  // rAthena: curWeight (offset 6, size 4)
	e.MaxCount = leI16(data, 4)  // rAthena: maxCount (offset 4, size 2)
	e.MaxWeight = leI32(data, 10)  // rAthena: maxWeight (offset 10, size 4)
	return e
}

