// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcNotifyPositionToGroupm_0x0107 decodes a 0x0107 packet (struct PACKET_ZC_NOTIFY_POSITION_TO_GROUPM).
func ZcNotifyPositionToGroupm_0x0107(data []byte, packetver uint32) events.ZcNotifyPositionToGroupm {
	var e events.ZcNotifyPositionToGroupm
	_ = packetver
	e.AID = data[2:]  // rAthena: AID (offset 2, size 4)
	e.XPos = leI16(data, 6)  // rAthena: xPos (offset 6, size 2)
	e.YPos = leI16(data, 8)  // rAthena: yPos (offset 8, size 2)
	return e
}

