// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// ZcNpcBarterMarketIteminfo_0x0B0E decodes a 0x0B0E packet (struct PACKET_ZC_NPC_BARTER_MARKET_ITEMINFO).
func ZcNpcBarterMarketIteminfo_0x0B0E(data []byte, packetver uint32) events.ZcNpcBarterMarketIteminfo {
	var e events.ZcNpcBarterMarketIteminfo
	_ = packetver
	e.List = data[4:]  // rAthena: list (offset 4, size 0)
	e.PacketLength = leI16(data, 2)  // rAthena: packetLength (offset 2, size 2)
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	return e
}

