// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcNotifyMemberinfoToGroupm_0x0ABD decodes a 0x0ABD packet (struct PACKET_ZC_NOTIFY_MEMBERINFO_TO_GROUPM).
func ZcNotifyMemberinfoToGroupm_0x0ABD(data []byte, packetver uint32) events.ZcNotifyMemberinfoToGroupm {
	var e events.ZcNotifyMemberinfoToGroupm
	_ = packetver
	e.AID = data[2:]  // rAthena: AID (offset 2, size 4)
	e.Job = leI16(data, 6)  // rAthena: job (offset 6, size 2)
	e.Level = leI16(data, 8)  // rAthena: level (offset 8, size 2)
	return e
}

