// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// ZcNotifyMemberinfoToGroupm_0x0ABD decodes a 0x0ABD packet (struct PACKET_ZC_NOTIFY_MEMBERINFO_TO_GROUPM).
func ZcNotifyMemberinfoToGroupm_0x0ABD(data []byte, packetver uint32) events.ZcNotifyMemberinfoToGroupm {
	var e events.ZcNotifyMemberinfoToGroupm
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
	e.Job = leI16(data, 6)  // rAthena: job (offset 6, size 2)
	e.Level = leI16(data, 8)  // rAthena: level (offset 8, size 2)
	return e
}

