// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcOpenReformUi_0x0B8F decodes a 0x0B8F packet (struct PACKET_ZC_OPEN_REFORM_UI).
func ZcOpenReformUi_0x0B8F(data []byte, packetver uint32) events.ZcOpenReformUi {
	var e events.ZcOpenReformUi
	_ = packetver
	e.ITID = leI32(data, 2) // rAthena: ITID (offset 2, size 4)
	return e
}
