// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// ZcPartyConfig_0x02C9 decodes a 0x02C9 packet (struct PACKET_ZC_PARTY_CONFIG).
func ZcPartyConfig_0x02C9(data []byte, packetver uint32) events.ZcPartyConfig {
	var e events.ZcPartyConfig
	_ = packetver
	e.DenyPartyInvites = data[2]  // rAthena: denyPartyInvites (offset 2, size 1)
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	return e
}

