// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcPartyJoinReq_0x02C6 decodes a 0x02C6 packet (struct PACKET_ZC_PARTY_JOIN_REQ).
func ZcPartyJoinReq_0x02C6(data []byte, packetver uint32) events.ZcPartyJoinReq {
	var e events.ZcPartyJoinReq
	_ = packetver
	e.GRID = data[2:6]                       // rAthena: GRID (offset 2, size 4)
	e.GroupName = nullTermString(data[6:30]) // rAthena: groupName (offset 6, size 24)
	return e
}

// ZcPartyJoinReq_0x00FE decodes a 0x00FE packet (struct PACKET_ZC_PARTY_JOIN_REQ).
func ZcPartyJoinReq_0x00FE(data []byte, packetver uint32) events.ZcPartyJoinReq {
	var e events.ZcPartyJoinReq
	_ = packetver
	e.GRID = data[2:6]                       // rAthena: GRID (offset 2, size 4)
	e.GroupName = nullTermString(data[6:30]) // rAthena: groupName (offset 6, size 24)
	return e
}
