// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcPositionInfo_0x0160 decodes a 0x0160 packet (struct PACKET_ZC_POSITION_INFO).
func ZcPositionInfo_0x0160(data []byte, packetver uint32) events.ZcPositionInfo {
	var e events.ZcPositionInfo
	_ = packetver
	e.PacketLength = leI16(data, 2) // rAthena: PacketLength (offset 2, size 2)
	e.PosInfo = data[4:]            // rAthena: posInfo (offset 4, size 0)
	return e
}
