// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcPcPurchaseItemlistFrommc_0x0133 decodes a 0x0133 packet (struct PACKET_ZC_PC_PURCHASE_ITEMLIST_FROMMC).
func ZcPcPurchaseItemlistFrommc_0x0133(data []byte, packetver uint32) events.ZcPcPurchaseItemlistFrommc {
	var e events.ZcPcPurchaseItemlistFrommc
	if packetver >= 20100105 {
		e.PacketLength = leI16(data, 2)  // rAthena: packetLength (offset 2, size 2)
		e.AID = leU32(data, 4)  // rAthena: AID (offset 4, size 4)
		e.VenderId = leU32(data, 8)  // rAthena: venderId (offset 8, size 4)
		e.Items = data[12:]  // rAthena: items (offset 12, size 0)
	} else {
		e.PacketLength = leI16(data, 2)  // rAthena: packetLength (offset 2, size 2)
		e.AID = leU32(data, 4)  // rAthena: AID (offset 4, size 4)
		e.Items = data[8:]  // rAthena: items (offset 8, size 0)
	}
	return e
}

