// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcPlayNpcBgm_0x07FE decodes a 0x07FE packet (struct PACKET_ZC_PLAY_NPC_BGM).
func ZcPlayNpcBgm_0x07FE(data []byte, packetver uint32) events.ZcPlayNpcBgm {
	var e events.ZcPlayNpcBgm
	if packetver >= 20220504 {
		e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
	} else {
		e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
	}
	return e
}

