// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// ZcPreviewMacroDetectorCaptcha_0x0A6B decodes a 0x0A6B packet (struct PACKET_ZC_PREVIEW_MACRO_DETECTOR_CAPTCHA).
func ZcPreviewMacroDetectorCaptcha_0x0A6B(data []byte, packetver uint32) events.ZcPreviewMacroDetectorCaptcha {
	var e events.ZcPreviewMacroDetectorCaptcha
	_ = packetver
	e.PacketLength = leI16(data, 2)  // rAthena: PacketLength (offset 2, size 2)
	e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
	e.CaptchaKey = nullTermString(data[4:8])  // rAthena: captchaKey (offset 4, size 4)
	e.ImageData = nullTermString(data[8:])  // rAthena: imageData (offset 8, size 0)
	return e
}

