// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcResponseEnchant_0x0B9F decodes a 0x0B9F packet (struct PACKET_ZC_RESPONSE_ENCHANT).
func ZcResponseEnchant_0x0B9F(data []byte, packetver uint32) events.ZcResponseEnchant {
	var e events.ZcResponseEnchant
	_ = packetver
	e.MsgId = leI32(data, 2) // rAthena: msgId (offset 2, size 4)
	e.ITID = leU32(data, 6)  // rAthena: ITID (offset 6, size 4)
	return e
}
