// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// ZcReqWearEquipAck_0x00AA decodes a 0x00AA packet (struct PACKET_ZC_REQ_WEAR_EQUIP_ACK).
func ZcReqWearEquipAck_0x00AA(data []byte, packetver uint32) events.ZcReqWearEquipAck {
	var e events.ZcReqWearEquipAck
	if packetver >= 20121205 {
		e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
		e.Index = leU16(data, 2)  // rAthena: index (offset 2, size 2)
		e.Result = data[10]  // rAthena: result (offset 10, size 1)
		e.WearLocation = leU16(data, 4)  // rAthena: wearLocation (offset 4, size 4)
	} else if packetver >= 20101123 {
		e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
		e.Index = leU16(data, 2)  // rAthena: index (offset 2, size 2)
		e.Result = data[8]  // rAthena: result (offset 8, size 1)
		e.WearLocation = leU16(data, 4)  // rAthena: wearLocation (offset 4, size 2)
	} else {
		e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
		e.Index = leU16(data, 2)  // rAthena: index (offset 2, size 2)
		e.Result = data[6]  // rAthena: result (offset 6, size 1)
		e.WearLocation = leU16(data, 4)  // rAthena: wearLocation (offset 4, size 2)
	}
	return e
}

