// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcReqJoinGuild_0x016A decodes a 0x016A packet (struct PACKET_ZC_REQ_JOIN_GUILD).
func ZcReqJoinGuild_0x016A(data []byte, packetver uint32) events.ZcReqJoinGuild {
	var e events.ZcReqJoinGuild
	_ = packetver
	e.Guild_id = leU32(data, 2)  // rAthena: guild_id (offset 2, size 4)
	e.Guild_name = nullTermString(data[6:30])  // rAthena: guild_name (offset 6, size 24)
	return e
}

