// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcReqWearEquipAck_0x0999 decodes a 0x0999 packet (struct PACKET_ZC_REQ_WEAR_EQUIP_ACK).
func ZcReqWearEquipAck_0x0999(data []byte, packetver uint32) events.ZcReqWearEquipAck {
	var e events.ZcReqWearEquipAck
	_ = packetver
	e.Index = leU16(data, 2)  // rAthena: index (offset 2, size 2)
	e.WearLocation = leU32(data, 4)  // rAthena: wearLocation (offset 4, size 4)
	e.WItemSpriteNumber = leU16(data, 8)  // rAthena: wItemSpriteNumber (offset 8, size 2)
	e.Result = data[10]  // rAthena: result (offset 10, size 1)
	return e
}

// ZcReqWearEquipAck_0x00AA decodes a 0x00AA packet (struct PACKET_ZC_REQ_WEAR_EQUIP_ACK).
func ZcReqWearEquipAck_0x00AA(data []byte, packetver uint32) events.ZcReqWearEquipAck {
	var e events.ZcReqWearEquipAck
	if packetver >= 20101123 {
		e.Index = leU16(data, 2)  // rAthena: index (offset 2, size 2)
		e.WearLocation = uint32(leU16(data, 4))  // rAthena: wearLocation (offset 4, size 2)
		e.WItemSpriteNumber = leU16(data, 6)  // rAthena: wItemSpriteNumber (offset 6, size 2)
		e.Result = data[8]  // rAthena: result (offset 8, size 1)
	} else {
		e.Index = leU16(data, 2)  // rAthena: index (offset 2, size 2)
		e.WearLocation = uint32(leU16(data, 4))  // rAthena: wearLocation (offset 4, size 2)
		e.Result = data[6]  // rAthena: result (offset 6, size 1)
	}
	return e
}

