// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcResurrection_0x0148 decodes a 0x0148 packet (struct PACKET_ZC_RESURRECTION).
func ZcResurrection_0x0148(data []byte, packetver uint32) events.ZcResurrection {
	var e events.ZcResurrection
	_ = packetver
	e.Gid = leU32(data, 2)  // rAthena: gid (offset 2, size 4)
	e.Type = leI16(data, 6)  // rAthena: type (offset 6, size 2)
	return e
}

