// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcRoleChange_0x00E1 decodes a 0x00E1 packet (struct PACKET_ZC_ROLE_CHANGE).
func ZcRoleChange_0x00E1(data []byte, packetver uint32) events.ZcRoleChange {
	var e events.ZcRoleChange
	_ = packetver
	e.Flag = leI32(data, 2)             // rAthena: flag (offset 2, size 4)
	e.Name = nullTermString(data[6:30]) // rAthena: name (offset 6, size 24)
	return e
}
