// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// ZcShortcutKeyList_0x02B9 decodes a 0x02B9 packet (struct PACKET_ZC_SHORTCUT_KEY_LIST).
func ZcShortcutKeyList_0x02B9(data []byte, packetver uint32) events.ZcShortcutKeyList {
	var e events.ZcShortcutKeyList
	if packetver >= 20190522 {
		e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	} else if packetver >= 20141022 {
		e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	} else if packetver >= 20090617 {
		e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	} else if packetver >= 20090603 {
		e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	} else {
		e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	}
	return e
}

