// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// ZcSound_0x01D3 decodes a 0x01D3 packet (struct PACKET_ZC_SOUND).
func ZcSound_0x01D3(data []byte, packetver uint32) events.ZcSound {
	var e events.ZcSound
	_ = packetver
	e.AID = leU32(data, 31)  // rAthena: AID (offset 31, size 4)
	e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
	e.Act = data[26]  // rAthena: act (offset 26, size 1)
	e.Term = leU32(data, 27)  // rAthena: term (offset 27, size 4)
	return e
}

