// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcStatus_0x00BD decodes a 0x00BD packet (struct PACKET_ZC_STATUS).
func ZcStatus_0x00BD(data []byte, packetver uint32) events.ZcStatus {
	var e events.ZcStatus
	_ = packetver
	e.Point = leU16(data, 2)  // rAthena: point (offset 2, size 2)
	e.Str = data[4]  // rAthena: str (offset 4, size 1)
	e.StandardStr = data[5]  // rAthena: standardStr (offset 5, size 1)
	e.Agi = data[6]  // rAthena: agi (offset 6, size 1)
	e.StandardAgi = data[7]  // rAthena: standardAgi (offset 7, size 1)
	e.Vit = data[8]  // rAthena: vit (offset 8, size 1)
	e.StandardVit = data[9]  // rAthena: standardVit (offset 9, size 1)
	e.Int_ = data[10]  // rAthena: int_ (offset 10, size 1)
	e.StandardInt = data[11]  // rAthena: standardInt (offset 11, size 1)
	e.Dex = data[12]  // rAthena: dex (offset 12, size 1)
	e.StandardDex = data[13]  // rAthena: standardDex (offset 13, size 1)
	e.Luk = data[14]  // rAthena: luk (offset 14, size 1)
	e.StandardLuk = data[15]  // rAthena: standardLuk (offset 15, size 1)
	e.AttPower = leI16(data, 16)  // rAthena: attPower (offset 16, size 2)
	e.RefiningPower = leI16(data, 18)  // rAthena: refiningPower (offset 18, size 2)
	e.Max_mattPower = leI16(data, 20)  // rAthena: max_mattPower (offset 20, size 2)
	e.Min_mattPower = leI16(data, 22)  // rAthena: min_mattPower (offset 22, size 2)
	e.ItemdefPower = leI16(data, 24)  // rAthena: itemdefPower (offset 24, size 2)
	e.PlusdefPower = leI16(data, 26)  // rAthena: plusdefPower (offset 26, size 2)
	e.MdefPower = leI16(data, 28)  // rAthena: mdefPower (offset 28, size 2)
	e.PlusmdefPower = leI16(data, 30)  // rAthena: plusmdefPower (offset 30, size 2)
	e.HitSuccessValue = leI16(data, 32)  // rAthena: hitSuccessValue (offset 32, size 2)
	e.AvoidSuccessValue = leI16(data, 34)  // rAthena: avoidSuccessValue (offset 34, size 2)
	e.PlusAvoidSuccessValue = leI16(data, 36)  // rAthena: plusAvoidSuccessValue (offset 36, size 2)
	e.CriticalSuccessValue = leI16(data, 38)  // rAthena: criticalSuccessValue (offset 38, size 2)
	e.ASPD = leI16(data, 40)  // rAthena: ASPD (offset 40, size 2)
	e.PlusASPD = leI16(data, 42)  // rAthena: plusASPD (offset 42, size 2)
	return e
}

