// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// ZcStartCapture_0x019E decodes a 0x019E packet (struct PACKET_ZC_START_CAPTURE).
func ZcStartCapture_0x019E(data []byte, packetver uint32) events.ZcStartCapture {
	var e events.ZcStartCapture
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
	return e
}

