// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcShortcutKeyList_0x02B9 decodes a 0x02B9 packet (struct PACKET_ZC_SHORTCUT_KEY_LIST).
func ZcShortcutKeyList_0x02B9(data []byte, packetver uint32) events.ZcShortcutKeyList {
	var e events.ZcShortcutKeyList
	if packetver >= 20191120 {
		e.Rotate = int8(data[2])  // rAthena: rotate (offset 2, size 1)
		e.Tab = leI16(data, 3)  // rAthena: tab (offset 3, size 2)
		e.Hotkey = data[5:271]  // rAthena: hotkey (offset 5, size 266)
	} else if packetver >= 20141022 {
		e.Rotate = int8(data[2])  // rAthena: rotate (offset 2, size 1)
		e.Hotkey = data[3:269]  // rAthena: hotkey (offset 3, size 266)
	} else if packetver >= 20110824 {
		e.Hotkey = data[2:268]  // rAthena: hotkey (offset 2, size 266)
	} else {
		e.Hotkey = data[2:191]  // rAthena: hotkey (offset 2, size 189)
	}
	return e
}

