// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// ZcSearchStoreInfoAck_0x0836 decodes a 0x0836 packet (struct PACKET_ZC_SEARCH_STORE_INFO_ACK).
func ZcSearchStoreInfoAck_0x0836(data []byte, packetver uint32) events.ZcSearchStoreInfoAck {
	var e events.ZcSearchStoreInfoAck
	_ = packetver
	e.FirstPage = data[4]  // rAthena: firstPage (offset 4, size 1)
	e.Items = data[7:]  // rAthena: items (offset 7, size 0)
	e.NextPage = data[5]  // rAthena: nextPage (offset 5, size 1)
	e.PacketLength = leI16(data, 2)  // rAthena: packetLength (offset 2, size 2)
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	e.UsesCount = data[6]  // rAthena: usesCount (offset 6, size 1)
	return e
}

