// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcSpirits2_0x01E1 decodes a 0x01E1 packet (struct PACKET_ZC_SPIRITS2).
func ZcSpirits2_0x01E1(data []byte, packetver uint32) events.ZcSpirits2 {
	var e events.ZcSpirits2
	_ = packetver
	e.AID = leU32(data, 2)  // rAthena: AID (offset 2, size 4)
	e.Num = leI16(data, 6)  // rAthena: num (offset 6, size 2)
	return e
}

