// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// ZcSpecialpopup_0x0BBE decodes a 0x0BBE packet (struct PACKET_ZC_SPECIALPOPUP).
func ZcSpecialpopup_0x0BBE(data []byte, packetver uint32) events.ZcSpecialpopup {
	var e events.ZcSpecialpopup
	_ = packetver
	e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
	e.PpId = leI32(data, 2)  // rAthena: ppId (offset 2, size 4)
	return e
}

