// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcUiOpen_0x0A38 decodes a 0x0A38 packet (struct PACKET_ZC_UI_OPEN).
func ZcUiOpen_0x0A38(data []byte, packetver uint32) events.ZcUiOpen {
	var e events.ZcUiOpen
	if packetver >= 20171122 {
		e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
		e.UIType = int8(data[2])  // rAthena: UIType (offset 2, size 1)
	} else {
		e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
		e.UIType = int8(data[2])  // rAthena: UIType (offset 2, size 1)
	}
	return e
}

