// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/ragnarok-go-client/pkg/events"

// ZcUpdateGdid_0x016C decodes a 0x016C packet (struct PACKET_ZC_UPDATE_GDID).
func ZcUpdateGdid_0x016C(data []byte, packetver uint32) events.ZcUpdateGdid {
	var e events.ZcUpdateGdid
	if packetver >= 20220216 {
		e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
		e.GuildId = leU32(data, 2)  // rAthena: guildId (offset 2, size 4)
		e.InterSid = leI32(data, 15)  // rAthena: interSid (offset 15, size 4)
		e.IsMaster = data[14]  // rAthena: isMaster (offset 14, size 1)
		e.Mode = leU32(data, 10)  // rAthena: mode (offset 10, size 4)
	} else {
		e.PacketType = leI16(data, 0)  // rAthena: PacketType (offset 0, size 2)
		e.GuildId = leU32(data, 2)  // rAthena: guildId (offset 2, size 4)
		e.InterSid = leI32(data, 15)  // rAthena: interSid (offset 15, size 4)
		e.IsMaster = data[14]  // rAthena: isMaster (offset 14, size 1)
		e.Mode = leU32(data, 10)  // rAthena: mode (offset 10, size 4)
	}
	return e
}

