// Code generated by internal/codegen. DO NOT EDIT.

package decode

import "github.com/lenaxia/rathena-client/pkg/events"

// ZcViewCamerainfo_0x0A78 decodes a 0x0A78 packet (struct PACKET_ZC_VIEW_CAMERAINFO).
func ZcViewCamerainfo_0x0A78(data []byte, packetver uint32) events.ZcViewCamerainfo {
	var e events.ZcViewCamerainfo
	_ = packetver
	e.Action = int8(data[2])  // rAthena: action (offset 2, size 1)
	e.PacketType = leI16(data, 0)  // rAthena: packetType (offset 0, size 2)
	return e
}

