// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/ragnarok-go-client/pkg/send"
)

// EncodeActorAction encodes a ActorAction packet for the appropriate packet version.
func EncodeActorAction(req send.ActorAction, packetver uint32) [7]byte {
	switch {
	case packetver >= 20200401: // 0x085A
		var p [7]byte
		p[0] = 0x5a; p[1] = 0x08
			p[6] = req.Type  // rAthena: Action
	leU32Put(		p[2:], req.TargetID)  // rAthena: TargetGID
		return p
	}
	panic("EncodeActorAction: no matching packetver implementation — unimplemented")
}
