// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCaExeHashcheck encodes a 0x0204 (PACKET_CA_EXE_HASHCHECK) packet for sending to the server.
func EncodeCaExeHashcheck(req send.CaExeHashcheck, packetver uint32) [18]byte {
	var p [18]byte
	// Packet ID: 0x0204 (little-endian)
	p[0] = 0x04
	p[1] = 0x02
	copy(p[2:18], req.Hash)  // rAthena: hash
	_ = packetver
	return p
}
