// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCaLogin2 encodes a 0x01DD (PACKET_CA_LOGIN2) packet for sending to the server.
func EncodeCaLogin2(req send.CaLogin2, packetver uint32) [47]byte {
	var p [47]byte
	// Packet ID: 0x01DD (little-endian)
	p[0] = 0xdd
	p[1] = 0x01
	leU32Put(p[2:], req.Version)     // rAthena: version
	copy(p[6:30], req.Username)      // rAthena: username
	copy(p[30:], req.PasswordMD5[:]) // rAthena: passwordMD5
	p[46] = req.Clienttype           // rAthena: clienttype
	_ = packetver
	return p
}
