// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCaReqHash encodes a 0x01DB (PACKET_CA_REQ_HASH) packet for sending to the server.
func EncodeCaReqHash(req send.CaReqHash, packetver uint32) [2]byte {
	var p [2]byte
	// Packet ID: 0x01DB (little-endian)
	p[0] = 0xdb
	p[1] = 0x01
	_ = packetver
	return p
}
