// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCaSsoLoginReq encodes a 0x0825 (PACKET_CA_SSO_LOGIN_REQ) packet for sending to the server.
func EncodeCaSsoLoginReq(req send.CaSsoLoginReq, packetver uint32) [92]byte {
	var p [92]byte
	// Packet ID: 0x0825 (little-endian)
	p[0] = 0x25
	p[1] = 0x08
	leU16Put(p[2:], uint16(req.PacketLength))  // rAthena: packetLength
	leU32Put(p[4:], req.Version)  // rAthena: version
	p[8] = req.Clienttype  // rAthena: clienttype
	copy(p[9:33], req.Username)  // rAthena: username
	copy(p[33:60], req.Password)  // rAthena: password
	copy(p[60:77], req.Mac)  // rAthena: mac
	copy(p[77:92], req.Ip)  // rAthena: ip
	copy(p[92:92], req.Token)  // rAthena: token
	_ = packetver
	return p
}
