// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeChangeCart encodes a 0x01AF (SYNTH_CZ_CHANGE_CART) packet for sending to the server.
func EncodeChangeCart(req send.ChangeCart, packetver uint32) [4]byte {
	var p [4]byte
	// Packet ID: 0x01AF (little-endian)
	p[0] = 0xaf
	p[1] = 0x01
	leU16Put(p[2:], req.Num)  // rAthena: num
	_ = packetver
	return p
}
