// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCharDelete encodes a 0x0068 (PACKET_CH_DELETE_CHAR) packet for sending to the server.
func EncodeCharDelete(req send.CharDelete, packetver uint32) [46]byte {
	var p [46]byte
	// Packet ID: 0x0068 (little-endian)
	p[0] = 0x68
	p[1] = 0x00
	leU32Put(p[2:], req.CID) // rAthena: CID
	copy(p[6:46], req.Key)   // rAthena: key
	_ = packetver
	return p
}
