// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCharacterMove encodes a 0x035F (SYNTH_CZ_REQUEST_MOVE2) packet for sending to the server.
func EncodeCharacterMove(req send.CharacterMove, packetver uint32) [5]byte {
	var p [5]byte
	// Packet ID: 0x035F (little-endian)
	p[0] = 0x5f
	p[1] = 0x03
	copy(p[2:], req.Coords[:])  // rAthena: dest
	_ = packetver
	return p
}
