// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCloseVending encodes a 0x012E (SYNTH_CZ_CLOSE_AUCTION) packet for sending to the server.
func EncodeCloseVending(req send.CloseVending, packetver uint32) [2]byte {
	var p [2]byte
	// Packet ID: 0x012E (little-endian)
	p[0] = 0x2e
	p[1] = 0x01
	_ = packetver
	return p
}
