// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCloseStorage encodes a 0x00F7 (SYNTH_CZ_CLOSE_STORE) packet for sending to the server.
func EncodeCloseStorage(req send.CloseStorage, packetver uint32) [2]byte {
	var p [2]byte
	// Packet ID: 0x00F7 (little-endian)
	p[0] = 0xf7
	p[1] = 0x00
	_ = packetver
	return p
}
