// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCzAdvancedStatusChange encodes a 0x0B24 (PACKET_CZ_ADVANCED_STATUS_CHANGE) packet for sending to the server.
func EncodeCzAdvancedStatusChange(req send.CzAdvancedStatusChange, packetver uint32) [6]byte {
	var p [6]byte
	// Packet ID: 0x0B24 (little-endian)
	p[0] = 0x24
	p[1] = 0x0b
	leU16Put(p[2:], uint16(req.Type))  // rAthena: type
	leU16Put(p[4:], uint16(req.Amount))  // rAthena: amount
	_ = packetver
	return p
}
