// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/ragnarok-go-client/pkg/send"
)

// EncodeCzCloseUiEnchant encodes a 0x0BA0 (PACKET_CZ_CLOSE_UI_ENCHANT) packet for sending to the server.
func EncodeCzCloseUiEnchant(req send.CzCloseUiEnchant, packetver uint32) [2]byte {
	var p [2]byte
	// Packet ID: 0x0BA0 (little-endian)
	p[0] = 0xa0
	p[1] = 0x0b
	leU16Put(p[0:], uint16(req.PacketType))  // rAthena: PacketType
	_ = packetver
	return p
}
