// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/ragnarok-go-client/pkg/send"
)

// EncodeCzCloseRefiningUi encodes a 0x0AA4 (PACKET_CZ_CLOSE_REFINING_UI) packet for sending to the server.
func EncodeCzCloseRefiningUi(req send.CzCloseRefiningUi, packetver uint32) [2]byte {
	var p [2]byte
	// Packet ID: 0x0AA4 (little-endian)
	p[0] = 0xa4
	p[1] = 0x0a
	leU16Put(p[0:], uint16(req.PacketType))  // rAthena: packetType
	_ = packetver
	return p
}
