// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCzCloseReformUi encodes a 0x0B90 (PACKET_CZ_CLOSE_REFORM_UI) packet for sending to the server.
func EncodeCzCloseReformUi(req send.CzCloseReformUi, packetver uint32) [2]byte {
	var p [2]byte
	// Packet ID: 0x0B90 (little-endian)
	p[0] = 0x90
	p[1] = 0x0b
	_ = packetver
	return p
}
