// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCzCheckname1 encodes a 0x0A13 (PACKET_CZ_CHECKNAME1) packet for sending to the server.
func EncodeCzCheckname1(req send.CzCheckname1, packetver uint32) [26]byte {
	var p [26]byte
	// Packet ID: 0x0A13 (little-endian)
	p[0] = 0x13
	p[1] = 0x0a
	copy(p[2:26], req.Name)  // rAthena: Name
	_ = packetver
	return p
}
