// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCzCheckname2 encodes a 0x0B97 (PACKET_CZ_CHECKNAME2) packet for sending to the server.
func EncodeCzCheckname2(req send.CzCheckname2, packetver uint32) [27]byte {
	var p [27]byte
	// Packet ID: 0x0B97 (little-endian)
	p[0] = 0x97
	p[1] = 0x0b
	copy(p[2:26], req.Name) // rAthena: Name
	p[26] = req.Own_char    // rAthena: own_char
	_ = packetver
	return p
}
