// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/ragnarok-go-client/pkg/send"
)

// EncodeCzGradeEnchantRequest encodes a 0x0B5B (PACKET_CZ_GRADE_ENCHANT_REQUEST) packet for sending to the server.
func EncodeCzGradeEnchantRequest(req send.CzGradeEnchantRequest, packetver uint32) [14]byte {
	var p [14]byte
	// Packet ID: 0x0B5B (little-endian)
	p[0] = 0x5b
	p[1] = 0x0b
	leU16Put(p[0:], uint16(req.PacketType))  // rAthena: PacketType
	p[8] = uint8(req.Blessing_flag)  // rAthena: blessing_flag
	leU16Put(p[2:], uint16(req.Index))  // rAthena: index
	p[13] = uint8(req.Protect_flag)  // rAthena: protect_flag
	leU32Put(p[4:], uint32(req.Material_index))  // rAthena: material_index
	leU32Put(p[9:], uint32(req.Blessing_amount))  // rAthena: blessing_amount
	_ = packetver
	return p
}
