// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCzJoinGuild encodes a 0x016B (PACKET_CZ_JOIN_GUILD) packet for sending to the server.
func EncodeCzJoinGuild(req send.CzJoinGuild, packetver uint32) [10]byte {
	var p [10]byte
	// Packet ID: 0x016B (little-endian)
	p[0] = 0x6b
	p[1] = 0x01
	leU32Put(p[2:], req.Guild_id)       // rAthena: guild_id
	leU32Put(p[6:], uint32(req.Answer)) // rAthena: answer
	_ = packetver
	return p
}
