// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCzMoveItemFromBodyToCart encodes a 0x0126 (PACKET_CZ_MOVE_ITEM_FROM_BODY_TO_CART) packet for sending to the server.
func EncodeCzMoveItemFromBodyToCart(req send.CzMoveItemFromBodyToCart, packetver uint32) [8]byte {
	var p [8]byte
	// Packet ID: 0x0126 (little-endian)
	p[0] = 0x26
	p[1] = 0x01
	leU16Put(p[2:], uint16(req.Index)) // rAthena: index
	copy(p[4:], req.Count)             // rAthena: count
	_ = packetver
	return p
}
