// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/ragnarok-go-client/pkg/send"
)

// EncodeCzNpcExpandedBarterMarketClose encodes a 0x0B58 (PACKET_CZ_NPC_EXPANDED_BARTER_MARKET_CLOSE) packet for sending to the server.
func EncodeCzNpcExpandedBarterMarketClose(req send.CzNpcExpandedBarterMarketClose, packetver uint32) [2]byte {
	var p [2]byte
	// Packet ID: 0x0B58 (little-endian)
	p[0] = 0x58
	p[1] = 0x0b
	leU16Put(p[0:], uint16(req.PacketType))  // rAthena: packetType
	_ = packetver
	return p
}
