// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCzNpcBarterMarketClose encodes a 0x0B12 (PACKET_CZ_NPC_BARTER_MARKET_CLOSE) packet for sending to the server.
func EncodeCzNpcBarterMarketClose(req send.CzNpcBarterMarketClose, packetver uint32) [2]byte {
	var p [2]byte
	// Packet ID: 0x0B12 (little-endian)
	p[0] = 0x12
	p[1] = 0x0b
	leU16Put(p[0:], uint16(req.PacketType))  // rAthena: packetType
	_ = packetver
	return p
}
