// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCzNpcMarketPurchase encodes a 0x09D6 (PACKET_CZ_NPC_MARKET_PURCHASE) packet for sending to the server.
func EncodeCzNpcMarketPurchase(req send.CzNpcMarketPurchase, packetver uint32) [4]byte {
	var p [4]byte
	// Packet ID: 0x09D6 (little-endian)
	p[0] = 0xd6
	p[1] = 0x09
	leU16Put(p[2:], uint16(req.PacketLength))  // rAthena: PacketLength
	leU16Put(p[0:], uint16(req.PacketType))  // rAthena: PacketType
	copy(p[4:], req.List)  // rAthena: list
	_ = packetver
	return p
}
