// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/ragnarok-go-client/pkg/send"
)

// EncodeCzPcPurchaseItemlistFrommc2 encodes a 0x0801 (PACKET_CZ_PC_PURCHASE_ITEMLIST_FROMMC2) packet for sending to the server.
func EncodeCzPcPurchaseItemlistFrommc2(req send.CzPcPurchaseItemlistFrommc2, packetver uint32) [12]byte {
	var p [12]byte
	// Packet ID: 0x0801 (little-endian)
	p[0] = 0x01
	p[1] = 0x08
	leU32Put(p[4:], req.AID)  // rAthena: AID
	leU32Put(p[8:], req.UniqueID)  // rAthena: UniqueID
	copy(p[12:], req.List)  // rAthena: list
	leU16Put(p[2:], uint16(req.PacketLength))  // rAthena: packetLength
	leU16Put(p[0:], uint16(req.PacketType))  // rAthena: packetType
	_ = packetver
	return p
}
