// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCzReqCashBargainSaleItemInfo encodes a 0x09AC (PACKET_CZ_REQ_CASH_BARGAIN_SALE_ITEM_INFO) packet for sending to the server.
func EncodeCzReqCashBargainSaleItemInfo(req send.CzReqCashBargainSaleItemInfo, packetver uint32) [10]byte {
	var p [10]byte
	// Packet ID: 0x09AC (little-endian)
	p[0] = 0xac
	p[1] = 0x09
	leU16Put(p[2:], uint16(req.PacketLength)) // rAthena: packetLength
	leU32Put(p[4:], req.AID)                  // rAthena: AID
	leU16Put(p[8:], req.ItemId)               // rAthena: itemId
	_ = packetver
	return p
}
