// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCzReqPreviewMacroDetector encodes a 0x0A69 (PACKET_CZ_REQ_PREVIEW_MACRO_DETECTOR) packet for sending to the server.
func EncodeCzReqPreviewMacroDetector(req send.CzReqPreviewMacroDetector, packetver uint32) [6]byte {
	var p [6]byte
	// Packet ID: 0x0A69 (little-endian)
	p[0] = 0x69
	p[1] = 0x0a
	copy(p[2:], req.CaptchaID)  // rAthena: captchaID
	_ = packetver
	return p
}
