// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCzReqOpenMsgboxExtendBodyitemSize encodes a 0x0B14 (PACKET_CZ_REQ_OPEN_MSGBOX_EXTEND_BODYITEM_SIZE) packet for sending to the server.
func EncodeCzReqOpenMsgboxExtendBodyitemSize(req send.CzReqOpenMsgboxExtendBodyitemSize, packetver uint32) [2]byte {
	var p [2]byte
	// Packet ID: 0x0B14 (little-endian)
	p[0] = 0x14
	p[1] = 0x0b
	leU16Put(p[0:], uint16(req.PacketType))  // rAthena: packetType
	_ = packetver
	return p
}
