// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/ragnarok-go-client/pkg/send"
)

// EncodeCzReqRefining encodes a 0x0AA3 (PACKET_CZ_REQ_REFINING) packet for sending to the server.
func EncodeCzReqRefining(req send.CzReqRefining, packetver uint32) [7]byte {
	var p [7]byte
	// Packet ID: 0x0AA3 (little-endian)
	p[0] = 0xa3
	p[1] = 0x0a
	p[6] = uint8(req.BlacksmithBlessing)  // rAthena: blacksmithBlessing
	leU16Put(p[2:], uint16(req.Index))  // rAthena: index
	leU32Put(p[4:], req.ItemId)  // rAthena: itemId
	leU16Put(p[0:], uint16(req.PacketType))  // rAthena: packetType
	_ = packetver
	return p
}
