// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCzRequestRandomEnchant encodes a 0x0B9B (PACKET_CZ_REQUEST_RANDOM_ENCHANT) packet for sending to the server.
func EncodeCzRequestRandomEnchant(req send.CzRequestRandomEnchant, packetver uint32) [12]byte {
	var p [12]byte
	// Packet ID: 0x0B9B (little-endian)
	p[0] = 0x9b
	p[1] = 0x0b
	leU16Put(p[0:], uint16(req.PacketType))  // rAthena: PacketType
	// req.EnchantGroup: unhandled type int64 for rAthena: enchant_group
	leU16Put(p[10:], uint16(req.Index))  // rAthena: index
	_ = packetver
	return p
}
