// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/ragnarok-go-client/pkg/send"
)

// EncodeCzReqGuildEmblemImg1 encodes a 0x0151 (PACKET_CZ_REQ_GUILD_EMBLEM_IMG1) packet for sending to the server.
func EncodeCzReqGuildEmblemImg1(req send.CzReqGuildEmblemImg1, packetver uint32) [6]byte {
	var p [6]byte
	// Packet ID: 0x0151 (little-endian)
	p[0] = 0x51
	p[1] = 0x01
	leU32Put(p[2:], uint32(req.GuildId))  // rAthena: guild_id
	leU16Put(p[0:], uint16(req.PacketType))  // rAthena: packetType
	_ = packetver
	return p
}
