// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCzReqBanGuild encodes a 0x015B (PACKET_CZ_REQ_BAN_GUILD) packet for sending to the server.
func EncodeCzReqBanGuild(req send.CzReqBanGuild, packetver uint32) [54]byte {
	var p [54]byte
	// Packet ID: 0x015B (little-endian)
	p[0] = 0x5b
	p[1] = 0x01
	leU32Put(p[2:], req.Guild_id) // rAthena: guild_id
	leU32Put(p[6:], req.AID)      // rAthena: AID
	leU32Put(p[10:], req.CID)     // rAthena: CID
	copy(p[14:54], req.Message)   // rAthena: message
	_ = packetver
	return p
}
