// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/ragnarok-go-client/pkg/send"
)

// EncodeCzReqPlayerAidInRange encodes a 0x0A6C (PACKET_CZ_REQ_PLAYER_AID_IN_RANGE) packet for sending to the server.
func EncodeCzReqPlayerAidInRange(req send.CzReqPlayerAidInRange, packetver uint32) [7]byte {
	var p [7]byte
	// Packet ID: 0x0A6C (little-endian)
	p[0] = 0x6c
	p[1] = 0x0a
	leU16Put(p[0:], uint16(req.PacketType))  // rAthena: PacketType
	p[6] = uint8(req.RadiusRange)  // rAthena: RadiusRange
	leU16Put(p[2:], uint16(req.XPos))  // rAthena: xPos
	leU16Put(p[4:], uint16(req.YPos))  // rAthena: yPos
	_ = packetver
	return p
}
