// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/ragnarok-go-client/pkg/send"
)

// EncodeCzReqRandomCombineItem encodes a 0x0A4F (PACKET_CZ_REQ_RANDOM_COMBINE_ITEM) packet for sending to the server.
func EncodeCzReqRandomCombineItem(req send.CzReqRandomCombineItem, packetver uint32) [6]byte {
	var p [6]byte
	// Packet ID: 0x0A4F (little-endian)
	p[0] = 0x4f
	p[1] = 0x0a
	leU32Put(p[4:], uint32(req.ItemId))  // rAthena: itemId
	copy(p[6:], req.Items)  // rAthena: items
	leU16Put(p[2:], uint16(req.PacketLength))  // rAthena: packetLength
	leU16Put(p[0:], uint16(req.PacketType))  // rAthena: packetType
	_ = packetver
	return p
}
