// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCzRequestUpgradeEnchant encodes a 0x0B9D (PACKET_CZ_REQUEST_UPGRADE_ENCHANT) packet for sending to the server.
func EncodeCzRequestUpgradeEnchant(req send.CzRequestUpgradeEnchant, packetver uint32) [14]byte {
	var p [14]byte
	// Packet ID: 0x0B9D (little-endian)
	p[0] = 0x9d
	p[1] = 0x0b
	// req.Enchant_group: unhandled type int64 for rAthena: enchant_group
	leU16Put(p[10:], uint16(req.Index))  // rAthena: index
	leU16Put(p[12:], uint16(req.Slot))  // rAthena: slot
	_ = packetver
	return p
}
