// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCzReqDisorganizeGuild encodes a 0x015D (PACKET_CZ_REQ_DISORGANIZE_GUILD) packet for sending to the server.
func EncodeCzReqDisorganizeGuild(req send.CzReqDisorganizeGuild, packetver uint32) [42]byte {
	var p [42]byte
	// Packet ID: 0x015D (little-endian)
	p[0] = 0x5d
	p[1] = 0x01
	copy(p[2:42], req.Key)  // rAthena: key
	_ = packetver
	return p
}
