// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCzRequestPerfectEnchant encodes a 0x0B9C (PACKET_CZ_REQUEST_PERFECT_ENCHANT) packet for sending to the server.
func EncodeCzRequestPerfectEnchant(req send.CzRequestPerfectEnchant, packetver uint32) [16]byte {
	var p [16]byte
	// Packet ID: 0x0B9C (little-endian)
	p[0] = 0x9c
	p[1] = 0x0b
	// req.Enchant_group: unhandled type int64 for rAthena: enchant_group
	leU16Put(p[10:], uint16(req.Index))  // rAthena: index
	leU32Put(p[12:], req.ITID)  // rAthena: ITID
	_ = packetver
	return p
}
