// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCzReqGuildEmblemImg2 encodes a 0x0B1E (PACKET_CZ_REQ_GUILD_EMBLEM_IMG2) packet for sending to the server.
func EncodeCzReqGuildEmblemImg2(req send.CzReqGuildEmblemImg2, packetver uint32) [14]byte {
	var p [14]byte
	// Packet ID: 0x0B1E (little-endian)
	p[0] = 0x1e
	p[1] = 0x0b
	leU32Put(p[2:], uint32(req.Guild_id))  // rAthena: guild_id
	leU32Put(p[6:], uint32(req.Emblem_id)) // rAthena: emblem_id
	leU32Put(p[10:], uint32(req.Unused))   // rAthena: unused
	_ = packetver
	return p
}
