// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCzReqJoinGuild encodes a 0x0168 (PACKET_CZ_REQ_JOIN_GUILD) packet for sending to the server.
func EncodeCzReqJoinGuild(req send.CzReqJoinGuild, packetver uint32) [14]byte {
	var p [14]byte
	// Packet ID: 0x0168 (little-endian)
	p[0] = 0x68
	p[1] = 0x01
	leU32Put(p[2:], req.AID)  // rAthena: AID
	leU32Put(p[6:], req.Inviter_AID)  // rAthena: inviter_AID
	leU32Put(p[10:], req.Inviter_CID)  // rAthena: inviter_CID
	_ = packetver
	return p
}
