// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCzReqTakeoffEquipAll encodes a CzReqTakeoffEquipAll packet for the appropriate packet version.
func EncodeCzReqTakeoffEquipAll(req send.CzReqTakeoffEquipAll, packetver uint32) []byte {
	switch {
	case packetver >= 20230906: // 0x0BF5
		p := make([]byte, 6)
		p[0] = 0xf5
		p[1] = 0x0b
		leU32Put(p[2:], req.Location) // rAthena: location
		return p
	case packetver >= 20210818: // 0x0BAD
		p := make([]byte, 2)
		p[0] = 0xad
		p[1] = 0x0b
		return p
	}
	panic("EncodeCzReqTakeoffEquipAll: no matching packetver implementation — unimplemented")
}
