// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCzRandomUpgradeItemUiClose encodes a 0x0AB5 (PACKET_CZ_RANDOM_UPGRADE_ITEM_UI_CLOSE) packet for sending to the server.
func EncodeCzRandomUpgradeItemUiClose(req send.CzRandomUpgradeItemUiClose, packetver uint32) [2]byte {
	var p [2]byte
	// Packet ID: 0x0AB5 (little-endian)
	p[0] = 0xb5
	p[1] = 0x0a
	leU16Put(p[0:], uint16(req.PacketType))  // rAthena: packetType
	_ = packetver
	return p
}
