// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCzRequestResetEnchant encodes a 0x0B9E (PACKET_CZ_REQUEST_RESET_ENCHANT) packet for sending to the server.
func EncodeCzRequestResetEnchant(req send.CzRequestResetEnchant, packetver uint32) [12]byte {
	var p [12]byte
	// Packet ID: 0x0B9E (little-endian)
	p[0] = 0x9e
	p[1] = 0x0b
	// req.Enchant_group: unhandled type int64 for rAthena: enchant_group
	leU16Put(p[10:], uint16(req.Index)) // rAthena: index
	_ = packetver
	return p
}
