// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCzShortcutkeybarRotate1 encodes a 0x0A01 (PACKET_CZ_SHORTCUTKEYBAR_ROTATE1) packet for sending to the server.
func EncodeCzShortcutkeybarRotate1(req send.CzShortcutkeybarRotate1, packetver uint32) [3]byte {
	var p [3]byte
	// Packet ID: 0x0A01 (little-endian)
	p[0] = 0x01
	p[1] = 0x0a
	p[2] = req.Rowshift  // rAthena: rowshift
	_ = packetver
	return p
}
