// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCzShortcutKeyChange1 encodes a 0x02BA (PACKET_CZ_SHORTCUT_KEY_CHANGE1) packet for sending to the server.
func EncodeCzShortcutKeyChange1(req send.CzShortcutKeyChange1, packetver uint32) [11]byte {
	var p [11]byte
	// Packet ID: 0x02BA (little-endian)
	p[0] = 0xba
	p[1] = 0x02
	// Hotkey: complex mapping "func() []byte { bytes, _ := packet.hotkey.ToPacket(0); if len(bytes) > 2 { return bytes[2:] }; return []byte{} }()" — implement manually
	leU16Put(p[2:], req.Index)  // rAthena: index
	leU16Put(p[0:], uint16(req.PacketType))  // rAthena: packetType
	_ = packetver
	return p
}
