// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeCzUseSkillEnd encodes a 0x0B11 (PACKET_CZ_USE_SKILL_END) packet for sending to the server.
func EncodeCzUseSkillEnd(req send.CzUseSkillEnd, packetver uint32) [4]byte {
	var p [4]byte
	// Packet ID: 0x0B11 (little-endian)
	p[0] = 0x11
	p[1] = 0x0b
	leU16Put(p[2:], uint16(req.SkillId))  // rAthena: skillId
	_ = packetver
	return p
}
