// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/ragnarok-go-client/pkg/send"
)

// EncodeCzViewCamerainfo encodes a 0x0A77 (PACKET_CZ_VIEW_CAMERAINFO) packet for sending to the server.
func EncodeCzViewCamerainfo(req send.CzViewCamerainfo, packetver uint32) [15]byte {
	var p [15]byte
	// Packet ID: 0x0A77 (little-endian)
	p[0] = 0x77
	p[1] = 0x0a
	p[2] = uint8(req.Action)  // rAthena: action
	leU16Put(p[0:], uint16(req.PacketType))  // rAthena: packetType
	_ = packetver
	return p
}
