// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeDealTrade encodes a 0x00EF (SYNTH_CZ_EXEC_EXCHANGE_ITEM) packet for sending to the server.
func EncodeDealTrade(req send.DealTrade, packetver uint32) [2]byte {
	var p [2]byte
	// Packet ID: 0x00EF (little-endian)
	p[0] = 0xef
	p[1] = 0x00
	_ = packetver
	return p
}
