// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/ragnarok-go-client/pkg/send"
)

// EncodeDealFinalize encodes a move request for the appropriate packet version.
func EncodeDealFinalize(req send.DealFinalize, packetver uint32) []byte {
	switch {
	}
	return nil
}
