// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeDealAddOther encodes a 0x00E8 (PACKET_CZ_ADD_EXCHANGE_ITEM) packet for sending to the server.
func EncodeDealAddOther(req send.DealAddOther, packetver uint32) [8]byte {
	var p [8]byte
	// Packet ID: 0x00E8 (little-endian)
	p[0] = 0xe8
	p[1] = 0x00
	leU16Put(p[2:], req.Index)          // rAthena: index
	leU32Put(p[4:], uint32(req.Amount)) // rAthena: amount
	_ = packetver
	return p
}
