// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeEquipItem encodes a 0x00A9 (PACKET_CZ_REQ_WEAR_EQUIP) packet for sending to the server.
func EncodeEquipItem(req send.EquipItem, packetver uint32) [6]byte {
	var p [6]byte
	// Packet ID: 0x00A9 (little-endian)
	p[0] = 0xa9
	p[1] = 0x00
	leU16Put(p[2:], req.Index)    // rAthena: index
	leU16Put(p[4:], req.Position) // rAthena: position
	_ = packetver
	return p
}
