// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeFriendsAdd encodes a 0x0202 (SYNTH_CZ_ADD_FRIENDS) packet for sending to the server.
func EncodeFriendsAdd(req send.FriendsAdd, packetver uint32) [26]byte {
	var p [26]byte
	// Packet ID: 0x0202 (little-endian)
	p[0] = 0x02
	p[1] = 0x02
	copy(p[2:26], req.Name)  // rAthena: name
	_ = packetver
	return p
}
