// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/ragnarok-go-client/pkg/send"
)

// EncodeGameLogin encodes a move request for the appropriate packet version.
func EncodeGameLogin(req send.GameLogin, packetver uint32) []byte {
	switch {
	}
	return nil
}
