// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeHomunculusMenu encodes a 0x022D (SYNTH_CZ_COMMAND_MER) packet for sending to the server.
func EncodeHomunculusMenu(req send.HomunculusMenu, packetver uint32) [5]byte {
	var p [5]byte
	// Packet ID: 0x022D (little-endian)
	p[0] = 0x2d
	p[1] = 0x02
	leU16Put(p[2:], req.HomId) // rAthena: homId
	p[4] = req.Action          // rAthena: action
	_ = packetver
	return p
}
