// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeIgnoreListReq encodes a 0x00D3 (SYNTH_CZ_REQ_IGNORE_LIST) packet for sending to the server.
func EncodeIgnoreListReq(req send.IgnoreListReq, packetver uint32) [2]byte {
	var p [2]byte
	// Packet ID: 0x00D3 (little-endian)
	p[0] = 0xd3
	p[1] = 0x00
	_ = packetver
	return p
}
