// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeInsertCard encodes a 0x017C (SYNTH_CZ_REQ_ITEMCOMPOSITION) packet for sending to the server.
func EncodeInsertCard(req send.InsertCard, packetver uint32) [6]byte {
	var p [6]byte
	// Packet ID: 0x017C (little-endian)
	p[0] = 0x7c
	p[1] = 0x01
	leU16Put(p[2:], req.Index_card)  // rAthena: index_card
	leU16Put(p[4:], req.Index_equip)  // rAthena: index_equip
	_ = packetver
	return p
}
