// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeItemUse encodes a 0x00A7 (SYNTH_CZ_USE_ITEM) packet for sending to the server.
func EncodeItemUse(req send.ItemUse, packetver uint32) [8]byte {
	var p [8]byte
	// Packet ID: 0x00A7 (little-endian)
	p[0] = 0xa7
	p[1] = 0x00
	leU16Put(p[2:], req.Index)  // rAthena: index
	leU32Put(p[4:], req.AID)  // rAthena: AID
	_ = packetver
	return p
}
