// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeMapLogin encodes a 0x0436 (SYNTH_CZ_ENTER) packet for sending to the server.
func EncodeMapLogin(req send.MapLogin, packetver uint32) [19]byte {
	var p [19]byte
	// Packet ID: 0x0436 (little-endian)
	p[0] = 0x36
	p[1] = 0x04
	leU32Put(p[2:], req.AID)  // rAthena: AID
	leU32Put(p[6:], req.GID)  // rAthena: GID
	leU32Put(p[10:], uint32(req.AuthCode))  // rAthena: AuthCode
	leU32Put(p[14:], req.ClientTime)  // rAthena: clientTime
	p[18] = req.Sex  // rAthena: Sex
	_ = packetver
	return p
}
