// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/ragnarok-go-client/pkg/send"
)

// EncodeMapLoaded encodes a move request for the appropriate packet version.
func EncodeMapLoaded(req send.MapLoaded, packetver uint32) []byte {
	switch {
	}
	return nil
}
