// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeMarketPurchase encodes a 0x09D6 (PACKET_CZ_NPC_MARKET_PURCHASE) packet for sending to the server.
func EncodeMarketPurchase(req send.MarketPurchase, packetver uint32) []byte {
	p := make([]byte, 4+len(req.List))
	// Packet ID: 0x09D6 (little-endian)
	p[0] = 0xd6
	p[1] = 0x09
	leU16Put(p[2:], uint16(len(p)))  // rAthena: PacketLength (computed)
	copy(p[4:], req.List)  // rAthena: list
	_ = packetver
	return p
}
