// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeMoveToStorage encodes a 0x00F3 (SYNTH_CZ_MOVE_ITEM_FROM_BODY_TO_STORE) packet for sending to the server.
func EncodeMoveToStorage(req send.MoveToStorage, packetver uint32) [8]byte {
	var p [8]byte
	// Packet ID: 0x00F3 (little-endian)
	p[0] = 0xf3
	p[1] = 0x00
	leU16Put(p[2:], req.Index)  // rAthena: index
	leU32Put(p[4:], req.Amount)  // rAthena: amount
	_ = packetver
	return p
}
