// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeNpcMenuResponse encodes a 0x00B8 (SYNTH_CZ_CHOOSE_MENU) packet for sending to the server.
func EncodeNpcMenuResponse(req send.NpcMenuResponse, packetver uint32) [7]byte {
	var p [7]byte
	// Packet ID: 0x00B8 (little-endian)
	p[0] = 0xb8
	p[1] = 0x00
	leU32Put(p[2:], req.NpcID)  // rAthena: NpcID
	p[6] = req.Select  // rAthena: select
	_ = packetver
	return p
}
