// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeNpcTalkClose encodes a 0x0146 (PACKET_CZ_CLOSE_DIALOG) packet for sending to the server.
func EncodeNpcTalkClose(req send.NpcTalkClose, packetver uint32) [6]byte {
	var p [6]byte
	// Packet ID: 0x0146 (little-endian)
	p[0] = 0x46
	p[1] = 0x01
	leU32Put(p[2:], req.GID)  // rAthena: GID
	_ = packetver
	return p
}
