// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeNpcTalkText encodes a 0x01D5 (PACKET_CZ_INPUT_EDITDLGSTR) packet for sending to the server.
func EncodeNpcTalkText(req send.NpcTalkText, packetver uint32) [8]byte {
	var p [8]byte
	// Packet ID: 0x01D5 (little-endian)
	p[0] = 0xd5
	p[1] = 0x01
	leU16Put(p[2:], req.PacketSize)  // rAthena: packetSize
	leU32Put(p[4:], uint32(req.GID))  // rAthena: GID
	copy(p[8:8], req.Value)  // rAthena: value
	_ = packetver
	return p
}
