// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeNpcTalkNumber encodes a 0x0143 (PACKET_CZ_INPUT_EDITDLG) packet for sending to the server.
func EncodeNpcTalkNumber(req send.NpcTalkNumber, packetver uint32) [10]byte {
	var p [10]byte
	// Packet ID: 0x0143 (little-endian)
	p[0] = 0x43
	p[1] = 0x01
	leU32Put(p[2:], req.GID)  // rAthena: GID
	leU32Put(p[6:], uint32(req.Value))  // rAthena: value
	_ = packetver
	return p
}
