// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeNpcTradeQuit encodes a 0x09D4 (SYNTH_CZ_NPC_TRADE_QUIT) packet for sending to the server.
func EncodeNpcTradeQuit(req send.NpcTradeQuit, packetver uint32) [2]byte {
	var p [2]byte
	// Packet ID: 0x09D4 (little-endian)
	p[0] = 0xd4
	p[1] = 0x09
	_ = packetver
	return p
}
