// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeNpcTalkContinue encodes a 0x00B9 (SYNTH_CZ_REQ_NEXT_SCRIPT) packet for sending to the server.
func EncodeNpcTalkContinue(req send.NpcTalkContinue, packetver uint32) [6]byte {
	var p [6]byte
	// Packet ID: 0x00B9 (little-endian)
	p[0] = 0xb9
	p[1] = 0x00
	leU32Put(p[2:], req.NpcID)  // rAthena: NpcID
	_ = packetver
	return p
}
