// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodePartyChangeOption encodes a 0x0102 (SYNTH_CZ_CHANGE_GROUPEXPOPTION) packet for sending to the server.
func EncodePartyChangeOption(req send.PartyChangeOption, packetver uint32) [6]byte {
	var p [6]byte
	// Packet ID: 0x0102 (little-endian)
	p[0] = 0x02
	p[1] = 0x01
	leU32Put(p[2:], req.Option) // rAthena: option
	_ = packetver
	return p
}
