// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodePartyCreate encodes a 0x00F9 (PACKET_CZ_MAKE_GROUP) packet for sending to the server.
func EncodePartyCreate(req send.PartyCreate, packetver uint32) [26]byte {
	var p [26]byte
	// Packet ID: 0x00F9 (little-endian)
	p[0] = 0xf9
	p[1] = 0x00
	copy(p[2:26], req.Name) // rAthena: name
	_ = packetver
	return p
}
