// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodePartyLeave encodes a 0x0100 (PACKET_CZ_REQ_LEAVE_GROUP) packet for sending to the server.
func EncodePartyLeave(req send.PartyLeave, packetver uint32) [2]byte {
	var p [2]byte
	// Packet ID: 0x0100 (little-endian)
	p[0] = 0x00
	p[1] = 0x01
	_ = packetver
	return p
}
