// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodePublicChat encodes a PublicChat packet for the appropriate packet version.
func EncodePublicChat(req send.PublicChat, packetver uint32) []byte {
	switch {
	}
	panic("EncodePublicChat: no matching packetver implementation — unimplemented")
}
