// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeRequestMemo encodes a 0x011D (SYNTH_CZ_REMEMBER_WARPPOINT) packet for sending to the server.
func EncodeRequestMemo(req send.RequestMemo, packetver uint32) [2]byte {
	var p [2]byte
	// Packet ID: 0x011D (little-endian)
	p[0] = 0x1d
	p[1] = 0x01
	_ = packetver
	return p
}
