// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeRequestBuySellList encodes a 0x00C5 (PACKET_CZ_ACK_SELECT_DEALTYPE) packet for sending to the server.
func EncodeRequestBuySellList(req send.RequestBuySellList, packetver uint32) [7]byte {
	var p [7]byte
	// Packet ID: 0x00C5 (little-endian)
	p[0] = 0xc5
	p[1] = 0x00
	leU32Put(p[2:], req.GID) // rAthena: GID
	p[6] = req.Type          // rAthena: type
	_ = packetver
	return p
}
