// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeRequestAction encodes a 0x0089 (SYNTH_CZ_REQUEST_ACT) packet for sending to the server.
func EncodeRequestAction(req send.RequestAction, packetver uint32) [7]byte {
	var p [7]byte
	// Packet ID: 0x0089 (little-endian)
	p[0] = 0x89
	p[1] = 0x00
	leU32Put(p[2:], req.TargetGID)  // rAthena: TargetGID
	p[6] = req.Action  // rAthena: Action
	_ = packetver
	return p
}
