// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeSelectCharacter encodes a 0x0066 (PACKET_CH_SELECT_CHAR) packet for sending to the server.
func EncodeSelectCharacter(req send.SelectCharacter, packetver uint32) [3]byte {
	var p [3]byte
	// Packet ID: 0x0066 (little-endian)
	p[0] = 0x66
	p[1] = 0x00
	p[2] = req.Slot  // rAthena: slot
	_ = packetver
	return p
}
