// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeSelectAccessibleMap encodes a 0x0841 (PACKET_CH_SELECT_ACCESSIBLE_MAPNAME) packet for sending to the server.
func EncodeSelectAccessibleMap(req send.SelectAccessibleMap, packetver uint32) [4]byte {
	var p [4]byte
	// Packet ID: 0x0841 (little-endian)
	p[0] = 0x41
	p[1] = 0x08
	p[2] = uint8(req.Slot)  // rAthena: slot
	p[3] = uint8(req.Mapnumber)  // rAthena: mapnumber
	_ = packetver
	return p
}
