// Manually implemented — not generated by codegen.
// PACKET_CZ_REQUEST_CHAT has no C struct definition in rAthena; it is a
// variable-length packet parsed manually in clif.cpp.
//
// Wire format: uint16 packetType | uint16 packetLength | "Name : Message\0"
// packetver < 20040726 → 0x008C
// packetver >= 20040726 → 0x00F3

package encode

import (
	"encoding/binary"

	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeSendChat encodes a SendChat packet (CZ_REQUEST_CHAT).
// Returns a variable-length byte slice.
func EncodeSendChat(req send.SendChat, packetver uint32) []byte {
	var pktID uint16
	if packetver >= 20040726 {
		pktID = 0x00F3
	} else {
		pktID = 0x008C
	}
	text := req.Name + " : " + req.Message + "\x00"
	totalLen := 4 + len(text)
	buf := make([]byte, totalLen)
	binary.LittleEndian.PutUint16(buf[0:], pktID)
	binary.LittleEndian.PutUint16(buf[2:], uint16(totalLen))
	copy(buf[4:], text)
	return buf
}
