// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeSendChat encodes a SendChat packet for the appropriate packet version.
func EncodeSendChat(req send.SendChat, packetver uint32) []byte {
	switch {
	}
	panic("EncodeSendChat: no matching packetver implementation — unimplemented")
}
