// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeShopSell encodes a 0x00C9 (PACKET_CZ_PC_SELL_ITEMLIST) packet for sending to the server.
func EncodeShopSell(req send.ShopSell, packetver uint32) [4]byte {
	var p [4]byte
	// Packet ID: 0x00C9 (little-endian)
	p[0] = 0xc9
	p[1] = 0x00
	leU16Put(p[2:], uint16(req.PacketLength))  // rAthena: packetLength
	copy(p[4:], req.SellList)  // rAthena: sellList
	_ = packetver
	return p
}
