// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeSkillUseLocation encodes a 0x0116 (SYNTH_CZ_USE_SKILL_TOGROUND) packet for sending to the server.
func EncodeSkillUseLocation(req send.SkillUseLocation, packetver uint32) [10]byte {
	var p [10]byte
	// Packet ID: 0x0116 (little-endian)
	p[0] = 0x16
	p[1] = 0x01
	leU16Put(p[2:], req.SkillLevel)  // rAthena: skillLevel
	leU16Put(p[4:], req.SkillID)  // rAthena: skillID
	leU16Put(p[6:], req.XPos)  // rAthena: xPos
	leU16Put(p[8:], req.YPos)  // rAthena: yPos
	_ = packetver
	return p
}
