// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeSkillUp encodes a 0x0112 (SYNTH_CZ_UPGRADE_SKILLLEVEL) packet for sending to the server.
func EncodeSkillUp(req send.SkillUp, packetver uint32) [4]byte {
	var p [4]byte
	// Packet ID: 0x0112 (little-endian)
	p[0] = 0x12
	p[1] = 0x01
	leU16Put(p[2:], req.Skill_id) // rAthena: skill_id
	_ = packetver
	return p
}
