// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeTimeSyncResponse encodes a TimeSyncResponse packet for the appropriate packet version.
func EncodeTimeSyncResponse(req send.TimeSyncResponse, packetver uint32) []byte {
	switch {
	}
	panic("EncodeTimeSyncResponse: no matching packetver implementation — unimplemented")
}
