// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeUseCard encodes a 0x017A (SYNTH_CZ_REQ_ITEMCOMPOSITION_LIST) packet for sending to the server.
func EncodeUseCard(req send.UseCard, packetver uint32) [4]byte {
	var p [4]byte
	// Packet ID: 0x017A (little-endian)
	p[0] = 0x7a
	p[1] = 0x01
	leU16Put(p[2:], req.Index)  // rAthena: index
	_ = packetver
	return p
}
