// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeVendingListReq encodes a 0x0130 (SYNTH_CZ_REQ_CLICK_TO_BUYING_STORE) packet for sending to the server.
func EncodeVendingListReq(req send.VendingListReq, packetver uint32) [6]byte {
	var p [6]byte
	// Packet ID: 0x0130 (little-endian)
	p[0] = 0x30
	p[1] = 0x01
	leU32Put(p[2:], req.AID) // rAthena: AID
	_ = packetver
	return p
}
