// Code generated by internal/codegen. DO NOT EDIT.

package encode

import (
	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeWeaponRefine encodes a 0x0222 (SYNTH_CZ_REQ_WEAPONREFINE) packet for sending to the server.
func EncodeWeaponRefine(req send.WeaponRefine, packetver uint32) [6]byte {
	var p [6]byte
	// Packet ID: 0x0222 (little-endian)
	p[0] = 0x22
	p[1] = 0x02
	leU32Put(p[2:], req.Index)  // rAthena: index
	_ = packetver
	return p
}
