// Manually implemented — not generated by codegen.
// CZ_WISPER (0x0096) has no C struct definition in rAthena; it is a
// variable-length packet parsed manually in clif.cpp via
// clif_process_message with whisperFormat=true.
//
// Wire format: uint16 packetType | uint16 packetLength | char target[24] | "Message\0"
// The target field is exactly NAME_LENGTH (24) bytes, NUL-padded.

package encode

import (
	"encoding/binary"

	"github.com/lenaxia/rathena-client/pkg/send"
)

// EncodeWhisper encodes a Whisper packet (CZ_WISPER / 0x0096).
// Returns a variable-length byte slice.
func EncodeWhisper(req send.Whisper, _ uint32) []byte {
	const pktID uint16 = 0x0096
	const nameLen = 24
	msg := req.Message + "\x00"
	totalLen := 4 + nameLen + len(msg)
	buf := make([]byte, totalLen)
	binary.LittleEndian.PutUint16(buf[0:], pktID)
	binary.LittleEndian.PutUint16(buf[2:], uint16(totalLen))
	// Copy target name into fixed 24-byte field (NUL-padded by make)
	copy(buf[4:4+nameLen], req.Target)
	copy(buf[4+nameLen:], msg)
	return buf
}
