// Code generated by internal/codegen. DO NOT EDIT.

package events

// AcAcceptLogin is the event emitted when a ac_accept_login packet is received.
// Login accepted - returns session tokens and character server list
type AcAcceptLogin struct {
	AccountID uint32 // Account ID assigned by server
	ServerInfo []byte // Variable-length character server list. Handler must parse based on packet version: 32 bytes per entry for packet 0x00...
	LastLoginIP uint32 // Last login IP address (4-byte binary)
	LastLoginTime string // Last login timestamp string (26 bytes, null-terminated)
	SessionID uint32 // Session token part 1 - used for character server authentication
	SessionID2 uint32 // Session token part 2 - used for character server authentication
	AccountSex uint8 // Account gender (0=female, 1=male, 2=server)
}
