// Code generated by internal/codegen. DO NOT EDIT.

package events

// AccountId is the event emitted when a account_id packet is received.
// Account ID confirmation from map server
type AccountId struct {
	AccountID uint32 // Account ID
}
