// Code generated by internal/codegen. DO NOT EDIT.

package events

// ActorConnected is the event emitted when a actor_connected packet is received.
// Actor appeared/connected (entering viewport, spawning)
type ActorConnected struct {
	EmblemID int16 // Guild emblem version
	ID uint32 // Actor unique identifier
	GuildID uint32 // Guild ID
	PosDir [3]byte // Packed position and direction (3 bytes: x, y, direction)
	Opt1 int16 // Body state (stone, freeze, stun, sleep)
	Lv int16 // Character level
	ClothesColor int16 // Clothes color ID
	Option int32 // Effect state flags
	HairColor int16 // Hair color ID
	HairStyle int16 // Hair style ID
	Lowhead int16 // Lower headgear sprite
	HeadDir int16 // Head direction
	Midhead int16 // Middle headgear sprite
	Tophead int16 // Upper headgear sprite
	Opt2 int16 // Health state (poison, curse, silence, etc)
	Stance uint8 // PK mode status
	Type int16 // Job class ID
	Manner int16 // Manner points
	Sex uint8 // Gender (0=female, 1=male)
	Shield int16 // Shield sprite ID
	WalkSpeed int16 // Movement speed
	Opt3 uint8 // Virtue/effect state
	Weapon int16 // Weapon sprite ID
	XSize uint8 // X size for collision
	YSize uint8 // Y size for collision
	HP int32 // Current HP
	MaxHP int32 // Maximum HP
	Name string // Entity name
	IsBoss uint8 // Boss monster flag
	Opt4 int16 // Body style
	Costume int16 // Garment/robe sprite
	ObjectType uint8 // Entity type (0=PC, 5=MOB, etc.)
	CharID uint32 // Character ID (for players)
	Font int16 // Font type
}
