// Code generated by internal/codegen. DO NOT EDIT.

package events

// AddExchangeItem is the event emitted when a add_exchange_item packet is received.
// Item added to trade window
type AddExchangeItem struct {
	Amount int32 // Item amount in trade
	Damaged uint8 // Whether item is broken/damaged
	Grade uint8 // grade field (uint8)
	Identified uint8 // Whether item is identified
	ID uint32 // Item ID in trade
	ItemType uint8 // itemType field (uint8)
	Location uint32 // Equipment position or inventory location
	Look uint16 // look field (uint16)
	Refine uint8 // Item refine/upgrade level
	Slot []byte // Card slots or item options
}
