// Code generated by internal/codegen. DO NOT EDIT.

package events

// BankingOpen is the event emitted when a banking_open packet is received.
// Banking window opened
type BankingOpen struct {
	Result uint8 // Open result (0=failed, 1=success)
}
