// Code generated by internal/codegen. DO NOT EDIT.

package events

// CaExeHashcheck is the event emitted when a ca_exe_hashcheck packet is received.
// CA_EXE_HASHCHECK packet (PACKET_CA_EXE_HASHCHECK)
type CaExeHashcheck struct {
	Hash string // hash field
	PacketType int16 // packetType field
}
