// Code generated by internal/codegen. DO NOT EDIT.

package events

// CaLogin2 is the event emitted when a ca_login2 packet is received.
// Login with MD5 hashed password (CA_LOGIN2)
type CaLogin2 struct {
	MasterVersion uint8 // Client type identifier (see CLIENT_TYPES)
	PacketType int16 // packetType field
	PasswordSaltedMd5 string // MD5 hashed password (16 bytes)
	Version uint32 // Client version number
}
