// Code generated by internal/codegen. DO NOT EDIT.

package events

// CaReqHash is the event emitted when a ca_req_hash packet is received.
// CA_REQ_HASH packet (PACKET_CA_REQ_HASH)
type CaReqHash struct {
	PacketType int16 // packetType field
}
