// Code generated by internal/codegen. DO NOT EDIT.

package events

// CastCancelled is the event emitted when a cast_cancelled packet is received.
// Cast cancelled/interrupted notification
type CastCancelled struct {
	ID uint32 // Actor whose cast was cancelled
}
