// Code generated by internal/codegen. DO NOT EDIT.

package events

// CharacterBlocked is the event emitted for the character_blocked action.
type CharacterBlocked struct {
	PacketLength int16
	Characters []byte
}
