// Code generated by internal/codegen. DO NOT EDIT.

package events

// CharacterMoves is the event emitted when a character_moves packet is received.
// Player character is moving
type CharacterMoves struct {
	MoveData [6]byte // Packed coordinates: from_x, from_y, to_x, to_y (6 bytes)
	Time uint32 // Server tick when movement started
}
