// Code generated by internal/codegen. DO NOT EDIT.

package events

// CharacterServerRefused is the event emitted for the character_server_refused action.
type CharacterServerRefused struct {
	Error uint8
}
