// Code generated by internal/codegen. DO NOT EDIT.

package events

// CharCreate is the event emitted when a char_create packet is received.
// Character creation request with stats and appearance
type CharCreate struct {
	Agi uint8 // Starting AGI stat value
	Dex uint8 // Starting DEX stat value
	Hair_color uint16 // Hair color ID
	Hair_style uint16 // Hair style ID
	Int uint8 // Starting INT stat value
	Luk uint8 // Starting LUK stat value
	Name string // Character name (24 bytes, null-terminated)
	Slot uint8 // Character slot to create in (0-based index)
	Str uint8 // Starting STR stat value
	Vit uint8 // Starting VIT stat value
}
