// Code generated by internal/codegen. DO NOT EDIT.

package events

// CharLogin is the event emitted when a char_login packet is received.
// Character selection request (client → char server)
type CharLogin struct {
	Slot uint8 // Character slot number to select (0-based index)
}
