// Code generated by internal/codegen. DO NOT EDIT.

package events

// ChatMessage is the event emitted when a chat_message packet is received.
// Public chat message received
type ChatMessage struct {
	SenderID uint32 // Actor ID of message sender
	Message string // Chat message text
}
