// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzApproximateActor is the event emitted when a cz_approximate_actor packet is received.
// CZ_APPROXIMATE_ACTOR packet (PACKET_CZ_APPROXIMATE_ACTOR)
type CzApproximateActor struct {
	PacketType int16 // PacketType field
	MasterGID uint32 // masterGID field
	Unused1 uint16 // unused1 field
	Unused2 uint8 // unused2 field
}
