// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzAdvancedStatusChange is the event emitted when a cz_advanced_status_change packet is received.
// CZ_ADVANCED_STATUS_CHANGE packet (PACKET_CZ_ADVANCED_STATUS_CHANGE)
type CzAdvancedStatusChange struct {
	StatusType int16 // Type of status to change (STR, AGI, VIT, INT, DEX, LUK)
	Amount int16 // Amount to increase status by
}
