// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzCheckname1 is the event emitted when a cz_checkname1 packet is received.
// CZ_CHECKNAME1 packet (PACKET_CZ_CHECKNAME1)
type CzCheckname1 struct {
	Name string // Name field
	PacketType int16 // PacketType field
}
