// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzCloseReformUi is the event emitted when a cz_close_reform_ui packet is received.
// CZ_CLOSE_REFORM_UI packet (PACKET_CZ_CLOSE_REFORM_UI)
type CzCloseReformUi struct {
	PacketType int16 // PacketType field
}
