// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzCloseUiStylingshop is the event emitted when a cz_close_ui_stylingshop packet is received.
// CZ_CLOSE_UI_STYLINGSHOP packet (PACKET_CZ_CLOSE_UI_STYLINGSHOP)
type CzCloseUiStylingshop struct {
	PacketType int16 // packetType field
}
