// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzCheckname2 is the event emitted when a cz_checkname2 packet is received.
// CZ_CHECKNAME2 packet (PACKET_CZ_CHECKNAME2)
type CzCheckname2 struct {
	Name string // Name field
	PacketType int16 // PacketType field
	OwnChar uint8 // own_char field
}
