// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzCloseUiEnchant is the event emitted when a cz_close_ui_enchant packet is received.
// CZ_CLOSE_UI_ENCHANT packet (PACKET_CZ_CLOSE_UI_ENCHANT)
type CzCloseUiEnchant struct {
	PacketType int16 // PacketType field
}
