// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzCloseMsgboxExtendBodyitemSize is the event emitted when a cz_close_msgbox_extend_bodyitem_size packet is received.
// CZ_CLOSE_MSGBOX_EXTEND_BODYITEM_SIZE packet (PACKET_CZ_CLOSE_MSGBOX_EXTEND_BODYITEM_SIZE)
type CzCloseMsgboxExtendBodyitemSize struct {
	PacketType int16 // packetType field
}
