// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzDynamicnpcCreateRequest is the event emitted when a cz_dynamicnpc_create_request packet is received.
// CZ_DYNAMICNPC_CREATE_REQUEST packet (PACKET_CZ_DYNAMICNPC_CREATE_REQUEST)
type CzDynamicnpcCreateRequest struct {
	PacketType uint16 // PacketType field
}
