// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzItemReform is the event emitted when a cz_item_reform packet is received.
// CZ_ITEM_REFORM packet (PACKET_CZ_ITEM_REFORM)
type CzItemReform struct {
	ITID int32 // ITID field
	PacketType int16 // PacketType field
	Index int16 // index field
}
