// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzInventoryTab is the event emitted when a cz_inventory_tab packet is received.
// CZ_INVENTORY_TAB packet (PACKET_CZ_INVENTORY_TAB)
type CzInventoryTab struct {
	Index int16 // Item inventory index
	Favorite bool // Whether item is marked as favorite
}
