// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzMoveItemFromBodyToCart is the event emitted when a cz_move_item_from_body_to_cart packet is received.
// CZ_MOVE_ITEM_FROM_BODY_TO_CART packet (PACKET_CZ_MOVE_ITEM_FROM_BODY_TO_CART)
type CzMoveItemFromBodyToCart struct {
	PacketType int16 // PacketType field
	Index int16 // index field
}
