// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzPcPurchaseItemlistFrommc is the event emitted when a cz_pc_purchase_itemlist_frommc packet is received.
// CZ_PC_PURCHASE_ITEMLIST_FROMMC packet (PACKET_CZ_PC_PURCHASE_ITEMLIST_FROMMC)
type CzPcPurchaseItemlistFrommc struct {
	AID uint32 // AID field
	List []byte // list field
	PacketLength int16 // packetLength field
	PacketType int16 // packetType field
}
