// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzPartyConfig is the event emitted when a cz_party_config packet is received.
// CZ_PARTY_CONFIG packet (PACKET_CZ_PARTY_CONFIG)
type CzPartyConfig struct {
	PacketType int16 // packetType field
	RefuseInvite uint8 // refuseInvite field
}
