// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzRodexReturn is the event emitted when a cz_rodex_return packet is received.
// CZ_RODEX_RETURN packet (PACKET_CZ_RODEX_RETURN)
type CzRodexReturn struct {
	MailID uint32 // Mail message ID to return to sender
}
