// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzReqItemrepair1 is the event emitted when a cz_req_itemrepair1 packet is received.
// CZ_REQ_ITEMREPAIR1 packet (PACKET_CZ_REQ_ITEMREPAIR1)
type CzReqItemrepair1 struct {
	Item []byte // item field
	PacketType int16 // packetType field
}
