// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzRequestUpgradeEnchant is the event emitted when a cz_request_upgrade_enchant packet is received.
// CZ_REQUEST_UPGRADE_ENCHANT packet (PACKET_CZ_REQUEST_UPGRADE_ENCHANT)
type CzRequestUpgradeEnchant struct {
	PacketType int16 // PacketType field
	EnchantGroup int64 // enchant_group field
	Index int16 // index field
	Slot int16 // slot field
}
