// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzReqJoinGuild is the event emitted when a cz_req_join_guild packet is received.
// CZ_REQ_JOIN_GUILD packet (PACKET_CZ_REQ_JOIN_GUILD)
type CzReqJoinGuild struct {
	GuildID uint32 // Guild ID to join
	Flag int32 // Accept (1) or reject (0) guild invitation
}
