// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzRandomCombineItemUiClose is the event emitted when a cz_random_combine_item_ui_close packet is received.
// CZ_RANDOM_COMBINE_ITEM_UI_CLOSE packet (PACKET_CZ_RANDOM_COMBINE_ITEM_UI_CLOSE)
type CzRandomCombineItemUiClose struct {
	PacketType int16 // packetType field
}
