// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzRequestResetEnchant is the event emitted when a cz_request_reset_enchant packet is received.
// CZ_REQUEST_RESET_ENCHANT packet (PACKET_CZ_REQUEST_RESET_ENCHANT)
type CzRequestResetEnchant struct {
	PacketType int16 // PacketType field
	Enchant_group int64 // enchant_group field
	Index int16 // index field
}
