// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzReqExpelGroupMember is the event emitted when a cz_req_expel_group_member packet is received.
// CZ_REQ_EXPEL_GROUP_MEMBER packet (PACKET_CZ_REQ_EXPEL_GROUP_MEMBER)
type CzReqExpelGroupMember struct {
	AccountID uint32 // Account ID of party member to expel
	CharacterName string // Character name to expel from party
}
