// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzReqGuildEmblemImg1 is the event emitted when a cz_req_guild_emblem_img1 packet is received.
// CZ_REQ_GUILD_EMBLEM_IMG1 packet (PACKET_CZ_REQ_GUILD_EMBLEM_IMG1)
type CzReqGuildEmblemImg1 struct {
	Guild_id int32 // guild_id field
	PacketType int16 // packetType field
}
