// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzReqApplyBargainSaleItem is the event emitted when a cz_req_apply_bargain_sale_item packet is received.
// CZ_REQ_APPLY_BARGAIN_SALE_ITEM packet (PACKET_CZ_REQ_APPLY_BARGAIN_SALE_ITEM)
type CzReqApplyBargainSaleItem struct {
	AccountID uint32 // Account ID
	ItemID uint16 // Item ID to apply bargain sale to
	Amount uint32 // Sale price amount
	StartTime uint32 // Sale start time (unix timestamp)
	Hours uint8 // Duration of sale in hours
}
