// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzRequestRandomEnchant is the event emitted when a cz_request_random_enchant packet is received.
// CZ_REQUEST_RANDOM_ENCHANT packet (PACKET_CZ_REQUEST_RANDOM_ENCHANT)
type CzRequestRandomEnchant struct {
	PacketType int16 // PacketType field
	Enchant_group int64 // enchant_group field
	Index int16 // index field
}
