// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzReqItemrepair2 is the event emitted when a cz_req_itemrepair2 packet is received.
// CZ_REQ_ITEMREPAIR2 packet (PACKET_CZ_REQ_ITEMREPAIR2)
type CzReqItemrepair2 struct {
	Item []byte // item field
	PacketType int16 // packetType field
}
