// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzReqMakingarrow is the event emitted when a cz_req_makingarrow packet is received.
// CZ_REQ_MAKINGARROW packet (PACKET_CZ_REQ_MAKINGARROW)
type CzReqMakingarrow struct {
	ItemID uint16 // Item ID for arrow making
}
