// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzRequestPerfectEnchant is the event emitted when a cz_request_perfect_enchant packet is received.
// CZ_REQUEST_PERFECT_ENCHANT packet (PACKET_CZ_REQUEST_PERFECT_ENCHANT)
type CzRequestPerfectEnchant struct {
	ITID uint32 // ITID field
	PacketType int16 // PacketType field
	EnchantGroup int64 // enchant_group field
	Index int16 // index field
}
