// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzReqJoinGroup is the event emitted when a cz_req_join_group packet is received.
// CZ_REQ_JOIN_GROUP packet (PACKET_CZ_REQ_JOIN_GROUP)
type CzReqJoinGroup struct {
	AccountID uint32 // Account ID to invite to party
}
