// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzReqUploadMacroDetector is the event emitted when a cz_req_upload_macro_detector packet is received.
// CZ_REQ_UPLOAD_MACRO_DETECTOR packet (PACKET_CZ_REQ_UPLOAD_MACRO_DETECTOR)
type CzReqUploadMacroDetector struct {
	PacketType int16 // PacketType field
	Answer string // answer field
	ImageSize uint16 // imageSize field
}
