// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzReqBanGuild is the event emitted when a cz_req_ban_guild packet is received.
// CZ_REQ_BAN_GUILD packet (PACKET_CZ_REQ_BAN_GUILD)
type CzReqBanGuild struct {
	GuildID uint32 // Guild ID
	AccountID uint32 // Account ID of member to ban
	CharacterID uint32 // Character ID of member to ban
	Message string // Reason for expulsion (40 bytes)
}
