// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzReqApplyMacroDetector is the event emitted when a cz_req_apply_macro_detector packet is received.
// CZ_REQ_APPLY_MACRO_DETECTOR packet (PACKET_CZ_REQ_APPLY_MACRO_DETECTOR)
type CzReqApplyMacroDetector struct {
	AID uint32 // AID field
	PacketType int16 // PacketType field
}
