// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzReqRandomCombineItem is the event emitted when a cz_req_random_combine_item packet is received.
// CZ_REQ_RANDOM_COMBINE_ITEM packet (PACKET_CZ_REQ_RANDOM_COMBINE_ITEM)
type CzReqRandomCombineItem struct {
	ItemId int32 // itemId field
	Items []byte // items field
	PacketLength int16 // packetLength field
	PacketType int16 // packetType field
}
