// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzReqRemaintime is the event emitted when a cz_req_remaintime packet is received.
// CZ_REQ_REMAINTIME packet (PACKET_CZ_REQ_REMAINTIME)
type CzReqRemaintime struct {
	PacketType int16 // packetType field
}
