// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzReqGuildEmblemImg2 is the event emitted when a cz_req_guild_emblem_img2 packet is received.
// CZ_REQ_GUILD_EMBLEM_IMG2 packet (PACKET_CZ_REQ_GUILD_EMBLEM_IMG2)
type CzReqGuildEmblemImg2 struct {
	EmblemId int32 // emblem_id field
	GuildId int32 // guild_id field
	PacketType int16 // packetType field
}
