// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzReqMergeItem is the event emitted when a cz_req_merge_item packet is received.
// CZ_REQ_MERGE_ITEM packet (PACKET_CZ_REQ_MERGE_ITEM)
type CzReqMergeItem struct {
	PacketLength int16 // Total packet length in bytes
	Indices []uint16 // Array of inventory indices to merge (variable length)
}
