// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzShortcutkeybarRotate2 is the event emitted when a cz_shortcutkeybar_rotate2 packet is received.
// CZ_SHORTCUTKEYBAR_ROTATE2 packet (PACKET_CZ_SHORTCUTKEYBAR_ROTATE2)
type CzShortcutkeybarRotate2 struct {
	PacketType int16 // packetType field
	Rowshift uint8 // rowshift field
	Tab uint16 // tab field
}
