// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzShortcutKeyChange1 is the event emitted when a cz_shortcut_key_change1 packet is received.
// CZ_SHORTCUT_KEY_CHANGE1 packet (PACKET_CZ_SHORTCUT_KEY_CHANGE1)
type CzShortcutKeyChange1 struct {
	Hotkey []byte // hotkey field (hotkey_data struct - 7 bytes: uint8 isSkill, uint32 id, uint16 count)
	Index uint16 // index field
	PacketType int16 // packetType field
}
