// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzUninstallation is the event emitted when a cz_uninstallation packet is received.
// CZ_UNINSTALLATION packet (PACKET_CZ_UNINSTALLATION)
type CzUninstallation struct {
	InstallationKind uint8 // InstallationKind field
	PacketType int16 // PacketType field
}
