// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzUseSkillEnd is the event emitted when a cz_use_skill_end packet is received.
// CZ_USE_SKILL_END packet (PACKET_CZ_USE_SKILL_END)
type CzUseSkillEnd struct {
	PacketType int16 // packetType field
	SkillId int16 // skillId field
}
