// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzUsePackageitem is the event emitted when a cz_use_packageitem packet is received.
// CZ_USE_PACKAGEITEM packet (PACKET_CZ_USE_PACKAGEITEM)
type CzUsePackageitem struct {
	AID uint32 // AID field
	BoxIndex uint32 // BoxIndex field
	PacketType int16 // PacketType field
	Index uint16 // index field
	ItemID uint32 // itemID field
}
