// Code generated by internal/codegen. DO NOT EDIT.

package events

// CzViewCamerainfo is the event emitted when a cz_view_camerainfo packet is received.
// CZ_VIEW_CAMERAINFO packet (PACKET_CZ_VIEW_CAMERAINFO)
type CzViewCamerainfo struct {
	Action int8 // action field
	PacketType int16 // packetType field
}
