// Code generated by internal/codegen. DO NOT EDIT.

package events

// DealAddOther is the event emitted when a deal_add_other packet is received.
// Client adds item to trade window
type DealAddOther struct {
	Amount uint32 // Amount of item to add to trade
	Index uint16 // Inventory index of item to add
}
