// Code generated by internal/codegen. DO NOT EDIT.

package events

// EntitySpawn is the event emitted when a entity_spawn packet is received.
// Entity (NPC/Monster) appears in view
type EntitySpawn struct {
	EntityID uint32 // Entity/Actor ID
	EntityType uint16 // Entity type/class
	PosDir [3]byte // Packed position and direction (3 bytes: x[10bit] + y[10bit] + dir[4bit]). Handler must unpack using makeCoordsDir pat...
}
