// Code generated by internal/codegen. DO NOT EDIT.

package events

// GameLogin is the event emitted when a game_login packet is received.
// Character server authentication (client → char server)
type GameLogin struct {
	AccountID uint32 // Account ID from login server (zero if absent for certain packet variants)
	SessionID uint32 // Session ID 1 (login_id1 from 0x0AC4, zero if absent)
	Clienttype uint16 // Client type or user level (zero if absent, often unused/0)
	SessionID2 uint32 // Session ID 2 (login_id2 from login server, zero if absent)
	Sex uint8 // Character sex (0=female, 1=male, 99=account sex, zero if absent)
}
