// Code generated by internal/codegen. DO NOT EDIT.

package events

// GameLogin is the event emitted when a game_login packet is received.
// Character server authentication (client → char server)
type GameLogin struct {
	AccountID uint32 // Account ID from login server (may be nil for certain packet variants)
	SessionID uint32 // Session ID 1 (login_id1 from 0x0AC4, may be nil)
	Clienttype uint16 // Client type or user level (may be nil, often unused/0)
	SessionID2 uint32 // Session ID 2 (login_id2 from login server, may be nil)
	Sex uint8 // Character sex (0=female, 1=male, 99=account sex, may be nil)
}
