// Code generated by internal/codegen. DO NOT EDIT.

package events

// InventoryItemAdded is the event emitted when a inventory_item_added packet is received.
// Item added to inventory (pickup result)
type InventoryItemAdded struct {
	Index uint16 // Inventory slot index
	Amount uint16 // Item quantity
	NameID uint32 // Item type ID from item_db
	Identified bool // Whether item is identified
	Broken bool // Whether item is broken
	Upgrade uint8 // Refining/upgrade level
	Cards []byte // Equipment card slots
	EquipLocation uint32 // Equipment location flags
	Type uint8 // Item type category
	Fail uint8 // Result code (0=success, other=failure)
}
