// Code generated by internal/codegen. DO NOT EDIT.

package events

// ItemDisappeared is the event emitted when a item_disappeared packet is received.
// Item disappeared from ground
type ItemDisappeared struct {
	ID uint32 // Item actor ID that disappeared
}
