// Code generated by internal/codegen. DO NOT EDIT.

package events

// ItemTake is the event emitted when a item_take packet is received.
// Request to pick up item from ground
type ItemTake struct {
	ID uint32 // Ground item entity ID to pick up
}
