// Code generated by internal/codegen. DO NOT EDIT.

package events

// ItemPickup is the event emitted when a item_pickup packet is received.
// Item added to inventory
type ItemPickup struct {
	ItemID uint32 // Item type ID from database
	Index uint16 // Inventory slot index
	Amount uint16 // Item quantity
	IsIdentified bool // Whether item is identified
	Result uint8 // Pickup result: 0=success, 1=inventory full, 2=too heavy, etc.
}
