// Code generated by internal/codegen. DO NOT EDIT.

package events

// ItemUnequip is the event emitted when a item_unequip packet is received.
// Unequip item to inventory
type ItemUnequip struct {
	Index uint16 // Inventory index of item to unequip
}
