// Code generated by internal/codegen. DO NOT EDIT.

package events

// Look is the event emitted when a look packet is received.
// Change character facing direction
type Look struct {
	Head uint8 // Head direction (0-7)
	Body uint8 // Body direction (0-7)
}
