// Code generated by internal/codegen. DO NOT EDIT.

package events

// MapLogin is the event emitted when a map_login packet is received.
// Map server login request (client → map server)
type MapLogin struct {
	AccountID uint32 // Account ID from login server
	SessionID int32 // Session authentication code (login_id1)
	CharID uint32 // Character ID from character selection
	PacketType int16 // Packet ID
	Sex uint8 // Character gender (0=female, 1=male)
	Tick uint32 // Client timestamp
}
