// Code generated by internal/codegen. DO NOT EDIT.

package events

// MapChanged is the event emitted for the map_changed action.
type MapChanged struct {
	MapName string
	XPos uint16
	YPos uint16
	Ip uint32
	Port uint16
	Domain string
}
