// Code generated by internal/codegen. DO NOT EDIT.

package events

// MasterLogin is the event emitted when a master_login packet is received.
// Login authentication packet (client → auth server)
type MasterLogin struct {
	MasterVersion uint8 // Client type identifier
	Password string // Account password (null-terminated, null-padded)
	Username string // Account username (null-terminated, null-padded)
	Version uint32 // Client version number
}
