// Code generated by internal/codegen. DO NOT EDIT.

package events

// MonsterHpUpdate is the event emitted when a monster_hp_update packet is received.
// Monster HP information update
type MonsterHpUpdate struct {
	ActorID uint32 // Monster actor GID
	CurrentHP uint32 // Current hit points
	MaxHP uint32 // Maximum hit points
}
