// Code generated by internal/codegen. DO NOT EDIT.

package events

// MonsterRangedAttack is the event emitted for the monster_ranged_attack action.
type MonsterRangedAttack struct {
	TargetAID uint32
	TargetXPos int16
	TargetYPos int16
	XPos int16
	YPos int16
	CurrentAttRange int16
}
