// Code generated by internal/codegen. DO NOT EDIT.

package events

// MoveFromStorage is the event emitted when a move_from_storage packet is received.
// Move item from storage to inventory
type MoveFromStorage struct {
	Index uint16 // Storage slot index
	Amount uint32 // Quantity to move
}
