// Code generated by internal/codegen. DO NOT EDIT.

package events

// NpcMenuResponse is the event emitted when a npc_menu_response packet is received.
// Respond to NPC menu selection
type NpcMenuResponse struct {
	NPCID uint32 // NPC actor ID
	MenuOption uint8 // Selected menu option (1-based index, 255=cancel)
}
