// Code generated by internal/codegen. DO NOT EDIT.

package events

// NpcTalkText is the event emitted when a npc_talk_text packet is received.
// Send text input to NPC dialog
type NpcTalkText struct {
	NPCID uint32 // NPC actor ID
	Text string // Text input (variable length string)
}
