// Code generated by internal/codegen. DO NOT EDIT.

package events

// NpcContact is the event emitted when a npc_contact packet is received.
// Initiate contact/talk with an NPC
type NpcContact struct {
	NPCID uint32 // NPC actor ID
	Type uint8 // Contact type (1=talk)
}
