// Code generated by internal/codegen. DO NOT EDIT.

package events

// PetEggList is the event emitted for the pet_egg_list action.
type PetEggList struct {
	PacketLength uint16
	Eggs         []byte
}
