// Code generated by internal/codegen. DO NOT EDIT.

package events

// PetInfo is the event emitted when a pet_info packet is received.
// Pet status information (hunger, intimacy, level)
type PetInfo struct {
	Accessory int16 // Pet accessory item ID
	PacketType int16 // PacketType field
	Type int8 // Update type flag
	Hungry int16 // Pet hunger level (0-100)
	Level int16 // Pet level
	Friendly int16 // Pet intimacy level (0-1000)
}
