// Code generated by internal/codegen. DO NOT EDIT.

package events

// PinCodeRequest is the event emitted for the pin_code_request action.
type PinCodeRequest struct {
	Seed uint32
	AID uint32
	Result uint16
}
