// Code generated by internal/codegen. DO NOT EDIT.

package events

// QuestUpdateMissionHunt is the event emitted when a quest_update_mission_hunt packet is received.
// Quest notification effect (quest started/completed)
type QuestUpdateMissionHunt struct {
	Active uint8 // Quest active state (1=active, 0=inactive)
	QuestID uint32 // Quest ID
}
