// Code generated by internal/codegen. DO NOT EDIT.

package events

// ReceivedCharactersPage is the event emitted when a received_characters_page packet is received.
// Paginated character list response
type ReceivedCharactersPage struct {
	Characters []byte // characters field (CHARACTER_INFO[])
}
