// Code generated by internal/codegen. DO NOT EDIT.

package events

// ReceivedCharactersInfo is the event emitted when a received_characters_info packet is received.
// Character slot information (normal, premium, billing slots)
type ReceivedCharactersInfo struct {
	Billing_slot uint8 // Billing character slots available
	Extension string // Extension data (20 bytes)
	Normal_slot uint8 // Normal character slots available
	Premium_slot uint8 // Premium character slots available
	Producible_slot uint8 // Producible character slots available
	Valid_slot uint8 // Total valid character slots
}
