// Code generated by internal/codegen. DO NOT EDIT.

package events

// ReplyPartyInvite is the event emitted when a reply_party_invite packet is received.
// Reply to party invitation
type ReplyPartyInvite struct {
	PartyID uint32 // Party ID
	Accept uint32 // Accept invitation (1=yes, 0=no)
}
