// Code generated by internal/codegen. DO NOT EDIT.

package events

// RequestTime is the event emitted when a request_time packet is received.
// Request server time synchronization
type RequestTime struct {
	ClientTick uint32 // Client timestamp for time synchronization
}
