// Code generated by internal/codegen. DO NOT EDIT.

package events

// ScNotifyBan is the event emitted when a sc_notify_ban packet is received.
// Character selection rejection/ban notification packet
type ScNotifyBan struct {
	PacketType int16 // packetType field
	Result uint8 // result field
}
