// Code generated by internal/codegen. DO NOT EDIT.

package events

// SelectAccessibleMap is the event emitted when a select_accessible_map packet is received.
// Client selects an accessible map from the list sent by 0x0840
type SelectAccessibleMap struct {
	Mapnumber int8 // Index of selected map from 0x0840 list
	PacketType int16 // Packet ID (0x0841)
	Slot int8 // Character slot number
}
