// Code generated by internal/codegen. DO NOT EDIT.

package events

// SelectCharacter is the event emitted when a select_character packet is received.
// Select a character to login
type SelectCharacter struct {
	Slot uint8 // Character slot number
}
