// Code generated by internal/codegen. DO NOT EDIT.

package events

// SendChat is the event emitted when a send_chat packet is received.
// Send public chat message
type SendChat struct {
	Message string // Chat message text (variable length)
}
