// Code generated by internal/codegen. DO NOT EDIT.

package events

// SkillPostDelay is the event emitted when a skill_post_delay packet is received.
// Skill cooldown notification
type SkillPostDelay struct {
	Time uint32 // Cooldown duration in milliseconds
	ID uint16 // Skill ID entering cooldown
}
