// Code generated by internal/codegen. DO NOT EDIT.

package events

// SkillAdd is the event emitted when a skill_add packet is received.
// Add new skill to skill list
type SkillAdd struct {
	Skill []byte // skill field (struct SKILLDATA)
}
