// Code generated by internal/codegen. DO NOT EDIT.

package events

// SkillUseLocation is the event emitted when a skill_use_location packet is received.
// Use skill on ground location (area skills)
type SkillUseLocation struct {
	SkillID uint16 // Skill ID to use
	Lv uint16 // Skill level to use
	X uint16 // Target X coordinate
	Y uint16 // Target Y coordinate
}
