// Code generated by internal/codegen. DO NOT EDIT.

package events

// SkillUseFailed is the event emitted for the skill_use_failed action.
type SkillUseFailed struct {
	SkillId uint16
	Btype int32
	ItemId uint32
	Flag uint8
	Cause uint8
}
