// Code generated by internal/codegen. DO NOT EDIT.

package events

// SkillUseFailed is the event emitted when a skill_use_failed packet is received.
// Skill usage failed notification
type SkillUseFailed struct {
	Btype uint32 // Basic type/category
	Cause uint8 // Failure reason code
	Flag uint8 // Additional flags
	ItemId uint16 // Required item ID (if applicable)
	SkillID uint16 // Skill ID that failed
}
