// Code generated by internal/codegen. DO NOT EDIT.

package events

// StorageItemAdd is the event emitted when a storage_item_add packet is received.
// Move item from inventory to storage
type StorageItemAdd struct {
	Amount uint32 // Amount of item to move to storage
	Index uint16 // Inventory index of item to move to storage
}
