// Code generated by internal/codegen. DO NOT EDIT.

package events

// Sync is the event emitted when a sync packet is received.
// Server time synchronization
type Sync struct {
	Time uint32 // Server tick/time for synchronization
}
