// Code generated by internal/codegen. DO NOT EDIT.

package events

// TimeSyncResponse is the event emitted when a time_sync_response packet is received.
// Respond to time sync request from server
type TimeSyncResponse struct {
	Time uint32 // Client tick time
}
