// Code generated by internal/codegen. DO NOT EDIT.

package events

// UnequipItem is the event emitted when a unequip_item packet is received.
// Unequip an item
type UnequipItem struct {
	Index uint16 // Inventory slot index
}
