// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcAckRandomCombineItem is the event emitted for the zc_ack_random_combine_item action.
type ZcAckRandomCombineItem struct {
	Result int16
}
