// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcAckItemrefining is the event emitted when a zc_ack_itemrefining packet is received.
// ZC_ACK_ITEMREFINING packet (PACKET_ZC_ACK_ITEMREFINING)
type ZcAckItemrefining struct {
	Result uint16 // Refining result code (0=success, 1=failure, 2=downgrade)
	ItemIndex uint16 // Inventory index of the item being refined
	RefineLevel uint16 // New refine level of the item after refining
}
