// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcAdventurerAgencyJoinReq is the event emitted for the zc_adventurer_agency_join_req action.
type ZcAdventurerAgencyJoinReq struct {
	GRID      []byte
	AID       []byte
	GroupName string
	Level     int16
	Job       int16
}
