// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcAutospelllist is the event emitted for the zc_autospelllist action.
type ZcAutospelllist struct {
	Skills []byte
	PacketLength int16
}
