// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcAckRandomUpgradeItem is the event emitted for the zc_ack_random_upgrade_item action.
type ZcAckRandomUpgradeItem struct {
	Result uint16
}
