// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcAcceptEnter is the event emitted for the zc_accept_enter action.
type ZcAcceptEnter struct {
	StartTime uint32
	PosDir [3]byte
	XSize uint8
	YSize uint8
	Font uint16
	Sex uint8
}
