// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcAutospelllist is the event emitted when a zc_autospelllist packet is received.
// ZC_AUTOSPELLLIST packet (PACKET_ZC_AUTOSPELLLIST)
type ZcAutospelllist struct {
	PacketType int16 // packetType field
}
