// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcAckTakeoffEquipAll is the event emitted when a zc_ack_takeoff_equip_all packet is received.
// ZC_ACK_TAKEOFF_EQUIP_ALL packet (PACKET_ZC_ACK_TAKEOFF_EQUIP_ALL)
type ZcAckTakeoffEquipAll struct {
	PacketType int16 // PacketType field
	Result uint8 // result field
}
