// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcAckReqnameallNpc is the event emitted when a zc_ack_reqnameall_npc packet is received.
// ZC_ACK_REQNAMEALL_NPC packet (PACKET_ZC_ACK_REQNAMEALL_NPC)
type ZcAckReqnameallNpc struct {
	Name string // NPC/Actor name
	ID uint32 // Actor/NPC ID
}
