// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcApplyMacroDetector is the event emitted when a zc_apply_macro_detector packet is received.
// ZC_APPLY_MACRO_DETECTOR packet (PACKET_ZC_APPLY_MACRO_DETECTOR)
type ZcApplyMacroDetector struct {
	PacketType int16 // PacketType field
	CaptchaKey []byte // Captcha key identifier (4-byte fixed array)
	ImageSize uint16 // imageSize field
}
