// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcAckItemrepair is the event emitted for the zc_ack_itemrepair action.
type ZcAckItemrepair struct {
	Index  uint16
	Result uint8
}
