// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcAckMergeItem is the event emitted when a zc_ack_merge_item packet is received.
// ZC_ACK_MERGE_ITEM packet (PACKET_ZC_ACK_MERGE_ITEM)
type ZcAckMergeItem struct {
	Amount int16 // amount field
	Index int16 // index field
	PacketType int16 // packetType field
	Reason uint8 // reason field
}
