// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcAckExtendBodyitemSize is the event emitted when a zc_ack_extend_bodyitem_size packet is received.
// ZC_ACK_EXTEND_BODYITEM_SIZE packet (PACKET_ZC_ACK_EXTEND_BODYITEM_SIZE)
type ZcAckExtendBodyitemSize struct {
	PacketType int16 // packetType field
	Result uint8 // result field
}
