// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcAckOpenMsgboxExtendBodyitemSize is the event emitted for the zc_ack_open_msgbox_extend_bodyitem_size action.
type ZcAckOpenMsgboxExtendBodyitemSize struct {
	Result uint8
	ItemId uint32
}
