// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcAckPreviewMacroDetector is the event emitted for the zc_ack_preview_macro_detector action.
type ZcAckPreviewMacroDetector struct {
	CaptchaFlag []byte
	ImageSize   uint16
	CaptchaKey  string
}
