// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcActionFailure is the event emitted when a zc_action_failure packet is received.
// ZC_ACTION_FAILURE packet (PACKET_ZC_ACTION_FAILURE)
type ZcActionFailure struct {
	PacketID uint16 // Packet identifier
	FailureType int16 // Type of action failure (0=no arrow, 1=overweight cant attack, 2=overweight cant skill, 3=arrow equipped)
}
