// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcAckMakeGroup is the event emitted when a zc_ack_make_group packet is received.
// ZC_ACK_MAKE_GROUP packet (PACKET_ZC_ACK_MAKE_GROUP)
type ZcAckMakeGroup struct {
	PacketType int16 // PacketType field
	Result int8 // result field
}
