// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcAddItemToCart is the event emitted for the zc_add_item_to_cart action.
type ZcAddItemToCart struct {
	Index int16
	Amount int32
	ItemId uint32
	ItemType uint8
	Identified uint8
	Damaged uint8
	Refine uint8
	Slot []byte
	Option_data []byte
	Grade uint8
}
