// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcAckPreviewMacroDetector is the event emitted when a zc_ack_preview_macro_detector packet is received.
// ZC_ACK_PREVIEW_MACRO_DETECTOR packet (PACKET_ZC_ACK_PREVIEW_MACRO_DETECTOR)
type ZcAckPreviewMacroDetector struct {
	PacketType int16 // PacketType field
	CaptchaKey []byte // Captcha key identifier (4-byte fixed array)
	ImageSize uint16 // imageSize field
}
