// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcBuyingStoreEntry is the event emitted for the zc_buying_store_entry action.
type ZcBuyingStoreEntry struct {
	MakerAID  uint32
	StoreName string
}
