// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcBroadcast is the event emitted for the zc_broadcast action.
type ZcBroadcast struct {
	PacketLength int16
	Message      string
}
