// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcBuyingStoreEntry is the event emitted when a zc_buying_store_entry packet is received.
// ZC_BUYING_STORE_ENTRY packet (PACKET_ZC_BUYING_STORE_ENTRY)
type ZcBuyingStoreEntry struct {
	MakerAID uint32 // makerAID field
	PacketType int16 // packetType field
}
