// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcCartoff is the event emitted when a zc_cartoff packet is received.
// ZC_CARTOFF packet (PACKET_ZC_CARTOFF)
type ZcCartoff struct {
	PacketID uint16 // Packet identifier
}
