// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcChangestatePet is the event emitted for the zc_changestate_pet action.
type ZcChangestatePet struct {
	Type int8
	GID  []byte
	Data []byte
}
