// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcClaninfo is the event emitted when a zc_claninfo packet is received.
// ZC_CLANINFO packet (PACKET_ZC_CLANINFO)
type ZcClaninfo struct {
	AllyCount uint8 // AllyCount field
	AntagonistCount uint8 // AntagonistCount field
	ClanID uint32 // ClanID field
	PacketLength int16 // PacketLength field
	PacketType int16 // PacketType field
}
