// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcCouplestatus is the event emitted for the zc_couplestatus action.
type ZcCouplestatus struct {
	StatusType    uint32
	DefaultStatus int32
	PlusStatus    int32
}
