// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcChangeGuild is the event emitted when a zc_change_guild packet is received.
// ZC_CHANGE_GUILD packet (PACKET_ZC_CHANGE_GUILD)
type ZcChangeGuild struct {
	AID uint32 // AID field
	Emblem_id uint16 // emblem_id field
	Guild_id int32 // guild_id field
	PacketType int16 // packetType field
}
