// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcChangeItemOption is the event emitted when a zc_change_item_option packet is received.
// ZC_CHANGE_ITEM_OPTION packet (PACKET_ZC_CHANGE_ITEM_OPTION)
type ZcChangeItemOption struct {
	Index int16 // index field
	PacketType int16 // packetType field
	RefiningLevel int16 // refiningLevel field
	Slot []byte // slot field
}
