// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcCompass is the event emitted for the zc_compass action.
type ZcCompass struct {
	NpcId uint32
	Type uint32
	XPos uint32
	YPos uint32
	Id uint8
	Color uint32
}
