// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcCouplename is the event emitted when a zc_couplename packet is received.
// ZC_COUPLENAME packet (PACKET_ZC_COUPLENAME)
type ZcCouplename struct {
	PacketID int16 // Packet identifier
	PartnerName string // Partner character name
}
