// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcCheckname is the event emitted when a zc_checkname packet is received.
// ZC_CHECKNAME packet (PACKET_ZC_CHECKNAME)
type ZcCheckname struct {
	BaseLevel int16 // Character base level
	CharId int32 // Character ID being checked
	Class int16 // Character class/job ID
	PacketType int16 // Packet type identifier (0x0A14)
	Name [24]byte // Character name (24-byte string)
}
