// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcDialogWindowPos2 is the event emitted for the zc_dialog_window_pos2 action.
type ZcDialogWindowPos2 struct {
	X []byte
	Y []byte
}
