// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcDebugmsg is the event emitted for the zc_debugmsg action.
type ZcDebugmsg struct {
	PacketLength int16
	Color        int32
	Message      string
}
