// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcDeleteMemberFromGroup is the event emitted for the zc_delete_member_from_group action.
type ZcDeleteMemberFromGroup struct {
	AID []byte
	CharacterName string
	Result int8
}
