// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcDeleteItemFromBody is the event emitted when a zc_delete_item_from_body packet is received.
// ZC_DELETE_ITEM_FROM_BODY packet (PACKET_ZC_DELETE_ITEM_FROM_BODY)
type ZcDeleteItemFromBody struct {
	PacketID int16 // Packet identifier
	DeleteType int16 // Reason for item deletion
	InventoryIndex uint16 // Inventory item index
	Amount int16 // Number of items deleted
}
