// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcDeleteItemFromCart is the event emitted for the zc_delete_item_from_cart action.
type ZcDeleteItemFromCart struct {
	Index uint16
	Amount int32
}
