// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcDialogWindowPos2 is the event emitted when a zc_dialog_window_pos2 packet is received.
// ZC_DIALOG_WINDOW_POS2 packet (PACKET_ZC_DIALOG_WINDOW_POS2)
type ZcDialogWindowPos2 struct {
	PacketType int16 // PacketType field
}
