// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcExtendBodyitemSize is the event emitted for the zc_extend_bodyitem_size action.
type ZcExtendBodyitemSize struct {
	ExpansionSize int16
}
