// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcEquipmentEffect is the event emitted when a zc_equipment_effect packet is received.
// ZC_EQUIPMENT_EFFECT packet (PACKET_ZC_EQUIPMENT_EFFECT)
type ZcEquipmentEffect struct {
	Aid uint32 // aid field
	Effects []byte // effects field
	PacketLength int16 // packetLength field
	PacketType int16 // packetType field
	Status int8 // status field
}
