// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcEquipArrow is the event emitted when a zc_equip_arrow packet is received.
// ZC_EQUIP_ARROW packet (PACKET_ZC_EQUIP_ARROW)
type ZcEquipArrow struct {
	Index uint16 // Arrow inventory index
}
