// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcExecExchangeItem is the event emitted when a zc_exec_exchange_item packet is received.
// ZC_EXEC_EXCHANGE_ITEM packet (PACKET_ZC_EXEC_EXCHANGE_ITEM)
type ZcExecExchangeItem struct {
	Type uint8 // Execution result (0=success)
}
