// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcEquipitemDamaged is the event emitted for the zc_equipitem_damaged action.
type ZcEquipitemDamaged struct {
	EquipLocation uint16
	GID           uint32
}
