// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcFriendsList is the event emitted for the zc_friends_list action.
type ZcFriendsList struct {
	PacketLength int16
	Friends []byte
}
