// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcGoldpccafePoint is the event emitted for the zc_goldpccafe_point action.
type ZcGoldpccafePoint struct {
	IsActive   int8
	Mode       int8
	Point      int32
	PlayedTime int32
}
