// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcGuildNotice is the event emitted for the zc_guild_notice action.
type ZcGuildNotice struct {
	Subject string
	Notice  string
}
