// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcInventoryStart is the event emitted when a zc_inventory_start packet is received.
// ZC_INVENTORY_START packet (PACKET_ZC_INVENTORY_START)
type ZcInventoryStart struct {
	InvType uint8 // invType field
	Name string // name field
	PacketLength int16 // packetLength field
	PacketType int16 // packetType field
}
