// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcInventoryTab is the event emitted when a zc_inventory_tab packet is received.
// ZC_INVENTORY_TAB packet (PACKET_ZC_INVENTORY_TAB)
type ZcInventoryTab struct {
	PacketID int16 // Packet identifier
	InventoryIndex int16 // Inventory index of the item
	IsFavorite bool // Whether item is marked as favorite
}
