// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcLonglongparChange is the event emitted for the zc_longlongpar_change action.
type ZcLonglongparChange struct {
	VarID  uint16
	Amount int64
}
