// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcMergeItemOpen is the event emitted when a zc_merge_item_open packet is received.
// ZC_MERGE_ITEM_OPEN packet (PACKET_ZC_MERGE_ITEM_OPEN)
type ZcMergeItemOpen struct {
	Items []byte // items field
	PacketLen uint16 // packetLen field
	PacketType int16 // packetType field
}
