// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcMenuList is the event emitted when a zc_menu_list packet is received.
// ZC_MENU_LIST packet (PACKET_ZC_MENU_LIST)
type ZcMenuList struct {
	NpcID uint32 // NPC ID
	Menu string // Menu items string
}
