// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcNotifyEffect3 is the event emitted when a zc_notify_effect3 packet is received.
// ZC_NOTIFY_EFFECT3 packet (PACKET_ZC_NOTIFY_EFFECT3)
type ZcNotifyEffect3 struct {
	Aid uint32 // aid field
	EffectId uint32 // effectId field
	Num uint32 // num field
	PacketType int16 // packetType field
}
