// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcNpcackServermove is the event emitted when a zc_npcack_servermove packet is received.
// ZC_NPCACK_SERVERMOVE packet (PACKET_ZC_NPCACK_SERVERMOVE)
type ZcNpcackServermove struct {
	IP uint32 // Map server IP address (4-byte binary)
	Map string // New map name (null-terminated)
	Port uint16 // Map server port
	X uint16 // Spawn X coordinate on new map
	Y uint16 // Spawn Y coordinate on new map
}
