// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcNotifyMemberinfoToGroupm is the event emitted when a zc_notify_memberinfo_to_groupm packet is received.
// ZC_NOTIFY_MEMBERINFO_TO_GROUPM packet (PACKET_ZC_NOTIFY_MEMBERINFO_TO_GROUPM)
type ZcNotifyMemberinfoToGroupm struct {
	PacketType int16 // PacketType field
	Job int16 // job field
	Level int16 // level field
}
