// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcNotifyStoreitemCountinfo is the event emitted for the zc_notify_storeitem_countinfo action.
type ZcNotifyStoreitemCountinfo struct{}
