// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcNotifyBargainSaleSelling is the event emitted for the zc_notify_bargain_sale_selling action.
type ZcNotifyBargainSaleSelling struct{}
