// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcNotifyGroundskill is the event emitted when a zc_notify_groundskill packet is received.
// ZC_NOTIFY_GROUNDSKILL packet (PACKET_ZC_NOTIFY_GROUNDSKILL)
type ZcNotifyGroundskill struct {
	AID uint32 // AID field
	PacketType int16 // PacketType field
	SKID uint16 // SKID field
	Level int16 // level field
	StartTime uint32 // startTime field
	XPos int16 // xPos field
	YPos int16 // yPos field
}
