// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcOpenReformUi is the event emitted when a zc_open_reform_ui packet is received.
// ZC_OPEN_REFORM_UI packet (PACKET_ZC_OPEN_REFORM_UI)
type ZcOpenReformUi struct {
	ITID int32 // ITID field
	PacketType int16 // PacketType field
}
