// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcOpenSearchStoreInfo is the event emitted when a zc_open_search_store_info packet is received.
// ZC_OPEN_SEARCH_STORE_INFO packet (PACKET_ZC_OPEN_SEARCH_STORE_INFO)
type ZcOpenSearchStoreInfo struct {
	Effect uint16 // effect field
	PacketType int16 // packetType field
	RemainingUses uint8 // remainingUses field
}
