// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcPositionInfo is the event emitted when a zc_position_info packet is received.
// ZC_POSITION_INFO packet (PACKET_ZC_POSITION_INFO)
type ZcPositionInfo struct {
	PacketLength int16 // PacketLength field
	PacketType int16 // PacketType field
	PosInfo []byte // posInfo field
}
