// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcPositionIdNameInfo is the event emitted when a zc_position_id_name_info packet is received.
// ZC_POSITION_ID_NAME_INFO packet (PACKET_ZC_POSITION_ID_NAME_INFO)
type ZcPositionIdNameInfo struct {
	PacketLength int16 // PacketLength field
	PacketType int16 // PacketType field
	PosInfo []byte // Guild position names (inline struct: positionID + posName[24])
}
