// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcPlayNpcBgm is the event emitted for the zc_play_npc_bgm action.
type ZcPlayNpcBgm struct {
	Bgm string
	PacketLength int16
	PlayType uint8
}
