// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcPropertyHomun is the event emitted for the zc_property_homun action.
type ZcPropertyHomun struct {
	Name        string
	Flags       uint8
	Level       uint16
	Hunger      uint16
	Intimacy    uint16
	ItemId      uint32
	Atk2        uint16
	Matk        uint16
	Hit         uint16
	Crit        uint16
	Def         uint16
	Mdef        uint16
	Flee        uint16
	Amotion     uint16
	Hp          uint32
	MaxHp       uint32
	Sp          uint32
	MaxSp       uint32
	Exp         int64
	ExpNext     int64
	SkillPoints uint16
	Range       uint16
}
