// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcPartyJoinReq is the event emitted for the zc_party_join_req action.
type ZcPartyJoinReq struct {
	GRID      []byte
	GroupName string
}
