// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcPreviewMacroDetectorCaptcha is the event emitted for the zc_preview_macro_detector_captcha action.
type ZcPreviewMacroDetectorCaptcha struct {
	PacketLength int16
	CaptchaKey string
	ImageData string
}
