// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcPcPurchaseMyitemlist is the event emitted when a zc_pc_purchase_myitemlist packet is received.
// ZC_PC_PURCHASE_MYITEMLIST packet (PACKET_ZC_PC_PURCHASE_MYITEMLIST)
type ZcPcPurchaseMyitemlist struct {
	AID uint32 // AID field
	Items []byte // items field
	PacketLength int16 // packetLength field
	PacketType int16 // packetType field
}
