// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcReqAnswerMacroDetector is the event emitted when a zc_req_answer_macro_detector packet is received.
// ZC_REQ_ANSWER_MACRO_DETECTOR packet (PACKET_ZC_REQ_ANSWER_MACRO_DETECTOR)
type ZcReqAnswerMacroDetector struct {
	PacketType int16 // PacketType field
	RetryCount uint8 // retryCount field
}
