// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcReqAckAgitInvestment is the event emitted for the zc_req_ack_agit_investment action.
type ZcReqAckAgitInvestment struct {
	Castle_id int8
	Economy int32
	Defense int32
}
