// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcRandomUpgradeItemUiOpen is the event emitted for the zc_random_upgrade_item_ui_open action.
type ZcRandomUpgradeItemUiOpen struct {
	ItemId uint32
}
