// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcRandomCombineItemUiOpen is the event emitted for the zc_random_combine_item_ui_open action.
type ZcRandomCombineItemUiOpen struct {
	ItemId int32
}
