// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcRoleChange is the event emitted when a zc_role_change packet is received.
// ZC_ROLE_CHANGE packet (PACKET_ZC_ROLE_CHANGE)
type ZcRoleChange struct {
	Flag int32 // flag field
	PacketType int16 // packetType field
}
