// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcReqTakeoffEquipAck is the event emitted for the zc_req_takeoff_equip_ack action.
type ZcReqTakeoffEquipAck struct {
	Index uint16
	WearLocation uint32
	Flag []byte
}
