// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcResponseEnchant is the event emitted for the zc_response_enchant action.
type ZcResponseEnchant struct {
	MsgId int32
	ITID  uint32
}
