// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcSkillinfoUpdate2 is the event emitted when a zc_skillinfo_update2 packet is received.
// ZC_SKILLINFO_UPDATE2 packet (PACKET_ZC_SKILLINFO_UPDATE2)
type ZcSkillinfoUpdate2 struct {
	Id uint16 // id field
	Inf int32 // inf field
	Level uint16 // level field
	PacketType int16 // packetType field
	Range2 uint16 // range2 field
	Sp uint16 // sp field
	UpFlag uint8 // upFlag field
}
