// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcShortcutKeyList is the event emitted for the zc_shortcut_key_list action.
type ZcShortcutKeyList struct {
	Hotkey []byte
	Rotate int8
	Tab int16
}
