// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcShortcutKeyList is the event emitted when a zc_shortcut_key_list packet is received.
// ZC_SHORTCUT_KEY_LIST packet (PACKET_ZC_SHORTCUT_KEY_LIST)
type ZcShortcutKeyList struct {
	PacketType int16 // packetType field
}
