// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcSkillDisappear is the event emitted when a zc_skill_disappear packet is received.
// Ground skill disappeared from map (area effect spell removed)
type ZcSkillDisappear struct {
	ID uint32 // Ground skill entry ID to remove
}
