// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcSeCashshopOpen is the event emitted for the zc_se_cashshop_open action.
type ZcSeCashshopOpen struct {
	CashPoints  uint32
	KafraPoints uint32
	Tab         uint32
}
