// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcTrycaptureMonster is the event emitted for the zc_trycapture_monster action.
type ZcTrycaptureMonster struct {
	Result int8
}
