// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcTalkboxChatcontents is the event emitted for the zc_talkbox_chatcontents action.
type ZcTalkboxChatcontents struct {
	Aid uint32
	Message string
}
