// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcTargetSpirits is the event emitted when a zc_target_spirits packet is received.
// ZC_TARGET_SPIRITS packet (PACKET_ZC_TARGET_SPIRITS)
type ZcTargetSpirits struct {
	ActorID uint32 // Target actor ID
	Count int16 // Number of spirits
	UnknownValue int16 // Unknown value
}
