// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcUiOpen2 is the event emitted when a zc_ui_open2 packet is received.
// ZC_UI_OPEN2 packet (PACKET_ZC_UI_OPEN2)
type ZcUiOpen2 struct {
	PacketType int16 // PacketType field
	UIType int8 // UIType field
	Data int64 // data field
}
