// Code generated by internal/codegen. DO NOT EDIT.

package events

// ZcViewCamerainfo is the event emitted for the zc_view_camerainfo action.
type ZcViewCamerainfo struct {
	Action   int8
	Range    []byte
	Rotation []byte
	Latitude []byte
}
