// Code generated by internal/codegen. DO NOT EDIT.

package send

// CaConnectInfoChanged is the request struct for the ca_connect_info_changed action.
// CA_CONNECT_INFO_CHANGED packet (PACKET_CA_CONNECT_INFO_CHANGED)
type CaConnectInfoChanged struct {
	PacketType int16 // packetType field
}
