// Code generated by internal/codegen. DO NOT EDIT.

package send

// CaLogin2 is the request struct for the ca_login2 action.
// Login with MD5 hashed password (CA_LOGIN2)
type CaLogin2 struct {
	Master_version uint8 // Client type identifier (see CLIENT_TYPES)
	PacketType int16 // packetType field
	Password_salted_md5 string // MD5 hashed password (16 bytes)
	Version uint32 // Client version number
}
