// Code generated by internal/codegen. DO NOT EDIT.

package send

// CzAdventurerAgencyJoinReq is the request struct for the cz_adventurer_agency_join_req action.
type CzAdventurerAgencyJoinReq struct {
	GID []byte
	AID []byte
}
