// Code generated by internal/codegen. DO NOT EDIT.

package send

// CzDynamicnpcCreateRequest is the request struct for the cz_dynamicnpc_create_request action.
type CzDynamicnpcCreateRequest struct {
	Name string
}
