// Code generated by internal/codegen. DO NOT EDIT.

package send

// CzGradeEnchantSelectEquipment is the request struct for the cz_grade_enchant_select_equipment action.
type CzGradeEnchantSelectEquipment struct {
	Index int16
}
