// Code generated by internal/codegen. DO NOT EDIT.

package send

// CzGradeEnchantCloseUi is the request struct for the cz_grade_enchant_close_ui action.
// CZ_GRADE_ENCHANT_CLOSE_UI packet (PACKET_CZ_GRADE_ENCHANT_CLOSE_UI)
type CzGradeEnchantCloseUi struct {
	PacketType int16 // PacketType field
}
