// Code generated by internal/codegen. DO NOT EDIT.

package send

// CzGetAccountLimtiedSaleList is the request struct for the cz_get_account_limtied_sale_list action.
type CzGetAccountLimtiedSaleList struct {
}
