// Code generated by internal/codegen. DO NOT EDIT.

package send

// CzInventoryTab is the request struct for the cz_inventory_tab action.
// CZ_INVENTORY_TAB packet (PACKET_CZ_INVENTORY_TAB)
type CzInventoryTab struct {
	Index int16 // Item inventory index
	Favorite bool // Whether item is marked as favorite
}
