// Code generated by internal/codegen. DO NOT EDIT.

package send

// CzMoveItemFromBodyToCart is the request struct for the cz_move_item_from_body_to_cart action.
type CzMoveItemFromBodyToCart struct {
	Index int16
	Count []byte
}
