// Code generated by internal/codegen. DO NOT EDIT.

package send

// CzNpcExpandedBarterMarketClose is the request struct for the cz_npc_expanded_barter_market_close action.
// CZ_NPC_EXPANDED_BARTER_MARKET_CLOSE packet (PACKET_CZ_NPC_EXPANDED_BARTER_MARKET_CLOSE)
type CzNpcExpandedBarterMarketClose struct {
	PacketType int16 // packetType field
}
