// Code generated by internal/codegen. DO NOT EDIT.

package send

// CzNpcExpandedBarterMarketClose is the request struct for the cz_npc_expanded_barter_market_close action.
type CzNpcExpandedBarterMarketClose struct {
}
