// Code generated by internal/codegen. DO NOT EDIT.

package send

// CzNpcMarketPurchase is the request struct for the cz_npc_market_purchase action.
type CzNpcMarketPurchase struct {
	PacketLength int16
	List []byte
}
