// Code generated by internal/codegen. DO NOT EDIT.

package send

// CzNpcBarterMarketPurchase is the request struct for the cz_npc_barter_market_purchase action.
type CzNpcBarterMarketPurchase struct {
	List []byte
}
