// Code generated by internal/codegen. DO NOT EDIT.

package send

// CzReqMakingarrow is the request struct for the cz_req_makingarrow action.
// CZ_REQ_MAKINGARROW packet (PACKET_CZ_REQ_MAKINGARROW)
type CzReqMakingarrow struct {
	ItemID uint16 // Item ID for arrow making
}
