// Code generated by internal/codegen. DO NOT EDIT.

package send

// CzReqPreviewMacroDetector is the request struct for the cz_req_preview_macro_detector action.
type CzReqPreviewMacroDetector struct {
	CaptchaID []byte
}
