// Code generated by internal/codegen. DO NOT EDIT.

package send

// CzReqAgitInvestment is the request struct for the cz_req_agit_investment action.
type CzReqAgitInvestment struct {
	Castle_id int8
}
