// Code generated by internal/codegen. DO NOT EDIT.

package send

// CzReqCashBargainSaleItemInfo is the request struct for the cz_req_cash_bargain_sale_item_info action.
// CZ_REQ_CASH_BARGAIN_SALE_ITEM_INFO packet (PACKET_CZ_REQ_CASH_BARGAIN_SALE_ITEM_INFO)
type CzReqCashBargainSaleItemInfo struct {
	PacketLength int16 // Packet length
	AccountID uint32 // Account ID
	ItemID uint16 // Item ID to query bargain sale info
}
