// Code generated by internal/codegen. DO NOT EDIT.

package send

// CzRequestPerfectEnchant is the request struct for the cz_request_perfect_enchant action.
// CZ_REQUEST_PERFECT_ENCHANT packet (PACKET_CZ_REQUEST_PERFECT_ENCHANT)
type CzRequestPerfectEnchant struct {
	ITID uint32 // ITID field
	PacketType int16 // PacketType field
	Enchant_group int64 // enchant_group field
	Index int16 // index field
}
