// Code generated by internal/codegen. DO NOT EDIT.

package send

// CzReqApplyMacroDetector is the request struct for the cz_req_apply_macro_detector action.
type CzReqApplyMacroDetector struct {
	AID uint32
}
