// Code generated by internal/codegen. DO NOT EDIT.

package send

// CzReqRefining is the request struct for the cz_req_refining action.
// CZ_REQ_REFINING packet (PACKET_CZ_REQ_REFINING)
type CzReqRefining struct {
	BlacksmithBlessing int8 // blacksmithBlessing field
	Index int16 // index field
	ItemId uint32 // itemId field
	PacketType int16 // packetType field
}
