// Code generated by internal/codegen. DO NOT EDIT.

package send

// CzRequestPerfectEnchant is the request struct for the cz_request_perfect_enchant action.
type CzRequestPerfectEnchant struct {
	Enchant_group int64
	Index int16
	ITID uint32
}
