// Code generated by internal/codegen. DO NOT EDIT.

package send

// CzRandomUpgradeItemUiClose is the request struct for the cz_random_upgrade_item_ui_close action.
type CzRandomUpgradeItemUiClose struct {
}
