// Code generated by internal/codegen. DO NOT EDIT.

package send

// CzReqApplyBargainSaleItem is the request struct for the cz_req_apply_bargain_sale_item action.
type CzReqApplyBargainSaleItem struct {
}
