// Code generated by internal/codegen. DO NOT EDIT.

package send

// CzReqOpenMsgboxExtendBodyitemSize is the request struct for the cz_req_open_msgbox_extend_bodyitem_size action.
type CzReqOpenMsgboxExtendBodyitemSize struct {
}
