// Code generated by internal/codegen. DO NOT EDIT.

package send

// CzShortcutKeyChange2 is the request struct for the cz_shortcut_key_change2 action.
// CZ_SHORTCUT_KEY_CHANGE2 packet (PACKET_CZ_SHORTCUT_KEY_CHANGE2)
type CzShortcutKeyChange2 struct {
	Hotkey []byte // hotkey field (hotkey_data struct - 7 bytes: uint8 isSkill, uint32 id, uint16 count)
	Index uint16 // index field
	PacketType int16 // packetType field
	Tab uint16 // tab field
}
