// Code generated by internal/codegen. DO NOT EDIT.

package send

// CzUploadMacroDetectorCaptcha is the request struct for the cz_upload_macro_detector_captcha action.
type CzUploadMacroDetectorCaptcha struct {
	PacketLength int16
	CaptchaKey string
	ImageData string
}
