// Code generated by internal/codegen. DO NOT EDIT.

package send

// FriendsReply is the request struct for the friends_reply action.
type FriendsReply struct {
	AID   uint32
	CID   uint32
	Reply uint32
}
