// Manually implemented — not generated by codegen.
// CZ_GUILD_CHAT / 0x017E has no C struct; it is variable-length and parsed
// manually in clif.cpp via clif_process_message with whisperFormat=false.

package send

// GuildChat is the request struct for the guild_chat action.
// Name is the sender's character name; Message is the text to send.
// The wire format encodes "Name : Message\0" identical to PublicChat.
type GuildChat struct {
	Name    string
	Message string
}
