// Code generated by internal/codegen. DO NOT EDIT.

package send

// NpcTalkText is the request struct for the npc_talk_text action.
type NpcTalkText struct {
	PacketSize uint16
	GID int32
	Value string
}
