// Manually implemented — not generated by codegen.
// PACKET_CZ_REQUEST_CHAT has no C struct definition in rAthena; it is a
// variable-length packet parsed manually in clif.cpp.

package send

// PublicChat is the request struct for the public_chat action.
// The client sends "Name : Message\0" as the text body.
type PublicChat struct {
	Name    string
	Message string
}
