// Code generated by internal/codegen. DO NOT EDIT.

package send

// SelectCharacter is the request struct for the select_character action.
// Select a character to login
type SelectCharacter struct {
	Slot uint8 // Character slot number
}
