// Code generated by internal/codegen. DO NOT EDIT.

package send

// SelectAccessibleMap is the request struct for the select_accessible_map action.
type SelectAccessibleMap struct {
	Slot int8
	Mapnumber int8
}
