// Code generated by internal/codegen. DO NOT EDIT.

package send

// ShopBuy is the request struct for the shop_buy action.
// Buy items from NPC shop
type ShopBuy struct {
	ItemList []byte // List of items to buy (variable length)
}
