// Code generated by internal/codegen. DO NOT EDIT.

package send

// UnequipItem is the request struct for the unequip_item action.
// Unequip an item
type UnequipItem struct {
	Index uint16 // Inventory slot index
}
