// Manually implemented — not generated by codegen.
// CZ_WISPER / 0x0096 has no C struct; it is variable-length and parsed
// manually in clif.cpp via clif_process_message with whisperFormat=true.

package send

// Whisper is the request struct for the whisper action.
// Target is the recipient character name (max 23 chars + NUL, padded to 24).
// Message is the chat text to send.
type Whisper struct {
	Target  string
	Message string
}
